### ISSUE TITLE
4.6.0 appears to include the minified version of 4.5.2

### ISSUE THREAD

**Issue by rogerguess** [tonytomov/jqGrid#1000]
Top of jquery.jqGrid.min.js shows this:

/*
 jqGrid  4.5.2 - jQuery Grid
 Copyright (c) 2008, Tony Tomov, tony@trirand.com
 Dual licensed under the MIT and GPL licenses
 http://www.opensource.org/licenses/mit-license.php
 http://www.gnu.org/licenses/gpl-2.0.html
 Date: 2013-05-21
*/

**Comment by tonytomov** [comment]
Hello,

Thank you for reporting. Unfortunately I can't do anything. You can manually minify the source (jquery.jqGrid.js),  which is up to date.

Best Regards,
Tony
