### ISSUE TITLE
jqGrid support bootstrap 5?

### ISSUE THREAD

**Issue by kstan79** [tonytomov/jqGrid#1003]
I'm using commercial license jqgrid since 2017, under bootstrap 3 and it work so far so good. Recently we wish to upgrade into bootstrap 5, does it support bootstrap 5? I notice there is some reference said bootstrap4 is supported.

**Comment by tonytomov** [comment]
Hello,

Yes, we have plans to Support Bootstrap 5 in the near future.

Kind Regards,
Tony

**Comment by kstan79** [comment]
ok, i'd tested run jqgrid's bootstrap 4 setup in bootstrap 5.1 environment. it seems able to render the grid and show the data. i think no much issue for you guy to support 5.1
<img width="600" alt="jqgridsample" src="https://user-images.githubusercontent.com/1889979/132778246-e30a4b49-ff5c-488d-a5c8-56d9370d9435.png">

**Comment by tonytomov** [comment]
Bootstrap 5 is supported now in 5.6
