### ISSUE TITLE
Multiselect Button Turns Off By Itself

### ISSUE THREAD

**Issue by unle70** [tonytomov/jqGrid#1007]
I have recently downloaded the latest version of jqGrid (v5.6.0) and jQuery itself (V3.6.0).
Today I have noticed a new issue with the multi-select button (the "master" button on the "titles" section of the grid". When clicking this button, the "onSelectAll" event triggers just fine. At that time the "status" parameter is correct and the checkbox is ON. But sometime after this event is finished, the checkbox turns OFF by itself.

After several hours of checking I have pinpointed the problem to another event which is internal in jqGrid. It is a "click" event on the "th" surrounding the checkbox (th#grid_id_cb). If this is allowed to run, the checkbox gets turned off by itself. Maybe it's because the jqGrid code (lines# 5100-5148 in the full jqGrid.js file) return "false". Currently I was able to overcome the problem by running "event.stopPropagation()" at the last line of my customized "onSelectAll" handler. 

I didn't have this issue with previous versions, so I'm wondering if any modification was done on this section.

**Comment by tonytomov** [comment]
Thanks. I will check this.
As far as I remember no changes for multiselct code, but will check this too.

**Comment by tonytomov** [comment]
I was able to reproduce the problem. 
Have fixed it in GitHub.
Thank you.

**Comment by tonytomov** [comment]
Will  close it. Fell free to reopen if there is a problem
