### ISSUE TITLE
Use `height:auto` with max-height to avoid infinite growth

### ISSUE THREAD

**Issue by systemsolutionweb** [tonytomov/jqGrid#1008]
Is there a way to achieve auto height but with a limit to prevent the grid from growing too large?

I found `maxHeight` property of others forks, has this plugins a similar property for that?
https://github.com/free-jqgrid/jqGrid/blob/c97869acd736030242469337343106f6cb56f731/js/grid.base.js#L6141-L6143
```js
if (p.maxHeight) {
    $(grid.bDiv).css("max-height", p.maxHeight + (isNaN(p.maxHeight) ? "" : "px"));
}
```

thanks in advance, this plugin is amazing

**Comment by tonytomov** [comment]
This is the original plugin. We have such option via method - it is named maxGridHeight. It is documented in [method list](http://www.guriddo.net/documentation/guriddo/javascript/user-guide/basic-grid/#method-list) and you can [find it here](https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L6545).

Best Regards

**Comment by systemsolutionweb** [comment]
Thanks for your reply

>We have such option via method - it is named maxGridHeight

Yes but that method doesn't work when the jgrid start with `data` and `datatype:'local'`, that is why i'm searching for a property config

**Example:** Maybe is a bug
https://jsfiddle.net/anz5u2r7/3/
On this example i did add a `delRowData` after 3 seconds for the resize

**Comment by systemsolutionweb** [comment]
> ```js
> $("#grid1").maxGridHeight('set',200).trigger("jqGridAfterGridComplete.setMaxHeght");
> ```

is `setMaxHeght` a typo?? maybe must be `jqGridAfterGridComplete.setMaxHeight`

https://github.com/tonytomov/jqGrid/blob/e593e6013236ec8c6f977671bfe64395ccd571ca/js/grid.base.js#L6581

Oh, was intencional or a mistake?

**Comment by tonytomov** [comment]
Have do more improvements on the method https://github.com/tonytomov/jqGrid/commit/2bf28a0c56ac7ff90f825aee6ca44142f67878f0

**Comment by tonytomov** [comment]
Since the method only set the css max-height property without to do any future action you may need in your case to call setGridWidth with the current width + scrollOffset width. This can be done like this

```js
var gridprm = $("#grid1").jqGrid('getGridParam'); // get all grid parameters
var neww = gridprm.width + gridprm.scrollOffset-2; // two pixel for the borders
$("#grid1").maxGridHeight('set',250).jqGrid('setGridWidth', neww);
```

**Comment by tonytomov** [comment]
Hello,

I will see what I can do

**Comment by tonytomov** [comment]
I have played with this and try to include the suggested code, but there is a problem in case the sum of height of the current  grid view is smaller than the max-width

![maxgridheight](https://user-images.githubusercontent.com/79932/157304186-b7a50714-3232-4aa9-a220-aa1611099e0b.png)

As can be seen we need to do additional check if the current height is greater than the max one

**Comment by tonytomov** [comment]
I have updated the source. You will need just in initial loading set the new grid width. From this point resizeGrid will do the job.

**Comment by tonytomov** [comment]
It seems I have rewritre the maxGridHeight again. You do not need to do anything just cal it and it will do the job angain with resize grid.

Best Regards

**Comment by systemsolutionweb** [comment]
Amazing, thanks
