### ISSUE TITLE
beforeSelectRow not turning off the selection checkbox in multi-select 

### ISSUE THREAD

**Issue by unle70** [tonytomov/jqGrid#1010]
Hello,
I'm using multi-select mode so I'm getting the column of checkboxes where I can turn ON the rows I want to select.
I'm trying to use the the "beforeSelectRow" event in order to prevent selection of some rows, if they don't meet a certain criteria. I'm doing this by returning "false" from the event handler. But now I've noticed that although a "false" is returned, the selection checkbox eventually turns ON.

A temporary workaround is to force the checkbox OFF (unchecked) by myself with: $(e.target).prop('checked', false) 
I hope this could be fixed sometime in the future.

**Comment by tonytomov** [comment]
Hello ,

Thanks.
I have try to fix the problem. Please check if it is working as expected and let me know.

**Comment by unle70** [comment]
Hi Tony,
Yes, working fine now.

Thank you very much,
Udi

**Comment by angeljqv** [comment]
Issue must be closed
