### ISSUE TITLE
An escape error was encountered while using autoencode option 

### ISSUE THREAD

**Issue by HandyCC** [tonytomov/jqGrid#1013]
When autoencode option is set to true. The original data is &amp;lt; , which became  < after editing.

**Comment by tonytomov** [comment]
Hello,

This is by default. It is the same as you use any web editor - the data stored in database is encoded, but when you edit it it is decoded.

If your original data is already encoded and you do not want to decode it in editing, just disable the autoencode and when you post,  do a manual encoding of the <,>,... and other  chars.

**Comment by HandyCC** [comment]
I misunderstood. Thank you for your reply
