### ISSUE TITLE
Unconsistente behaivor on `showSummaryOnHide`

### ISSUE THREAD

**Issue by PaolaRuby** [tonytomov/jqGrid#1014]
Hi, i think that i find a bug

When i am using `grouping`  with subgroups and `groupSummary:[true,true], showSummaryOnHide:true, groupCollapse:true`, 
it shows all groups summaries, but when you click on one group for open and close again, it shows only the last summary, 
i think that the last behaivor is the right one, because all the subgroups summaries at the same time is confusing

 _**Using:** jqGrid JS - v5.7.0_
![image](https://user-images.githubusercontent.com/79208489/177576646-5bdeaa95-5a03-4a93-9fe6-848d8f67b766.png)
**DEMO:** https://jsfiddle.net/w3gcd2zf/

**Comment by PaolaRuby** [comment]
Thanks for answer

No problem for me, i'm just testing

**Comment by tonytomov** [comment]
Hello,

I have play with this and really find the behavior strange.

IMHO the true behavior is to show the summary grouping details always when the group is collapsed.

This come from the nature of the option showSummaryOnHide. This mean that the summary column(s) shlod be show instead if the grouping is collapsed. 

I have do a fix where when the group is collapsed the summary show anyway.

One more bug is fixed - In case of showSummaryOnHide false when you expand the main group the summary is not shown - it is shown only if you click on the last subgroup (which IMHO is wrong)

**Comment by PaolaRuby** [comment]
> but when you click on one group for open and close again, it shows only the last summary,
i think that the last behaivor is the right one, because all the subgroups summaries at the same time is confusing

Maybe can be a new feature `showSummaryOnColapse`, when the behavior shows the sumary of last group colapsed and visible, instead of all groups and subgroups summaries, because when you have more subgroups, looks more confusing, and there is not a way to set a custom message for each subgroup

This is the final result of this fix
![image](https://user-images.githubusercontent.com/79208489/178280733-7c51c89a-5206-4052-be7b-335d0e2131d3.png)

Thanks for answer
