### ISSUE TITLE
Unconsistente behaivor on `summaryTpl` and `groupText`

### ISSUE THREAD

**Issue by PaolaRuby** [tonytomov/jqGrid#1015]
On `groupText` i can use another cols, but if i try the same on `summaryTpl` it gives me `undefined`
How can i achieve the same result on both??

Maybe is a bug or it is not supported and could be a new feature

 _**Using:** jqGrid JS - v5.7.0_
![image](https://user-images.githubusercontent.com/79208489/177588497-b90e709e-778f-4e7e-8b93-37320f871d7f.png)
**DEMO:** https://jsfiddle.net/yLzmop75/1/
```js
///
colModel: [
   ///
   { 'name': 'col', summaryType:'sum', summaryTpl:'<b>{0} - {group_name}</b>' }, // get undefined
],
grouping: true,
groupingView: {
  groupField: ['group'],
  groupText:["{0} - <b>{group_name}</b>"], // it works
  ///
```

**Comment by PaolaRuby** [comment]
Hi again, 
```diff
-tmpdata= "<td "+$t.formatCol(k,1,'')+">"+$.jgrid.template(tplfld, vv, fdata.cnt, fdata.dataIndex, fdata.displayValue)+ "</td>";
+tmpdata= "<td "+$t.formatCol(k,1,'')+">"+$.jgrid.template(tplfld, vv, fdata.cnt, fdata.dataIndex, fdata.displayValue, fdata.summary)+ "</td>";
```
https://github.com/tonytomov/jqGrid/blob/10bca9a05bdec7eb69885bc6c7bf4306161fa14b/js/grid.grouping.js#L346
looks like adding `fdata.summary` on that line fix the problem
![image](https://user-images.githubusercontent.com/79208489/177594188-2d31121b-d78f-47fa-b548-46686564b70b.png)
**DEMO:** https://jsfiddle.net/nh9a7xo2/

**Comment by tonytomov** [comment]
Thanks for look at this.
With your solution you can attach fields only if they have summaryTpl property. Any field without this property can't be set. 
Instead of this I will include your solution.

Thank you.

**Comment by PaolaRuby** [comment]
Thanks
Of course, only when they have summary property, same functionality as `groupText`
