### ISSUE TITLE
After upgrade from 5.8.2 to current master ajax json call fail after using `datatype:local`

### ISSUE THREAD

**Issue by fredsal** [tonytomov/jqGrid#1028]
I make a debug and if i comment next line everything works again
```diff
if(ts.p.datatype==='local' && !grp._locgr) {
-   ts.p.datatype = 'jsonstring';
+   // ts.p.datatype = 'jsonstring';
    ts.p.datastr = ts.p.data;
}
```
https://github.com/tonytomov/jqGrid/blob/a64f9320c8bad23b19b97df2928bb1ec245f6af0/js/grid.base.js#L3815-L3818

Well, i have a grid with `local` datatype, but, depending on changes on a parent table, i change the datatype to `json` and reload data(only when required), but with that line the grid never reload the rows, but the rows do come in an ajax call, I don't know if it's a bug or if I'm doing something wrong, but what's clear to me is that with version 5.8.2 everything worked

This is the code for changing `datatype` and reload grid data
```js
// i found this code on stackoverflow, and it was working without problems till now
let grid=$('#jqGrid');
grid.setGridParam({datatype:'json',postData:$.extend(true,OriginalData,MyDataObject)}); // MyDataObject is custom data
grid.trigger('reloadGrid',[page:1]);
```
I could make a demo if it is necessary

**PD:** Sorry for mi english, i'm learning, please be patient

**Comment by tonytomov** [comment]
Hello,

We always need a demo in order to look at this.
Thank you

**Comment by fredsal** [comment]
@tonytomov thanks for answering, 
After digging I found out that 8.2 is not the problem, the problem is in master, 
And the problem only show with `grouping:true` propertie, without that everything work as expected

**Demos:**
  **Working Demo on v8.2:** https://jsfiddle.net/2g6xphqr/2/
  **Failing Demo on Master:** https://jsfiddle.net/tu2nepag/

Best regards, Fred

**Comment by tonytomov** [comment]
Hello,

Thank you very much for the test case.

The problem you point is more conceptual, rather than a bug.
In your first working example (offical 5.8.2) if you replace datatype local with jsonstring and set datastr the problem is the same. Like this

```js
  $("#jqGrid").jqGrid({
    url: '/echo/json/',
    datatype: "jsonstring",
    datastr :"",
    ...
```

Switching from one datatype to another when grouping require  to reset a certain parameter in order this to work.
I have created a method called groupingResetCalcs which should be called before you trigger the grid with the new datatype.

```js
let grid=$('#jqGrid');
grid.jqGrid('setGridParam' , {datatype:'json',postData:{...})
.jqGrid('groupingResetCalcs')
.trigger('reloadGrid',{page:1});
```

We will describe this into the docs when the new release appear.

The commit is in GitHub, so you can test it.

Best Regards

**Comment by fredsal** [comment]
**Test `groupingResetCalcs`:** https://jsfiddle.net/jom906n1/ (_it works_)

It would have been great if it was something more internal since it looks like a BC to me, all previous versions worked, but at least I can fix it with `groupingResetCalcs`

Thank you very much, this is a great plugin

**Comment by systemsolutionweb** [comment]
@tonytomov hi, if we already set `datatype` to `local`, why change it to `jsonstring` internally?
So, if we check if datatype is local on runtime, it would be false because it changes to jsonstring?

**Comment by systemsolutionweb** [comment]
@tonytomov hi, if we already set `datatype` to `local`, why change it to `jsonstring` internally?
So, if we check if datatype is local on runtime, it would be false because it changes to jsonstring?

What about this, for avoid breaking changes
```js
setGridParam : function (newParams, overwrite){
  return this.each(function(){
	if( $.jgrid.isNull(overwrite) ) {
		overwrite = false;
	}
	if (this.grid && typeof newParams === 'object') {
                // start added fix
                if (this.p.grouping && newParams.datatype && ['json', 'jsonp'].includes(newParams.datatype)) {
                      $(this).jqGrid('groupingResetCalcs');
                }
                // end added fix
		if(overwrite === true) {
			var params = $.extend({}, this.p, newParams);
			this.p = params;
		} else {
			$.extend(true,this.p,newParams);
		}
	}
  });
},
```
https://github.com/tonytomov/jqGrid/blob/a95cc5bd59f07f5045068b67e095814f0f2b7387/js/grid.base.js#L5888-L5902

**Comment by fredsal** [comment]
@systemsolutionweb y test your solution, it works without changing all mi code
**Demo:** https://jsfiddle.net/gra2Lwpe/1/

**Comment by tonytomov** [comment]
Reason for this change was that with local datatype there was not possible to loop through the entire data and perform calculation when grouping is on, while with jsonstring this is possible.

More over after set jsonstring and performing calculation the datatype becomes local 
[See here:](https://github.com/tonytomov/jqGrid/blob/v5.8.2/js/jquery.jqGrid.js#L3758-L3764)

**Comment by fredsal** [comment]
Hi @tonytomov, seems like you fixed this in: https://github.com/tonytomov/jqGrid/commit/f2b3de9223eb8006dc42f147add0945532e71988 _v5.8.8_, **am I right?**
https://github.com/tonytomov/jqGrid/blob/7b23577790f4720c8b8f0e722534b8065f7799c7/js/grid.base.js#L4068-L4073


>I make a debug and if i comment next line everything works again
>```diff
>if(ts.p.datatype==='local' && !grp._locgr) {
>-   ts.p.datatype = 'jsonstring';
>+   // ts.p.datatype = 'jsonstring';
>    ts.p.datastr = ts.p.data;
>}
>```
>https://github.com/tonytomov/jqGrid/blob/a64f9320c8bad23b19b97df2928bb1ec245f6af0/js/grid.base.js#L3815-L3818
