### ISSUE TITLE
" setGroupHeaders " function in JQGRID affect search and filtering, both header and form search

### ISSUE THREAD

**Issue by V-for-velascoDMY23** [tonytomov/jqGrid#1030]
![image](https://user-images.githubusercontent.com/68804300/224241456-e099b5a6-793a-4adb-b3de-087f8ed6e36f.png)
![image](https://user-images.githubusercontent.com/68804300/224241582-ba0dfcf5-b9e2-4c65-af6b-df17114ff149.png)
![image](https://user-images.githubusercontent.com/68804300/224241722-a5c1e044-7bfe-438c-a976-48297635c689.png)

**Comment by tonytomov** [comment]
Hello,

Can you please provide a working test case?
Thank you.

**Comment by V-for-velascoDMY23** [comment]
Hi, 

When I include the  column that's searchable in the group header it automatically disables the search function. Both search button in pager and inline nav search.  

You can see the affected lines above. Thank you

**Comment by parallels999** [comment]
@V-for-velascoDMY23 when @tonytomov says a **working test case** means a **runing  test case**
example: https://jsfiddle.net/jom906n1/

**Comment by tonytomov** [comment]
Not sure if this example describes the problem. Can you please check again? I do not see calling of setGroupHeaders

**Comment by V-for-velascoDMY23** [comment]
Hi @tonytomov 
When I reported this issue, I was using jqGrid 5.7.0 then now I updated it to your current version, which solved the problem. thanks!
I'm currently developing an intranet web app, so I am not using online JS and CSS libraries.
