### ISSUE TITLE
 jqGrid exporting of subgrids to excel/CSV is now supported or not?

### ISSUE THREAD

**Issue by V-for-velascoDMY23** [tonytomov/jqGrid#1031]
@tonytomov jqGrid exporting of subgrids to excel/CSV is now supported or still not?

**Comment by tonytomov** [comment]
Hello,

It is not supported and we do not plan to work on this feature.

**Comment by V-for-velascoDMY23** [comment]
Hi @tonytomov 
Thank you for your immediate response
