### ISSUE TITLE
Summary not formatted on grouping header

### ISSUE THREAD

**Issue by fredsal** [tonytomov/jqGrid#1034]
On footer row and  footer group the field appears formatted, but on header group doesn't

![image](https://github.com/tonytomov/jqGrid/assets/79155632/aea76c70-13e0-4b97-a4d5-49903513c9ce)

**Demo:** https://jsfiddle.net/132xkcLa/

Best regards, Fred

**Comment by tonytomov** [comment]
I try to fix the problem. Please let me know if the fix work for you.

**Comment by fredsal** [comment]
With that the demo is not showing anything
https://jsfiddle.net/1wqLn8fc/

**Comment by fredsal** [comment]
How about making it optional, so you avoid breaking changes?
**Example:** 
`summaryFormat: 'currency'`
Or
`summaryFormat: true`, when true it uses formatter from colModel

**Comment by tonytomov** [comment]
In jqGrid setup of your demo  change datatype from 'local' to 'json'. It work for me when I do this change.

**Comment by tonytomov** [comment]
By default summary fields are formated with the formatter when applied. The data on header and footer row can be formated and can be not depending on the parameter - **formatHeaderData formatFooterData**. The only exception was the grouping text, which is fixed with last commit.

**Comment by fredsal** [comment]
Ok, my mistake, seems to be working fine, thank you very much

**Comment by parallels999** [comment]
hi @tonytomov,  

I use `gridConc.getGridParam("groupingView").groups` for getting group totals(for custom calculations)
With this change, now i only get formated values(breaking change for me), 
there is a possibility that we can get the value without formatting too, for example
```json
v : 'FORMATED_VALUE',
vv: UNFORMATD_VALUE
```

**Comment by tonytomov** [comment]
I have added this requirement, but the property is named uv (un-formatted value) . Maybe it is a good idea to have option what to display - formatted or un-formatted value

**Comment by parallels999** [comment]
>  Maybe it is a good idea to have option what to display - formatted or un-formatted value

that would be great
