### ISSUE TITLE
[bootstrap4] Word `Empty` on sort icon

### ISSUE THREAD

**Issue by parallels999** [tonytomov/jqGrid#1036]
This happens in bootstrap 4

![image](https://github.com/tonytomov/jqGrid/assets/109294935/0cc7faf8-fc00-4730-83e9-f2926e4864c1)

This commit is causing the problem https://github.com/tonytomov/jqGrid/commit/bcdac3955f5180efdfd6990d94fb074bc4ae5c2d

shows empty even if one of the 2 options is selected(asc, desc)

**Comment by tonytomov** [comment]
Hello,

Can you please prepare a working example with the problem.
Thank you

**Comment by parallels999** [comment]
Done
https://jsfiddle.net/jcmg6v2a/1/
![image](https://github.com/tonytomov/jqGrid/assets/109294935/c930fa58-dcb8-44a5-a9aa-9ee2d1cae9b7)
