### ISSUE TITLE
`footerrow` problem using `setFrozenColumns`, `groupingView` and `height:'auto'`

### ISSUE THREAD

**Issue by parallels999** [tonytomov/jqGrid#1041]
https://jsfiddle.net/6pa0ts37/3/

![image](https://github.com/tonytomov/jqGrid/assets/109294935/9e8a8933-c279-443f-acc9-f3703c42bd75)

**UPDATE:**
https://jsfiddle.net/79qz5gym/, I fix it by adding:
```js
onClickGroup: () => {
  grid.destroyFrozenColumns();
  grid.setFrozenColumns();
}
```

**Comment by tonytomov** [comment]
Please, read the docs for the [limitations](https://www.guriddo.net/documentation/guriddo/javascript/user-guide/frozencols/#notes-limitations) when frozen columns are on

**Comment by parallels999** [comment]
This could be fixed easy adding the next code on `groupingToggle`
```js
if(frz && $t.p.height === 'auto'){
  $t.grid.fbDiv.height($($t).height());
  if($t.grid.fsDiv) {
    $t.grid.fsDiv.css('top', $t.grid.fbDiv.position().top + $t.grid.fbDiv.height() + 'px');
  }
}
```
Here:
https://github.com/tonytomov/jqGrid/blob/630d3d84856967a257f516c82ef5d4707c10a3c3/js/grid.grouping.js#L274-L275

**Comment by tonytomov** [comment]
setFrozenColumns as described into the docs should be called as last method. In one of your example 
https://jsfiddle.net/ocxyrpb8/1/
you call it before grouping which causes the problem. If you call frozen columns after grouping the result will be as expected.

As for your recommendation I will check it - thanks.

**Comment by parallels999** [comment]
>https://jsfiddle.net/ocxyrpb8/1/
>you call it before grouping which causes the problem

I already changed the order, it's the same result
**DEMO:** https://jsfiddle.net/gmezbxfL/1/
![image](https://github.com/tonytomov/jqGrid/assets/109294935/d9ba0575-4140-4642-b284-08cd7a5f061f)

**Comment by tonytomov** [comment]
As last method- after visibility setting 
```js
$('#jqGridParent').css('visibility','');
```

**Comment by parallels999** [comment]
> As last method- after visibility setting

That is the problem that I describe, when the grid does not have visibility frozen it does not work correctly, I have the grid hidden, and when the tab is activated the header is not displayed, 
>when the grid has no visibility, setGroupHeaders set no text on the header,

I add the `$('#jqGridParent').css('visibility','');` and `<div id="jqGridParent" style="visibility:hidden;">` to show the problem, 
Of course without these changes it works correctly, even if I put it after `$('#jqGridParent').css('visibility','');`, but in my case I have tabs and the grid is hidden until the user activates the tab

**Comment by tonytomov** [comment]
Thanks. I have fixed the visibility problem.

Your fix for height auto isn't enough - in your example try to resize some column - the footer text disappear
