### ISSUE TITLE
config “ coloptions ” is invalid parameter

### ISSUE THREAD

**Issue by hp3423** [tonytomov/jqGrid#1052]
when "colMenu" is true , "coloptions" is invalid.

So I see the source code, I find an error on line 5058.
![微信截图_20231208171827](https://github.com/tonytomov/jqGrid/assets/12905493/ac36ad53-feda-4c4f-a49b-508bb0ac6143)

"coloptions" is not in "cm".
I think the correct code should be

`cm = ts.p.colModel[index], op = $.extend({sorting:true, columns: true, filtering: true, seraching:true, grouping:true, freeze : true}, ts.p.coloptions),`

**Comment by hp3423** [comment]
Thanks.

Can we add a common parameter,like "colOptions",or we must modify "coloptions" on every column .
The code like this:
`cm = ts.p.colModel[index], op = $.extend({sorting:true, columns: true, filtering: true, seraching:true, grouping:true, freeze : true},ts.p.colOptions, cm.coloptions),`

**Comment by tonytomov** [comment]
We have grid option called cmTemplate, where you can add common options for all colModel items.
See [docs for this](https://www.guriddo.net/documentation/guriddo/javascript/user-guide/basic-grid/#colmodel-options)

**Comment by hp3423** [comment]
Thanks,I got it
