### ISSUE TITLE
`showSummaryOnHide` problem when collapse last subgroup

### ISSUE THREAD

**Issue by PaolaRuby** [tonytomov/jqGrid#1064]
This happens only in the collapse of the last subgroup of every main group, it hides the sum of the higher main groups
![image](https://github.com/tonytomov/jqGrid/assets/79208489/eefcb0ae-c567-457a-ad2b-0bf3963563b1)
**DEMO:** https://jsfiddle.net/fdnyqx1h/1/

Maybe related #1014 https://github.com/tonytomov/jqGrid/commit/c8b0a999e2866f4b7c151ae8707ab18a240374e1

**Comment by tonytomov** [comment]
Thanks. 

I have fixed it, but the behavior is little changed. I think the last fix is better.

Regards
Tony

**Comment by PaolaRuby** [comment]
Thanks
