### ISSUE TITLE
When celledit=true, a 'setSelection' makes the row impossible to unselect.

### ISSUE THREAD

**Issue by noelant** [tonytomov/jqGrid#173]
Hi Tony,

when
   your grid is cellEdit=true, 
then
   if you select a row with jqGrid('setSelection',xxx)
   then this row can't be unselected anymore: the [tr] keeps 'ui-state-highlight' class even if you clic another row, or if you 'resetSelection'.

**Comment by tonytomov** [comment]
Hello,

Not sure that  the fix is easy. Will close the issue, but it will stay in my bug list.
