### ISSUE TITLE
jqGrid should support  Asynchronous Module Definition (AMD) API

### ISSUE THREAD

**Issue by jd-boyd** [tonytomov/jqGrid#217]
Jquery 1.7 adds support for the Asynchronous Module Definition (AMD) API ( https://github.com/amdjs/amdjs-api/wiki/AMD ). It would be great if jqGrid would also now support this. Usually the easiest, most flexible way to do this is to find the appropriate Universal Module Definition pattern from https://github.com/umdjs/umd (probably their simple jqueryPlugin template, https://github.com/umdjs/umd/blob/master/jqueryPlugin.js ) and apply it to jqGrid.

**Comment by dallincoons** [comment]
+1

**Comment by tonytomov** [comment]
This is already supported as of version 4.8. Please look here: http://guriddo.net/?p=123585
