### ISSUE TITLE
What is the license for jqGrid?

### ISSUE THREAD

**Issue by EntitySpaces** [tonytomov/jqGrid#226]
I expected to see this on github but cannot find it anywhere?

**Comment by punitganshani** [comment]
@tonytomov the link to license is broken. 
Does this product require purchasing for commercial products? How different is it from Guriddo jqGrid?

**Comment by tonytomov** [comment]
Hello,

This is Guriddo jqGrid. You may need to read this: http://www.trirand.com/blog/?p=1438

Regards,
