### ISSUE TITLE
Wrong div height for jqGrid frozen column

### ISSUE THREAD

**Issue by fingermark** [tonytomov/jqGrid#263]
I can't figure out exactly what's going on, but the bottom part of my frozen column isn't freezing.  When I manually increase the height on that div, then everything looks fine.  Also, when I uncomment the following code, it looks fine:

```csss
.ui-jqgrid tr.jqgrow td { height: 22px; }
```

I call setFrozenColumns.  The result is a frozen column w/ a wrong height, resulting in the bottom part of that div not freezing.

```html
<div class="frozen-bdiv ui-jqgrid-bdiv" style="position: absolute; left: 0px; top: 45px; overflow-y: hidden; height: 94px;">
```

All code is up-to-date (bb5673c).

**Comment by tonytomov** [comment]
Hello,

I will close this with a hope if you are interested to reopen this with test case.

Regards
