### ISSUE TITLE
Inline edit in bad state after expand in treegrid

### ISSUE THREAD

**Issue by Annxii** [tonytomov/jqGrid#335]
The problem occurs when using inline edit and load on demand in treegrid-mode. When a cell is selected for edit and a node above the selected cell is expanded, the row index used for the edit cell is still the same after the expand. This puts the grid in a bad state since those row indexes are no longer correct. When changing cell the saveCell-function ends up trying to save "undefined", because it can't find the input-element anymore.

I fixed it in my own project by making a correction in the loadedData-function to the grid.p.iRow, grid.savedRow and the id of the input-element ([iRow]_[columnname])

**Comment by tonytomov** [comment]
Hello,

It is difficult to reproduce this. I will close it and if you want to reopen it, please provide a test case.

Kind Regards.
