### ISSUE TITLE
Pager Width calculation grid inside a small containers

### ISSUE THREAD

**Issue by dharapvj** [tonytomov/jqGrid#340]
Currently, the pager width is calculated using following code in JQgrid. (Approx line:https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L1916)

```javascript
tdw = $(".ui-jqgrid").css("font-size") || "11px";
$(document.body).append("<div id='testpg' class='ui-jqgrid ui-widget ui-widget-content' style='font-size:"+tdw+";visibility:hidden;' ></div>");
twd = $(pgl).clone().appendTo("#testpg").width();
$("#testpg").remove();
```

In certain situations, when we bring the grid page using ajax, and attach it to a "smaller width" container div, following snippet calculated wrong width of the pager div. This happens since it attaches the testpg to the body element.

I propose that we should use the attach the testpg to container div of jqgrid itself. This way the correct calculation of width will happen.

**Comment by tonytomov** [comment]
Hello,

Just fixed this.

Regards
