### ISSUE TITLE
Add horizontal scroll when no data is loaded

### ISSUE THREAD

**Issue by fingermark** [tonytomov/jqGrid#358]
It seems that horizontal scroll is only on when there is data (overflow-x is auto for ui-jqgrid-bdiv).  But when there is no data, there is no horizontal scroll, because (ui-jqgrid-hdiv has overlflow-x: hidden, for a reason).  The problem I'm having is with the filter toolbar.  I have a lot of headers that require horizontal scrolling.  When a user filters data to the point that no records return, the horizontal scroll bar disappears.  If the column that caused no results is hidden, the user cannot remove the text in that column.

Would it be possible to change .ui-jqgrid-hdiv to overflow-x: auto when no results are returned?  And back to hidden when results are returned.

I'm not on HEAD, so I'm not sure if this has been added.

I'm doing this right now by adding the following to loadComplete:

```
    if grid.jqGrid('getGridParam', 'reccount') == 0
      $(".ui-jqgrid-hdiv").css("overflow-x", "auto")
    else
      $(".ui-jqgrid-hdiv").css("overflow-x", "hidden")
```

**Comment by maelmonnier** [comment]
Thanks all :+1: . It is slightly better with a reset of the height to 0 when there is data :
```
if ($("#grid_[[${random}]]").jqGrid('getGridParam', 'reccount') == 0)
		  $(".jqgfirstrow").css("height","1px");
	  else
		  $(".jqgfirstrow").css("height","0px");
```

**Comment by tommy1308** [comment]
Hey,
whats the current Status, Is there a bugfix available asap?

**Comment by tonytomov** [comment]
This is already realized. with option emptyRecordRow
