### ISSUE TITLE
addRowData: First row incorrectly having ui-priority-secondary applied

### ISSUE THREAD

**Issue by mdownes** [tonytomov/jqGrid#369]
Hi,
 When adding a row using addRowData and position "last" the "ui-priority-secondary" class is being applied to the first row instead of the second row.

I am calling addRowData in a for loop passing in one item of data each time.

The offending code seems to be :
                 if (t.p.altRows === true && !aradd) {
                        if (pos == "last") {
                            if ((t.rows.length - 1) % 2 == 1) { $(t.rows[t.rows.length - 1]).addClass(cn); }
                        } else {
                            $(t.rows).each(function (i) {
                                if (i % 2 == 1) { $(this).addClass(cn); }
                                else { $(this).removeClass(cn); }
                            });
                        }
                    }

At this point t.rows.length already has a row in it (the row used for cell widths and heights of 0px ) with a class of jqgfirstrow, which should not be used as part of the calculation.

When using addJSONData() the alternative rows are applied correctly.

You can see a test example at the following url:(NOte red highlighting should not be on the first row.

http://jsfiddle.net/7vg94/

Kind Regards,

Maurice

**Comment by tonytomov** [comment]
Thanks. I will investigate this. It seems that not only this part of code in addRowData is wrong,

**Comment by tonytomov** [comment]
Sorry puch the wrong button. Reopening

**Comment by tonytomov** [comment]
Fixed. Thanks
