### ISSUE TITLE
Multiple Rows Drag and Drop

### ISSUE THREAD

**Issue by immobilia** [tonytomov/jqGrid#388]
Multiple rows drag and drop.
Able to select several rows, and drag and drop em. 
Instead drag and drop row by row.

**Comment by joankent** [comment]
I need this functionallity, do you have any idea how can I do it?

**Comment by tonytomov** [comment]
Hello,

As I mentioned in my post before two years I do not plan to develop this feature.

You can play with drag and drop jqGrid method **gridDnD**  (in grid.jqueryui.js module).

Kind Regards
Tony

**Comment by joankent** [comment]
Never mind :)

It work's for me, I hope that it work's for you:

`
$("#myTable1").jqGrid('gridDnD',{
	connectWith:'#myTable2',
	beforedrop: function (e, ui, getdata, source, target) {
		beforejqdrop(e, ui, getdata, source, target); //call external function beforejqdrop
	},
	dragcopy: 'false'
});

function beforejqdrop(e, ui, getdata, source, target){
    if(confirm('is it ok to drop it?')){
		var rowsids = $("#myTable1").jqGrid('getGridParam', 'selarrrow'); //this is the magic!
		
		$.ajax({
			url: 'ajaxurl.php',
			data: { 'rowsids': rowsids },
			success: function(data){
				if(data.check == 1){
					ui.helper.dropped = true; //drop rows
					$("#myTable1").trigger("reloadGrid");
					$("#myTable2").trigger("reloadGrid");
				}else{
					ui.helper.dropped = false; //reset rows
					alert('Error to execute!');
				}
				return false;
			},
			error: function(){
				ui.helper.dropped = false;
				alert('Error to execute!');
			},
			cache: false,
			type: "POST",
			dataType: 'json'
		});
	}else{
		ui.helper.dropped = false; //reset rows
	} //end if
	
} //end function

`

**Comment by JrPD** [comment]
my Solution
gridDnD: function (opts)
        {
            return this.each(function ()
            {
                var $t = this;
                if (!$t.grid) { return; }
                // Currently we disable a treeGrid drag and drop
                if ($t.p.treeGrid) { return; }
                if (!$.fn.draggable || !$.fn.droppable) { return; }
                function updateDnD()
                {
                    var datadnd = $.data($t, "dnd");
                    $("tr.jqgrow:not(.ui-draggable)", $t).draggable($.isFunction(datadnd.drag) ? datadnd.drag.call($($t), datadnd) : datadnd.drag);
                }
                function selectedRows()
                {
                    var selectedIds = $($t).jqGrid("getGridParam", "selarrrow");
                    return $($t).children().children().filter(function (id, el)
                    {
                        return selectedIds.indexOf(el.id) !== -1;
                    });
                }
                function IsDragAllowed(targetId)
                {
                    var selectedIds = $($t).jqGrid("getGridParam", "selarrrow");
                    if (selectedIds.indexOf(targetId) === -1)
                    {
                        return false;
                    }
                    return true;
                }
                function IsDropAllowed()
                {
                    var disabledCount = $($t).find("tr.jqgrow.border-top.dropSelectedElement.disableSelection").length;
                    var allCount = $($t).find("tr.jqgrow.border-top.dropSelectedElement").length;
                    return allCount - disabledCount > 0;
                }

                function SubstituteHelper($)
                {
                    var oldMouseStart = $.ui.draggable.prototype._mouseStart;
                    $.ui.draggable.prototype._mouseStart = function (event, overrideHandle, noActivation)
                    {
                        this._trigger("prepare", event, this);
                        oldMouseStart.apply(this, [event, overrideHandle, noActivation]);
                    };

                    $.extend($.ui.draggable.prototype.options, {
                        multiple: true,
                        cloneHelper: false,
                        selected: "[aria-selected=true]"
                    });

                    $.ui.plugin.add('draggable', 'multiple', {
                        prepare: function (evt, ui)
                        {
                            var $this = $(this),
                                inst = $this.data('ui-draggable');

                            if (inst.options.multiple == true)
                            {
                                // create helper. empty if move from not selected element
                                let $t = $(this).closest("table.ui-jqgrid-btable");
                                let targetId = evt.currentTarget.id;
                                var selectedIds = $($t).jqGrid("getGridParam", "selarrrow");
                                inst.options._selected = $("#" + $t[0].id + " " + inst.options.selected);
                                inst.options.cloneHelper = inst.options.cloneHelper || inst.options.helper == 'clone';

                                let helper = selectedIds.indexOf(targetId) == -1 ? $('<tr></tr>') : createHelper(inst.options._selected);
                                $("body").mouseleave(function ()
                                {
                                    $(helper).trigger("mouseup");
                                });
                                inst.options.helper = function ()
                                {
                                    return helper;
                                }
                            }
                        },
                    });
                    $.ui.plugin.add("draggable", "scroll", {
                        start: function (event, ui, i)
                        {
                            var scrollable = i.element.closest(".MvcDialInnerBody");//MvcDialInnerBody MvcPanelBody
                            if (scrollable)
                                i.scrollParentNotHidden = scrollable;

                            if (i.scrollParentNotHidden[0] !== i.document[0] && i.scrollParentNotHidden[0].tagName !== "HTML")
                            {
                                i.overflowOffset = i.scrollParentNotHidden.offset();
                            }
                        }
                    });

                    function createHelper(selected)
                    {
                        var selContainer = $('<table></table>');

                        $.each(selected, function ()
                        {
                            clone = $(this).clone();

                            clone.addClass('ui-draggable-clone');
                            clone.removeClass("ui-state-highlight ui-state-hover");

                            selContainer.append(clone);
                            selContainer.addClass("ui-state-highlight");
                        });
                        var row = $('<tr></tr>').addClass('ui-draggable-container').css('border', '0').height(0);
                        return row.append(selContainer);
                    }
                }

                var appender = "<table id='jqgrid_dnd' class='ui-jqgrid-dnd'></table>";
                if ($("#jqgrid_dnd")[0] === undefined)
                {
                    $('body').append(appender);
                }

                if (typeof opts == 'string' && opts == 'updateDnD' && $t.p.jqgdnd === true)
                {
                    updateDnD();
                    return;
                }
                opts = $.extend({
                    "drag": function (opts)
                    {
                        return $.extend({
                            start: function (ev, ui)
                            {
                                $($t).find("tr.jqgrow.just-dropped").removeClass("just-dropped");
                                // if we are in subgrid mode try to collapse the node
                                if ($t.p.subGrid)
                                {
                                    var subgid = $(ui.helper).attr("id");
                                    try
                                    {
                                        $($t).jqGrid('collapseSubGridRow', subgid);
                                    } catch (e) { }
                                }
                                // hack
                                // drag and drop does not insert tr in table, when the table has no rows
                                // we try to insert new empty row on the target(s)
                                for (var i = 0; i < $.data($t, "dnd").connectWith.length; i++)
                                {
                                    if ($($.data($t, "dnd").connectWith[i]).jqGrid('getGridParam', 'reccount') == "0")
                                    {
                                        $($.data($t, "dnd").connectWith[i]).jqGrid('addRowData', 'jqg_empty_row', {});
                                    }
                                }
                                ui.helper.addClass("ui-state-highlight");
                                if (opts.multiple)
                                {
                                    $($t).find("tr.jqgrow").droppable({
                                        hoverClass: "ui-state-hover",
                                        over: function (e, ui)
                                        {
                                            //todo insert top, bottom
                                            $(this).addClass("dropSelectedElement border-top");
                                        },
                                        out: function (e, ui)
                                        {
                                            $(this).removeClass("dropSelectedElement border-top");
                                        },
                                    });
                                    $($t).find("tr.jqgrow").draggable({
                                        multiple: opts.multiple,
                                        drag: function (ev, ui)
                                        {
                                            return IsDragAllowed(ev.target.id);
                                        }
                                    });
                                    $("tr", ui.helper).each(function (j, row)
                                    {
                                        $("td", row).each(function (i)
                                        {
                                            this.style.width = $t.grid.headers[i].width + "px";
                                        });
                                        $(row).removeClass("just-dropped");
                                    });
                                }
                                else
                                {
                                    $("td", ui.helper).each(function (i)
                                    {
                                        this.style.width = $t.grid.headers[i].width + "px";
                                    });
                                }
                                if (opts.onstart && $.isFunction(opts.onstart)) { opts.onstart.call($($t), ev, ui); }
                            },
                            stop: function (ev, ui)
                            {
                                if (opts.multiple)
                                {
                                    var rows = selectedRows();
                                    $.each(rows, function ()
                                    {
                                        var $this = $(this);
                                        $this.removeClass('ui-draggable-hidden');
                                    });
                                    if (IsDropAllowed())
                                    {
                                        $($t).jqGrid('resetSelection');
                                        rows.addClass("just-dropped");
                                        rows.removeClass("border-top dropSelectedElement");
                                    }

                                    // clean up "over" borders
                                    $($t).find("tr.jqgrow").removeClass("border-top dropSelectedElement");
                                }
                                else
                                {
                                    if (ui.helper.dropped && !opts.dragcopy)
                                    {
                                        var ids = $(ui.helper).attr("id");
                                        if (ids === undefined) { ids = $(this).attr("id"); }
                                        $($t).jqGrid('delRowData', ids);
                                    }
                                    // if we have a empty row inserted from start event try to delete it
                                    for (var i = 0; i < $.data($t, "dnd").connectWith.length; i++)
                                    {
                                        $($.data($t, "dnd").connectWith[i]).jqGrid('delRowData', 'jqg_empty_row');
                                    }
                                }
                                if (opts.onstop && $.isFunction(opts.onstop)) { opts.onstop.call($($t), ev, ui); }
                            }
                        }, opts.drag_opts || {});
                    },
                    "drop": function (opts)
                    {
                        return $.extend({
                            accept: function (d)
                            {
                                if (!$(d).hasClass('jqgrow')) { return d; }
                                var tid = $(d).closest("table.ui-jqgrid-btable");
                                if (tid.length > 0 && $.data(tid[0], "dnd") !== undefined)
                                {
                                    if (opts.multiple)
                                    {
                                        if (!IsDropAllowed())
                                        {
                                            return false;
                                        }

                                        var sourceId = d.attr("id");
                                        var selectedIds = $($t).jqGrid('getGridParam', 'selarrrow');
                                        return selectedIds.indexOf(sourceId) === -1 ? false : true;
                                    }
                                    else
                                    {
                                        var cn = $.data(tid[0], "dnd").connectWith;
                                        return $.inArray('#' + $.jgrid.jqID(this.id), cn) != -1 ? true : false;
                                    }
                                }
                                return false;
                            },
                            drop: function (ev, ui)
                            {
                                if (opts.multiple)
                                {
                                    var dropOver = $($t).find('.dropSelectedElement');
                                    var getdata = null;

                                    // todo if the first is selected - insert the top
                                    $.each(selectedRows(), function (pos, current)
                                    {
                                        $(current).insertBefore(dropOver);
                                    });
                                }
                                else
                                {
                                    if (!$(ui.draggable).hasClass('jqgrow')) { return; }
                                    var accept = $(ui.draggable).attr("id");
                                    var getdata = ui.draggable.parent().parent().jqGrid('getRowData', accept);
                                    if (!opts.dropbyname)
                                    {
                                        var j = 0, tmpdata = {}, nm;
                                        var dropmodel = $("#" + $.jgrid.jqID(this.id)).jqGrid('getGridParam', 'colModel');
                                        try
                                        {
                                            for (var key in getdata)
                                            {
                                                nm = dropmodel[j].name;
                                                if (!(nm == 'cb' || nm == 'rn' || nm == 'subgrid'))
                                                {
                                                    if (getdata.hasOwnProperty(key) && dropmodel[j])
                                                    {
                                                        tmpdata[nm] = getdata[key];
                                                    }
                                                }
                                                j++;
                                            }
                                            getdata = tmpdata;
                                        } catch (e) { }
                                    }
                                    ui.helper.dropped = true;
                                    if (opts.beforedrop && $.isFunction(opts.beforedrop))
                                    {
                                        //parameters to this callback - event, element, data to be inserted, sender, reciever
                                        // should return object which will be inserted into the reciever
                                        var datatoinsert = opts.beforedrop.call(this, ev, ui, getdata, $('#' + $.jgrid.jqID($t.p.id)), $(this));
                                        if (typeof datatoinsert != "undefined" && datatoinsert !== null && typeof datatoinsert == "object") { getdata = datatoinsert; }
                                    }
                                    if (ui.helper.dropped)
                                    {
                                        var grid;
                                        if (opts.autoid)
                                        {
                                            if ($.isFunction(opts.autoid))
                                            {
                                                grid = opts.autoid.call(this, getdata);
                                            } else
                                            {
                                                grid = Math.ceil(Math.random() * 1000);
                                                grid = opts.autoidprefix + grid;
                                            }
                                        }
                                        // NULL is interpreted as undefined while null as object
                                        $("#" + $.jgrid.jqID(this.id)).jqGrid('addRowData', grid, getdata, opts.droppos);
                                    }
                                }
                                if (opts.ondrop && $.isFunction(opts.ondrop)) { opts.ondrop.call(this, ev, ui, getdata); }
                            }
                        }, opts.drop_opts || {});
                    },
                    "onstart": null,
                    "onstop": null,
                    "beforedrop": null,
                    "ondrop": null,
                    "drop_opts": {
                        "activeClass": "ui-state-active",
                        "hoverClass": "ui-state-hover"
                    },
                    "drag_opts": {
                        "revert": "invalid",
                        "helper": "clone",
                        "cursor": "move",
                        "appendTo": "#jqgrid_dnd",
                        "zIndex": 5000
                    },
                    "dragcopy": false,
                    "dropbyname": false,
                    "droppos": "first",
                    "autoid": true,
                    "autoidprefix": "dnd_"
                }, opts || {});

                if (!opts.connectWith) { return; }
                opts.connectWith = opts.connectWith.split(",");
                opts.connectWith = $.map(opts.connectWith, function (n) { return $.trim(n); });
                $.data($t, "dnd", opts);

                if (opts.multiple)
                {
                    SubstituteHelper(jQuery);
                }
                if ($t.p.reccount != "0" && !$t.p.jqgdnd)
                {
                    updateDnD();
                }
                $t.p.jqgdnd = true;
                for (var i = 0; i < opts.connectWith.length; i++)
                {
                    var cn = opts.connectWith[i];
                    $(cn).droppable($.isFunction(opts.drop) ? opts.drop.call($($t), opts) : opts.drop);
                }
            });
