### ISSUE TITLE
selrow broken when multiselect: true

### ISSUE THREAD

**Issue by gluparia** [tonytomov/jqGrid#390]
Looks like the selrow option reads incorrectly with the multiselect option set to true.

Scenario:
A multiselect jqgrid.
An external button which, when clicked, writes to the console the selrow and selarrrow values for the grid.

When clicking on an unselected row the row becomes selected. Subsequent reads to selrow return the rowid of the last cliked row. This keeps consistent when selecting other rows.

When clicking on a selected row the row becomes unselected. Subsequent reads to selrow seem to return the rowid of the first selected row, instead of returning the rowid of the row which was selected last (or, if the deselected row was also the last selected, the row selected just before it).

Note:
The selarrrow array seems to behave right by keeping the true "last selected row" in its last position.

**Comment by tonytomov** [comment]
Hello,

Fixed. Now it return last selected.
