### ISSUE TITLE
setFrozenColumns ondblClickRow  Uncaught TypeError: Cannot read property 'ondblClickRow' of undefined 

### ISSUE THREAD

**Issue by ibmsoft** [tonytomov/jqGrid#419]
a grid use setFrozenColumns 
frozen a,b column

in the ondblClickRow 
when column is a or b then

Uncaught TypeError: Cannot read property 'ondblClickRow' of undefined

**Comment by tonytomov** [comment]
Hello,

Can not reproduce the bug. In the last version (4.8) the event work as expected
