### ISSUE TITLE
gridResize option prevents full hiddengrid, hidegrid functionality

### ISSUE THREAD

**Issue by dvdotsenko** [tonytomov/jqGrid#42]
Hi.

Enabling 'gridResize' (which is an awesome feature) "breaks" 'hidegrid' functionality (minimize / maximize button on right in caption bar). The contents of the grid are rolled up, but frame remains in place and is not resized, leaving an empty rectangle on the page.

Hope this one is looked at, because both features are great to have for pages that have multiple instances of jqGrid.

Daniel.

**Comment by tonytomov** [comment]
Hello,

Thanks. I have fixed this in more elegant way.

Regards
