### ISSUE TITLE
frozen columns do not resize when gridResize is used

### ISSUE THREAD

**Issue by y-p** [tonytomov/jqGrid#425]
When using frozen columns + gridResize at the same time,
using the resize handle to reduce the height of the
grid doesn't resize the frozen columns.

Using 4.4.4+ , 7d00484

Workaround: hook the resize event and trigger a reload
which also re-renders the grid. Tested on Chrome 24.

```javascript
<table id="myGrid"></table>
...
  var req=null

$("#gbox_myGrid").bind( "resize", function(event, ui) {
   if (req ) clearTimeout(req);

   req=setTimeout(function() {
        $grid.trigger("reloadGrid");
        req=null
          },25);
});
```

**Comment by tonytomov** [comment]
Thanks. Fixed
