### ISSUE TITLE
Column's height are different when enable frozen column feature

### ISSUE THREAD

**Issue by henryyan** [tonytomov/jqGrid#460]
This bug created in the year ago...

Please fix it, thanks.

http://www.trirand.com/blog/?page_id=393/bugs/the-columns-height-are-different-after-enable-frozen-column-feature/&value=Frozen&type=1&include=1&search=1

**Comment by tonytomov** [comment]
Not sure if this will be fixed easy

**Comment by tonytomov** [comment]
It is fixed now in the last version of Guriddo jqGrid

**Comment by tonytomov** [comment]
Do you use custom theme? Do you use Frozen columns? 
Please prepare WORKING example otherwise we can't help.
