### ISSUE TITLE
possible to submit old input value after select field change

### ISSUE THREAD

**Issue by rootsmith** [tonytomov/jqGrid#486]
In environments where the browser is overtaxed or a network operation may have serious lag, it is possible in the advanced search dialog for the user to submit an old input text element value after a select rule field change because the rendering of the new input text element has not completed yet.

For example, in the advanced search dialog, a user selects a different rule field and very quickly pastes a value into the input text box and hits 'Find'. Imagine that the building of the new data row element requires a remote call such as in a custom buildSelect. As a result, jqGrid posts an empty string even though the user entered in a value because it hadn't finished rendering the new element.

The root cause is that the processing of the ruleFieldSelect onChange event took a while, leaving the input data field for the old filter field on the screen. The user actually entered the data into the old input text element and hit submit before the new input text element had a chance to render. The call to empty() the old input field does not occur until the end of the event handler.

Note that this behaviour is extremely hard to replicate because most modern equipment and networks allow the whole thing to happen faster than human actions. I have only seen it in a hideously overburdened enterprise environment.

I have a patch on my forked jqGrid. I am just raising this issue to spark discussion and checking if I am indeed on to something. If I am not proven to be crazy I will do a pull request at some point.

Cheers

**Comment by tonytomov** [comment]
Hello,

Thanks for investigation. I think it is OK. Fixed.
Thanks
