### ISSUE TITLE
Grid with frozen columns leaks memory when sorting by any field

### ISSUE THREAD

**Issue by lukelalo** [tonytomov/jqGrid#487]
We are currently using jqGrid 4.4.5 and we have this memory leak. We've tried with jqGrid 4.5.2 and we've noted that with this version when you try to sort a grid with frozen columns, this feature is disabled.

Is there a way to sort rows with frozen columns on the grid?

Best regards and thanks for the good job
Pablo García

**Comment by tonytomov** [comment]
Hello,

Sorry, but with such kind of description is not possible to determine the problem
