### ISSUE TITLE
setRowData not applying colModel formatter

### ISSUE THREAD

**Issue by pmoriarity** [tonytomov/jqGrid#5]
Using 3.5 Beta.

As far as I can tell the setRowData method does not apply the colModel formatter.  

The work around is to call addRowData then delRowData to update a row of data with colModel formatting (I haven't tried this yet, but I'm assuming this will work).

Is there a technical reason setRowData does not apply the formatting?  Would be really nice if it did.  Thanks.

**Comment by ae6623** [comment]
楼上说的对。

  $.jgrid.formatter.date.reformatAfterEdit = true;
  $("#tblList").setRowData(rowid, changeValue);

It is ok！Thanks

**Comment by cdll** [comment]
@ae6623 u r welcomed~
