### ISSUE TITLE
When groupingSetup was called by groupingGroupBy, the groupText's array stack's value is incorrectly assigned/populated

### ISSUE THREAD

**Issue by fletchsod** [tonytomov/jqGrid#501]
I'm using jqGrid v4.5.2 and I noticed this strange bug.

![image](https://f.cloud.github.com/assets/4219733/977348/b5bff5da-06a1-11e3-94ed-2ce080e439d3.png)

The red circle showed missing total rows count for the 2nd grouped column.  Also the font text right next to the red circle is not font bold as well.

--- Original Scripts ---
                $('#' + jqgridSpreadsheetId).jqGrid('groupingGroupBy',
                    parmColumnName,
                    {
                        groupCollapse: true,
                        groupField: ['name'],
                        groupText: ["<span style='float:left;font-weight:bold;'>{0} - ({1})</span><span style='float:right;font-weight:bold;'> </span>"]
                    }
                );
-- End Original Scripts ---

The original script above showed the groupText object is using both 1) HTML/CSS scripts and 2) {0} and {1} argument values being assigned.  This showed up properly in the 1st column grouping but it is not being used in the 2nd column grouping (or more columns grouping)  Meaning it is not recursively used.

I narrowed down the problem to this jqGrid source code under "groupingSetup" function which produce this bug.

--snip--
$.jqgrid.extended({
   groupingSetup : function() {
      //Rest of source code not entered here.

      if(!grp.groupText[i]) {
         grp.groupText[i] = '{0}';
      }

      //Rest of source code not entered here.
   }, 
   groupingPrepare : function ....
   //Rest of source code not entered here.
});
--snip--

This source code above "grp.groupText[i] = '{0}' cause the column's name to show up in the 2nd (or more) grouped columns instead of the actual value from groupText's scripted value setting.

**Comment by tonytomov** [comment]
Hello,

I think you have set wrong options in groupingGroupBy. Either destroy grouping and set new one or set two groupFields as in your original grouping setup , you set one, but actually you have two

**Comment by fletchsod-developer** [comment]
You suck!
