### ISSUE TITLE
Toobar search on touch devices hardly working

### ISSUE THREAD

**Issue by mistic100** [tonytomov/jqGrid#503]
Hello
I'm using the toolbar search with ```searchOnEnter: false,```

On android devices, many times the results are not refreshed when an input is changed.

I found it's because the keypress event is not fired correctly with virtuals keyboards
https://github.com/tonytomov/jqGrid/blob/master/js/grid.custom.js#L524

replace this line by 
```javascript
$("input",thd).on('input', function(e){
```

and it works well

**Comment by tonytomov** [comment]
Can not find where to change this in current release

**Comment by mistic100** [comment]
https://github.com/tonytomov/jqGrid/blob/master/js/grid.filter.js#L1020
and line 1032

back in 2013 if you only listen to "key" events it didn't work on touch screens
I don't know if it's still the case now and I can't test
(if you even care)
