### ISSUE TITLE
issues when specifying rowNum as a string (4.5.2)

### ISSUE THREAD

**Issue by snobo** [tonytomov/jqGrid#509]
In version 4.5.2 (don't know about other 4.5.x versions), if you specify rowNum as a string (like "100" instead of 100), the specified number of records per page (rowNum) is not selected in the rowList drop-down. The grid still governs the specified number of records correctly, but no OPTION of SELECT.ui-pg-selbox is marked as selected, which leads to confusion whenever rowNum is not equal to rowList[0]. See screenshot for demo.

![jqgrid rownum](https://f.cloud.github.com/assets/1439713/1071947/46ad7d58-1483-11e3-96b3-82be4874bee6.png)

I know, it would be natural to dismiss it as a non-essential problem and simply suggest specifying rowNum as an integer. However, in all my applications I remember user settings (like number of records per page, current page, etc) in cookies. So, the problem is actually caused by the fact that getGridParam('rowNum') returns a string, not the integer (so "100" instead of 100), and this is what I store in the cookies and read/apply for the grid on next page visit. Before 4.5.x, it was never a problem because rowNum could be specified with a string with no side-effects. Not anymore.

**Comment by tonytomov** [comment]
This is fixed now using intNum internal function
