### ISSUE TITLE
Setting stype to select and searchoptions.dataUrl expects either postData or ajaxSelectOptions to be set

### ISSUE THREAD

**Issue by rootsmith** [tonytomov/jqGrid#512]
Scenario: You want to create a select pulldown built from a call to an URL for a particular field in the advanced search.

In the colModel for a particular row, if you set the stype to 'select' and provide a 'dataUrl' then the following code path will be followed in grid.common.js:
```javascript
if(options.dataUrl !== undefined) {
    var rowid = options.name ? String(options.id).substring(0, String(options.id).length - String(options.name).length - 1) : String(options.id),
    postData = options.postData || ajaxso.postData;
    ...
}
```
However, if you haven't set 'postData' in options nor any ajaxSelectOptions then a javascript error will happen as it tries to get the postData attribute on the undefined ajaxso object.

What if you have a dataUrl that returns your select options but doesn't take any url params or expects any post data? In this case you wouldn't set either postData or ajaxSelectOptions.

I'm thinking the code should read:

```javascript
postData = options.postData || (ajaxso && ajaxso.postData)
```

**Comment by tonytomov** [comment]
Hello,

Thanks for the tip. Actually it is too late, but the problem is fixed passing a ajaxSelectOptions or empty object in createEl function like this: ...p.ajaxSelectOptions || {}

Regards
