### ISSUE TITLE
Paging No Longer Working as Expected in jqGrid 4.5.2

### ISSUE THREAD

**Issue by BlogTheHaggis** [tonytomov/jqGrid#517]
Hi There,

I recently downloaded jqGrid 4.5.2 but noticed a few issues to do with paging which might be bugs.

Issue 1:
In version 4.1.2 you could obtain the current page by running this command:

$('#GridID').jqGrid('getGridParam', 'page');

Now this command only seems to return 1. Is this intentional? One work around is to detect which pager button has been clicked in the onPaging event and manually add/subtract to the pageNumber. Is this the right approach?

Issue 2:
When changing number of visible rows in the pager drop down list, the onPaging event now seems to fire before the rowNum value is updated. Eg. if I changed the number of rows from 20 to 10 via the UI in the onPaging event rowNum would still be 20.

Any information you could provide on these 2 issues would be greatly appreciated.

Regards,
-Duncan

**Comment by tonytomov** [comment]
Hello,

Not sure about the first problem without test case.
I have added second parameter in onPaging event (the element when it is called) so you can 
```
onPaging : function( which, thus) {
    if(which === 'records') {
        var new_rowNum = thus.value;   // or $(thus).val();
        // do what you want with new_rowNum
    }
}
```

**Comment by BlogTheHaggis** [comment]
Hi there,

Wow I had forgotten I posted this (I don't even work for that company anymore)

Thanks for following this up.

Regards,
-Duncan
