### ISSUE TITLE
searchOnEnter searches for wrong value due to wrong event order

### ISSUE THREAD

**Issue by lir-ht** [tonytomov/jqGrid#542]
The "simple search" dialog fails to correctly update the filter that is applied when using the keyboard command (with searchOnEnter enabled).

As I understand it, the contents of the textbox are read when the change event is triggered (when the textbox loses focus) and the resulting filter is applied in the button's click event. But with the keyboard command, the events arrive in the wrong order, so when the click event occurs the filter still has the value from the *last* time the textbox lost focus.

I have fixed it by delaying the click event until the next turn of the event loop, so that the change event always arrives first, but I'm not sure if that's the best way to do it. Triggering a change of focus and simulating a click event seems like a bit of a hack in the first place; wouldn't it be better to have the underlying functionality in some common function that can be called both from onchange/onclick and onkeypress?

To reproduce:
1. With searchOnEnter enabled, type in "a" and press enter.
2. Repeat for "b".
3. Repeat for "c".

Expected results:
The table will show results for "a", then for "b", then for "c".

Actual results:
The table shows results for "" (the empty string), then "a", then "b". I.e., it always uses the *previous* value, not the one that was actually specified.

The problem occurs with jqGrid 4.4.0 on Firefox 25 and Chromium 30.0.1599.101. I haven't tested other browsers. (I think it applies to jqGrid 4.4.5 as well, if I remember correctly.)

**Comment by tonytomov** [comment]
Hello, 

This is fixed just with removing the focus()

Regards
