### ISSUE TITLE
jqGrid  4.5.4: setCell bypass the formatter of date type

### ISSUE THREAD

**Issue by dreamershl** [tonytomov/jqGrid#546]
When using setCell to set the date value, the formatter is bypassed by the parameter "edit"

setCell : function(rowid,colname,nData,cssp,attrp, forceupd) {
...
v = $t.formatter(rowid, nData, pos,ind,'edit');

in the formatter.date if will just return the value if the act is "edit'
if(!op.reformatAfterEdit && act === 'edit'){

**Comment by tonytomov** [comment]
Set the reformatAfterEdit to true.
