### ISSUE TITLE
Summary type sum doesnt work and incorrect height

### ISSUE THREAD

**Issue by hjunior81** [tonytomov/jqGrid#549]
I have a grid with Turkish language injected, scroll and gridview enabled. There are two columns using formatter:currency and summaryType:sum and there is NO GROUP. I set footerRow = true. The footer row displayed between data and toolbar
I have two problems:
1. I set the height using setHeight method. But the height is incorrect about 22px. So i think if the footerrow is enabled and showed it must substract more 22 px.
2. The footer row doesnt contain the SUMs. They are not calculated.

Whats wrong with it?

**Comment by tonytomov** [comment]
The grid height does not include footer row, pager, grid headers, grid caption. We calculate the height only on the rows. So if you have footer row you will need to set height - 22.
About the second problem - without test case I can not help.
