### ISSUE TITLE
additional parameter in colModel for search index

### ISSUE THREAD

**Issue by pnmpn25** [tonytomov/jqGrid#556]
I have a case where I would like to search by a different name than I sort by for a column. Currently the index/name property is used to specify the search and sort parameter values. 

Can we add another property, searchindex, which overrides index/name for the search?

Example for filtertoolbar

Line 4006 -- jquery.jqGrid.js
          nm = this.index || this.name;

to 
          nm = this.searchindex || this.index || this.name;

**Comment by tonytomov** [comment]
Hello,

I think that more common solution like dynamically change this with a function is a good start. I close this and add it to our todo list. Adding more and more parameters is highly not recommended.

regards
