### ISSUE TITLE
When reloading a jqgrid we should be able to keep selected rows checked

### ISSUE THREAD

**Issue by pauloortins** [tonytomov/jqGrid#561]
When reloading a jqgrid we should be able to keep selected rows checked instead to clear the checkboxes

**Comment by tonytomov** [comment]
Hello,

This is by default. When a reloading is made we clear the current data and load a fresh data from the server. It is unknown if this data is the same as previous.

That is the reason that you can do a custom function which will save the selected rows and later after the fresh data is loaded you can select them using setSelection (if they are present)

Regards
