### ISSUE TITLE
date formatter can't reformat after edit - design problem

### ISSUE THREAD

**Issue by bouks** [tonytomov/jqGrid#568]
Problem:

The option reformatAfterEdit is hard set to false by default in grid.locale-xx.js although it is not an i18n function.

It can't be overriden in colmodel's formatoptions like 'srcformat' or 'newformat'.

Solutions:

Maybe set it to true by default or set possible change (or overriding) it in colmodel and/or define it in another place.

**Comment by tonytomov** [comment]
Hello,

It is in i18n function under the section formatter.
You can do this after the language file is loaded (using the new locale in 4.8)
```
$.extend(true, $.jgrid.regional['fr'], { formatter: { date : { reformatAfterEdit : true}}});
```

Kind Regards
