### ISSUE TITLE
Numerous Detached Nodes after Grid Unload

### ISSUE THREAD

**Issue by Rapida11428** [tonytomov/jqGrid#576]
Steps to reproduce:
1. Create a jqgrid
2. Call GridDestory or GridUnload on the grid
Results: There are a large number of detached DOM nodes continuing to take up browser memory.
Expected: I would think that all the DOM nodes should in a state where the garbage collector can handle them.
This can be seen on this demo site: http://www.ok-soft-gmbh.com/jqGrid/RecreateGrid.htm

Steps:
Load the page and click Create large grid.
![capture](https://f.cloud.github.com/assets/6751736/2234680/6a8c76b2-9b3c-11e3-9286-09a00731fa8e.PNG)
This causes $("#list").jqGrid('GridUnload'); to be called. 
You can then use Chrome's profiler to take a heap snapshot to view the detached DOM nodes.
![capture](https://f.cloud.github.com/assets/6751736/2234670/3b63b562-9b3c-11e3-8fd2-cc92a15f89fc.PNG)

Associated stackoverflow question: http://stackoverflow.com/q/22021026/146566

**Comment by tonytomov** [comment]
Hello,

This bug is fixed in 4.8. Please use the new method $.jgrid.gridUnload('jqGridId'); See release notes here: http://guriddo.net/?p=123585
