### ISSUE TITLE
Multisort not maintaining column order

### ISSUE THREAD

**Issue by azghanvi** [tonytomov/jqGrid#583]
http://www.trirand.com/blog/phpjqgrid/examples/sorting/multiple_sorting/default.php

Referring above example, 
i) first remove all sorts.
ii) Sort with customerid (asc)
iii) Sort with orderid

Expected result was to make sort like 'customerid asc, orderid'
But, the result is 'orderid asc, customerid'

Tony, Please tag it for next build.

**Comment by tonytomov** [comment]
Hello,

I will try to implement this in the next release 4.8.1

**Comment by tiritas** [comment]
Any progress on this? I'm using version 4.8.2 and the column order is still left to right, rather than being based on the order the column headers were clicked.

**Comment by tonytomov** [comment]
Hello,
I hope it will be available in the next release.

Kind Regards

**Comment by tonytomov** [comment]
Hello,

I have added this feature : https://github.com/tonytomov/jqGrid/commit/eb8cb6a38cabcabd03ca78ebaf7d1832c698820b

You can download the latest build from GitHub.
Please let us know if this is working as expected, so that the requierment will be closed.

Thank you

**Comment by tiritas** [comment]
I downloaded the latest version, but the combined jquery.jqgrid.js does not contain the latest changes, even though the grid.base.js file does. Is it possible to provide an updated combined file so that we can test?

**Comment by tonytomov** [comment]
ined version.
I have downloaded the last build and everything is here.
When open the zip look in the js folder - here is the combined version - jquery.jqGrid.js
js folder contain minified folder with minified version

**Comment by tiritas** [comment]
I just re-downloaded and the combined file (jquery.jqGrid.js) does contain the sort changes. I noticed that the date in the header is different from the one I downloaded yesterday after your post (5/29 vs 5/30). Multi-column sorting with updated code works exactly as expected!

Thanks!

**Comment by tonytomov** [comment]
Thanks for the feedback. Glad to hear that this work as expected. I will close the requirement.

Kind Regards,
Tony
