### ISSUE TITLE
Updating values of Custom elements on navigation between records in editing form

### ISSUE THREAD

**Issue by smartcorestudio** [tonytomov/jqGrid#594]
I've created a simple custom elemrnt (input type="number")

```
function number (value, options) {
    return $('<input type="number" step="0.5" value="'+value+'"/>');
};

function myvalue(elem, operation, value) {
    if(operation === 'get') {
       return $(elem).val();
    } else if(operation === 'set') {
       $('input',elem).val(value);
    }
};
```

After setting "recreateForm: true" it started to update values on form opening. But it doesn't change values of the custom elements when I'm navigating between the records in the form

**Comment by tonytomov** [comment]
I can not reproduce this problem. can you please post a full grid setup and simple test data

**Comment by BogMil** [comment]
All works if you reopen edit dialog every time for different row. But when navigating, it does not change value.
https://jqgriddemo.000webhostapp.com/

**Comment by tonytomov** [comment]
Actually the problem s in the definition of the function myvalue. It should look like this

````js
function myvalue(elem, operation, value) {
    if(operation === 'get') {
       return $(elem).val();
    } else if(operation === 'set') {
       $(elem).val(value);
    }
};
````

i.e replace the element 
````
$('input',elem).val(value);
````
with
````
$(elem).val(value);
````

Actually the passed element is the same input created and there is no input in the input.
This problem has been seen into the docs for which we apologizes. It is fixed now.
http://www.guriddo.net/documentation/guriddo/javascript/user-guide/editing/#edittype

Kind Regards,
Tony
