### ISSUE TITLE
input in toppager not displayed correctly in chrome/opera

### ISSUE THREAD

**Issue by aeschbacher** [tonytomov/jqGrid#595]
The 'input class="ui-pg-input"' is correctly displayed in the bottom pager, but not in a top pager ( toppager: true ) when using Chrome or Opera.

Works as expected with Firefox.

Current workaround is to add following css (after ui.jqgrid.css is loaded):

.ui-jqgrid .ui-pg-input { height:15px;}

**Comment by tonytomov** [comment]
Fixed in 4.8
