### ISSUE TITLE
Cell height inconsistent with frozen columns

### ISSUE THREAD

**Issue by mr-unicoder** [tonytomov/jqGrid#599]
I've a grid with columns [Id, Code, Details] and some other columns
When i freeze the first two columns (Id, Code) and Details column data is multi-line string then i select one of these rows, The selected row class is inconsistent on the both sides of frozen columns

![jqgrid issue](https://cloud.githubusercontent.com/assets/6755384/2847006/567e2b96-d0a9-11e3-8878-4a739a2747f1.png)

**Comment by tonytomov** [comment]
Hello,

This is well  known problem. It is difficult to apply a fix to this...

**Comment by tonytomov** [comment]
Hello,

This is already fixed in the last reales of Guriddo jqGrid
