### ISSUE TITLE
Post entire grid to controller

### ISSUE THREAD

**Issue by praveenlobo7** [tonytomov/jqGrid#600]
We have a jqgrid which contains 2 checkboxes. I want to post the entire grid data to my controller. I use the following command.

$("#circleActorsTable").jqGrid('getGridParam', 'data');
If Loadonce=true, this returns the entire grid data. But if the checkboxes are checked, updated data is not shown.

If Loadonce=false, then null data is returned.

Please help!!

**Comment by tonytomov** [comment]
If loadonce is true you have all the data that comes from the server. If it is false it is only a portion set in rowNum. So in order to solve the problem you will need to use loadonce set to true
