### ISSUE TITLE
Form data not updated after selecting different row

### ISSUE THREAD

**Issue by Mensae** [tonytomov/jqGrid#604]
I just upgraded from version 4.5.2 to 4.6.0 as I need a pivot functionality.

Strange thing that is happening now is that when I select a row and hit either edit/view/add the form shows the correct data. After closing the form and choosing another row and hit either edit/view/add the form shows the data from the previously selected row.
I broke down the issue to be related to the jqModal option. If set to 'true' the issue goes away.

I had a look at http://stackoverflow.com/questions/413569 but the suggested solution does not help

**Comment by tonytomov** [comment]
Sorry - Demo is not provided and I can not use your trick
