### ISSUE TITLE
jqgrid 4.6.0 frozen columns problems on safari

### ISSUE THREAD

**Issue by banch0140** [tonytomov/jqGrid#605]
When setting frozen columns(jqgrid 4.6.0) on safari, the float forzen div is shortter.
![snap1](https://cloud.githubusercontent.com/assets/1267869/2992855/16e41284-dc9d-11e3-92dd-453ee0136293.jpg)

**Comment by tonytomov** [comment]
Hello,

Which version of Safai and which OS?
