### ISSUE TITLE
Problems with nested tables

### ISSUE THREAD

**Issue by roadrunner1801** [tonytomov/jqGrid#623]
Hi, 
I am using jqGrid 4.6.0 and a table as content for a cell leads to interresting errors for e.g. input/select elements because  

jquery.jqGrid,src.js:9964: cc = $("td:eq("+iCol+")",$t.rows[iRow]);

provides no longer a valid selector for the cell with the input element.
I propose to exchange it with one of the following lines:

cc = $("> td:eq("+iCol+")",$t.rows[iRow]);
cc = $($t.rows[iRow]).children("td:eq("+iCol+")");

Both lines are working for me.
Any other ideas ?

Thanks, Stef

**Comment by tonytomov** [comment]
Hello,

I suppose that the same should be do in other places. Can you please send me a simple test data and and setup so that I can look better on this. It is difficult to reproduce such a problem from me.

Thank you

**Comment by tonytomov** [comment]
Hello,

I have fixed this here: https://github.com/tonytomov/jqGrid/commit/9dbcd67ace8ebdefbd76bafb28497d9976bfbb96 .
