### ISSUE TITLE
Scroll position after page refresh

### ISSUE THREAD

**Issue by vitman** [tonytomov/jqGrid#625]
On latest jqgrid, if you will scroll grid to the end, then refresh page, scroll will left down, as shown on the screen
![screenshot-dmp1 2014-08-19 14-11-51](https://cloud.githubusercontent.com/assets/2102773/3965099/163e1dee-2792-11e4-844c-dd45c0d97156.png)

**Comment by tonytomov** [comment]
Can you please post a test case on this. Which browser on which OS is this?

**Comment by vitman** [comment]
This screen was made 8 months ago. Unfortunately I have not opportunity for now to try reproduce it again or make test case for you. System was Linux Ubuntu, Firefox.

**Comment by tonytomov** [comment]
Hello,

Thanks for feedback.  I will close the problem. If you have time or a case to reproduce it again, please reopen it.

Thank you.

Kind Regards
