### ISSUE TITLE
problem with scroll:1 or scroll:true and multiselect and localStorage selected rows :)

### ISSUE THREAD

**Issue by istiti** [tonytomov/jqGrid#642]
Hi, when the option scroll:true or scroll:1 is enabled and when I scroll into my grid I realize the loadComplete or gridComplete aren't called always.

So, what 'im trying is: save in localStorage all the ID the users select thereby when I scroll into the grid I check in loadcomplete or gridcomplete if the rows's id actually shown is in localstorage and I setSelection.... I realize loadcomplete aren't called always so sometimes my rows aren't selected.... 

How can I fix this problem ? Other way than using jquery scroll() method on bdiv :s

Thanks

**Comment by tonytomov** [comment]
Hello,

Couild you please prepare a simple demo which shows the problem?
When we speak about the virtual scrolling it is very difficult to determine the problem without test case.

Thank you

**Comment by tonytomov** [comment]
Hello,

I think that this problem is similar to this one: https://github.com/tonytomov/jqGrid/issues/691
It is partially fixed.
