### ISSUE TITLE
Subgrid and setGridHeight to 'auto' issue in IE 9

### ISSUE THREAD

**Issue by jaysachaniya** [tonytomov/jqGrid#651]
There is an issue with IE 9 web browser when you have a subgrid and use setGridHeight and setting height to 'auto'. 
To reproduce it
- go to http://jsfiddle.net/54d1z5kq/1/ using Internet Explorer 9
- hover over rows

Observe that grid height increases unpredictably as you hover over the row.

**Comment by tonytomov** [comment]
Hello,

Hello - I see that you use a old version of jqGrid. Can you please use the latest 4.8 and tell us if the bug is present. Sorry for this, but it is difficult for us to get true working IE9.

Regards,
