### ISSUE TITLE
After vertical and horizontal scroll, the column headers disappears in UI for IE10

### ISSUE THREAD

**Issue by raptorsteam** [tonytomov/jqGrid#652]
Go to http://jqgrid.com/jqgrid/demos/jqgrid-standalone/working-with-row-data 
(when we tested the above grid demo url and found out the version is : 4.5.2 )
Increase the column width so that you can scroll horizontally.
Steps : 
1) Scroll Vertically down
2) Scroll horizontally.
3) Scroll vertically, and see that header column names will not visible.

Happens in IE10 . 
When we once again scroll, the names appear back.

Pls find the sequence of screen shots.
![1](https://cloud.githubusercontent.com/assets/9606863/4951127/8adab422-6663-11e4-8dab-8d704d002cc2.gif)
![2](https://cloud.githubusercontent.com/assets/9606863/4951128/8affc514-6663-11e4-918d-12cef88e7dd2.gif)
![3](https://cloud.githubusercontent.com/assets/9606863/4951129/8b0677b0-6663-11e4-904f-ebce8af95aae.gif)
![4](https://cloud.githubusercontent.com/assets/9606863/4951130/8b122772-6663-11e4-819e-4c69b739d5ed.gif)

**Comment by tonytomov** [comment]
Please ask the author of the demo of this problem
