### ISSUE TITLE
When multiselect is true and multi select key is set, I am unable to select text in the grid.

### ISSUE THREAD

**Issue by codymullins** [tonytomov/jqGrid#672]
I am unable to select any text on the grid when multi-select is true and I have a multi-select key set.

**Comment by tonytomov** [comment]
Hello,

Could you please clarify what you mean with select text in grid?
Thank you

**Comment by codymullins** [comment]
I cannot highlight the text; for instance if I were to highlight the text to copy it and paste it elsewhere.

**Comment by tonytomov** [comment]
Thanks for the replay. I'm going to check this.

Regards

**Comment by tonytomov** [comment]
Hello,

This is disabled by default with this code in the grid:

```
		if(ts.p.multikey){
			if( $.jgrid.msie) {
				$(grid.bDiv).bind("selectstart",function(){return false;});
			} else {
				$(grid.bDiv).bind("mousedown",function(){return false;});
			}
		}
```

To do what you want you will need to unbind theis event like this.
```
$("#jqGrid").jqGrid{
...
});

var grid = $("#jqGrid")[0];
$(grid.grid.bDiv).unbind("mousedown");
```

You will need to use selectstart whe the browser is IE.

Regards
