### ISSUE TITLE
Filtering Issue

### ISSUE THREAD

**Issue by KyleKolpek** [tonytomov/jqGrid#674]
newformat is applied in parsedate() even when the date has already been converted. This breaks the filtering of dates when newformat differs from srcformat.

To recreate:
Input is 2014-09-08;
datatype = local;  // I assume this is a/the culprit
srcformat = 'Y-m-d';
newformat = 'n/j/Y';
Enable filter toolbar.

The grid shows 9/8/2014, but won't filter correctly because when filtering jqGrid is trying to apply 'Y-m-d' to 9/8/2014.)

**Comment by tonytomov** [comment]
Hello,
Thanks for this. As you mentioned the culprit is the local data. The date is stored in srcformat in data array and should be converted back if the search apply. I will look into this issue and will let you know

Regards
Tony

**Comment by tonytomov** [comment]
@KyleKolpek  
Which format do you use when a search apply :  2014-09-08 or 9/8/2014?

**Comment by tonytomov** [comment]
Hello,
I have fixed the problem. You can view the commit here https://github.com/tonytomov/jqGrid/commit/e0d9ed010d86a8df75f0c6a7805180928124c2bc
I have prepared a demo for this purpose. You can look at it here: http://www.guriddo.net/demo/guriddojs/searching/toolbar/index.html

Please let me know if this fixes the problem for you. You can download the fix from here.

Kind Regards
Tony

**Comment by KyleKolpek** [comment]
Thanks for the fast response @tonytomov.

To answer your first question I was trying to use the 9/8/2014 format. Looking at your demo it seems to work. I'll check out the newer version tomorrow and see if it solves our problem.

**Comment by tonytomov** [comment]
Fixed.
