### ISSUE TITLE
editRow does not save the real state of the cells when cells are objects

### ISSUE THREAD

**Issue by larjohn** [tonytomov/jqGrid#677]
If you use the following:
1. custom inline editing form
2. custom object value coming from the inline editing form
3. custom formatter to display the object as a string

then, while you can make it to save the row correctly, if you click edit and then restore, the formatted string replaces the object and makes it a string completely loosing the previous state.

This is due to the editRow function:

Don't have the time for a pull request right now, just dumping the code here for the time being:
I used the following code to fix it (line 9329 and following):

                             try {
                                var $row_obj =  $($t).jqGrid('getLocalRow',rowid)[cm[i].name];
                                if(typeof($row_obj)=="object"){
                                    tmp = $row_obj;
                                }
                                else{
                                    tmp = $.unformat.call($t,this,{rowId:rowid, colModel:cm[i]},i);
                                }

                            } catch (_) {
                                tmp =  ( cm[i].edittype && cm[i].edittype === 'textarea' ) ? $(this).text() : $(this).html();
                            }

**Comment by tonytomov** [comment]
Hello,

Thanks for the tip. I think you will need to define a custom unformat function in col model.
This will grand you the result. It is recommended to define custom unformter if a custom formatter is defined.
Please let me know if this case you have resolved the problem.
Below is a link in our defo for a custom unformatter:
http://www.guriddo.net/demo/guriddojs/functionality/formatters_custom/index.html

Kind Regards
Tony

**Comment by larjohn** [comment]
A careful fabrication of formatter and unformatter has resolved the problem for me. Thanks!
