### ISSUE TITLE
unable to set property 'innerHTML' of undefined error in ie8/9 + 4.7.1

### ISSUE THREAD

**Issue by jackz3** [tonytomov/jqGrid#679]
Use 4.7.1,when showing data in ie8/9,I got "unable to set property 'innerHTML' of undefined or null" error.
The problem code is
ts.firstElementChild.innerHTML += rowData.join('');

downgrade to 4.6。no problem

**Comment by tonytomov** [comment]
Hello,

Thank you for reporting. This is fixed and will be available in the new release soon: https://github.com/tonytomov/jqGrid/commit/679f4a82606f9908632f42c76102edc849062b51
