### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by jlovejoy** [tonytomov/jqGrid#683]
The headers for versions 4.7.0 and earlier say: "Dual licensed under the MIT and GPL licenses"
Do you actually mean it is disjunctively licensed under a choice of either MIT or GPL (v2 or later)?

A copy of each license is also missing from the source tree, as far as I can tell.

Thanks for clarifying,
J

**Comment by Niggler** [comment]
See https://github.com/tonytomov/jqGrid/issues/646

Basically, 4.7.0 was MIT/GPL and you could use it under either license.

After that, it was changed to use a proprietary license.

There are some prominent forks including https://github.com/free-jqgrid/jqGrid and https://github.com/openpsa/jsgrid that should be used in lieu of this project.  The license situation is currently very murky and it's best to stick with a true open source solution
