### ISSUE TITLE
Keyboard Support on Column Headers

### ISSUE THREAD

**Issue by citi-raulfernandez** [tonytomov/jqGrid#684]
Is it possible to include keyboard support on the actionable grid's column headers? Add a tabindex=0 so you can tab through it, press ENTER/SPACE to execute the action (usually sorting).

**Comment by tonytomov** [comment]
In principle this is possible. I have not tested this, but the label can be set as html (I mena (a href tag) and thus we can attach a event on this. I will try to play with this and will let you know.

Kind Regards

**Comment by tonytomov** [comment]
Hello,

I just implemented the idea and it work for me. The only exception is that the sort work only and ENTER and NOT on SPACE. Here is a code that I used to test:
`
                colModel: [
                    { label: '<a href="" tabindex=0>OrderID</a>', name: 'OrderID', key: true, width: 75 },
                    { label: '<a href="" tabindex=0>Customer ID</a>', name: 'CustomerID', width: 150 },
                    { label: '<a href="" tabindex=0>Order Date</a>', name: 'OrderDate', width: 150 },
                    { label: '<a href="" tabindex=0>Freight</a>', name: 'Freight', width: 150 },
                    { label:'<a href="" tabindex=0>Ship Name</a>', name: 'ShipName', width: 150 }
                ],
`

Please let me know if you have difficulties to realize this.

Kind Regards

**Comment by tonytomov** [comment]
I will close this
