### ISSUE TITLE
Using toolbar searching and Grid Search

### ISSUE THREAD

**Issue by haryl** [tonytomov/jqGrid#686]
I'm using the grid with toolbar search and allow to search with searchGrid function.
But those two search/filter possibilities are a little confusing.

If I search in searchGrid and will enhance those search by quickly define another search in the toolbar only the search in the toolbar gets recognized/processed. The query in the searchGrid is completely ignored.
On the other hand, if I first search in the toolbar, the searchGrid form gets initialized with those search query so the user can enhance/delete the query.

Suggestion:
It would be great if a searchGrid was already done, this will also get recognized and will get extend the query send to the backend using the toolbar search.

``` javascript
jQuery("#mygrid").jqGrid('searchGrid', {
            multipleSearch:true,
            multipleGroup:true,
            showQuery:false,
            jqModal: true,
            modal: false,
            stringResult: true,
            closeOnEscape: true,
            recreateFilter: true,
            caption:"Filterfunktion",
            closeAfterSearch:true,
            closeAfterReset: true,
            sopt:["eq","ne","lt","le","gt","ge","bw","bn","ew","en","cn","nc","nu","nn"]
            });
```

**Comment by tonytomov** [comment]
Hello,

At first look I see the "problem" in the definition of the searchGrid - especially the options multipleSearch:true, and multipleGroup:true, - this way you can define a very complex search conditions (with many nested and and or on the same field) which can not be converted so simple in the toolBar serarch. That is the reason that the other conversion work, while it is very simple.

**Comment by OlegKi** [comment]
@haryl I recommend you to look at [the old answer](http://stackoverflow.com/a/6884755/315935). You can implement your requirements in the simplest cases.

On the other side the old function `refreshSerchingToolbar` from the answer don't support `searchOperators` option of `filterToolbar`. Moreover you should clear understand, that **one can't convert more complex queries from Advanced Searching dialog in the searching toolbar**. The simplest Searching dialog with OR operation can't be converted to the searching toolbar. So I full agree with Tony in the point.

**Comment by haryl** [comment]
Many thanks for reply!

Since the toolbar properties are AND connected to other operators, it would be an option to extends the existing searchGrid filter by adding another group with "all" and add toolbar filter as.

E.g 
[groupOp:AND, groups:[
[groupOp:AND, groups:[], 
rules:[[data:123123, field:mobilePhone, op:cn]]]], 
rules:[
[data:abc, field:firstName, op:cn], 
[data:123, field:name, op:cn]]
]

add a new group with rules like
rules:[
[data:toolbarfilter, field:middleName, op:cn] ]
If the middleName should get into a complex query the customer has either way to open the searchGrid....

**Comment by tonytomov** [comment]
Hello,

Just to note that toolbar properties can be a OR described - see **groupOp** option in filterToolbar method.

Regards
