### ISSUE TITLE
Find a bug about paging

### ISSUE THREAD

**Issue by explorerit** [tonytomov/jqGrid#687]
When page button is disabled, clicking will load the event . This will change the value of 'ts.p.selrow ' and 'ts.p.selarrrow ', but rows selected are still showed cause getting the value of selrow or selarrrow  is failed.
A sentence should be added as shown following.

![1](https://cloud.githubusercontent.com/assets/8748522/6633955/e12b51d4-c98b-11e4-8e51-88bdce65b818.png)

**Comment by tonytomov** [comment]
Thanks.
I will check this.

**Comment by tonytomov** [comment]
Can yo please post a simple setup with data so that I can look at this in a better way?
Thank you

**Comment by explorerit** [comment]
http://jsfiddle.net/explorerit/pwbdj3jt/

You can click the disabled first page or previous page, then get row selected, it will get none.

**Comment by tonytomov** [comment]
Hoell,

Thank you very much for the test case.
Sorry that I do not understand fully the problem you describe. You use a old jqGrid version 4.5.
The problem is already fixed and you can use the fresh 4.8.

Thanks again.

Best Regards,
Tony
