### ISSUE TITLE
Paginator not visible in pair with scroll pagination

### ISSUE THREAD

**Issue by AuthorProxy** [tonytomov/jqGrid#689]
Version of jqGrid: Guriddo jqGrid JS 4.7.0 (2014-12-08) Main jqGrid options:

```
mtype: 'get',
datatype: 'json',
page: 1,
scroll: 1,
rowNum: 50,
rowList: [10, 20, 50],
width: 780,
height: 250,
hidegrid: false,
multiSort: false,
autowidth: true,
multiselect: true,
ignoreCase: true,
shrinkToFit: true,
rownumbers: true,
rownumWidth: 25,
viewrecords: true,
gridview: true,
pager: '#jqGridPager',
viewsortcols: [false, 'horizontal', true]
```

http://stackoverflow.com/questions/27966057/jqgrid-paginator-not-visible-in-scroll-pagination

**Comment by tonytomov** [comment]
Hello,

This is by design. When scroll is on - pager buttons are disabled due to logic.
In the upcomming 4.8 the page info can be visible via setting scrollPopUp parameter

Regards

**Comment by AuthorProxy** [comment]
Just ask cause on previous versions i could enable both as I remember.. It's very comfortable for fast pagination.

**Comment by tonytomov** [comment]
You should either use pagination or virtual scrolling, but not both. These features are not enabled from the creation of the virtual scrolling
