### ISSUE TITLE
Refreshing jqGrid don't save current page pozition with infinitive scroll enabled

### ISSUE THREAD

**Issue by AuthorProxy** [tonytomov/jqGrid#690]
Example from http://www.trirand.net/demo/javascript/jqgrid/loading_data/scrollbar/index.html
Versions of Guriddo jqGrid JS: 4.7.0 and 4.7.1

```
(function ($) {
  'use strict';
  $(function () {
    $('#jqGrid').jqGrid({
      url: 'http://trirand.com/blog/phpjqgrid/examples/jsonp/getjsonp.php?callback=?&qwery=longorders',
      mtype: 'GET',
      datatype: 'json',
      page: 1,
      colNames: ['Order ID', 'Customer ID', 'Order Date', 'Freight', 'Ship Name'],
      colModel: [{
        name: 'OrderID',
        key: true,
        width: 75
      }, {
        name: 'CustomerID',
        width: 150
      }, {
        name: 'OrderDate',
        width: 150
      }, {
        name: 'Freight',
        width: 150
      }, {
        name: 'ShipName',
        width: 150
      }],
      width: 750,
      height: 250,
      rowNum: 20,
      scroll: 1, // set the scroll property to 1 to enable paging with scrollbar - virtual loading of records
      emptyrecords: 'Scroll to bottom to retrieve new page', // the message will be displayed at the bottom
      pager: '#jqGridPager'
    });
  });
})(jQuery);
```

When I call 2 times:
```
$('#jqGrid').trigger('reloadGrid', {
    page: 3
});
```

[first time request:](http://trirand.com/blog/phpjqgrid/examples/jsonp/getjsonp.php?callback=jQuery111103447585825342685_1426667139022&qwery=longorders&_search=false&nd=1426667144479&rows=20&page=3&sidx=&sord=asc&_=1426667139024) the page param is 3 as expected.

[second time request:](http://trirand.com/blog/phpjqgrid/examples/jsonp/getjsonp.php?callback=jQuery111103447585825342685_1426667139022&qwery=longorders&_search=false&nd=1426667149225&rows=20&page=1&sidx=&sord=asc&_=1426667139025) the page param is 1 !?

The same problems I see at refresh button with refreshstate: 'current', It doesn't work at all. (SO question [here](http://stackoverflow.com/questions/29120935/refreshing-jqgrid-dont-save-current-page-pozition-with-infinitive-scroll-enable)).

**Comment by tonytomov** [comment]
Hello,

Not sure, but you should call trigger('reloadGrid) with delay one after other. If you call it immediate one after other maybe this will be normal (not tested from me)

**Comment by AuthorProxy** [comment]
No matter, make i delay or not, It's one case, other is refresh button, but i don't describe it, cause i think It is the same bug

**Comment by tonytomov** [comment]
Hello,

Will check, but the version you point is old 4.6 and these demos are no valid.
The only that I think is that after first call of reloading the response is not correct since of this code in  when a reload is on
```
			if (opts && opts.page) {
				var page = opts.page;
				if (page > ts.p.lastpage) { page = ts.p.lastpage; }
				if (page < 1) { page = 1; }
				ts.p.page = page;
...
```

**Comment by AuthorProxy** [comment]
I try on the local machine with 4.7.0 and 4.7.1, just point that setup is the same as on the demo page

**Comment by tonytomov** [comment]
Hello,

I confirm this bug. We will try to investigate it deeper and fix it.

Kind Regards,

**Comment by tonytomov** [comment]
Fixed in development. Need more testing.
