### ISSUE TITLE
Can't call jqGrid('GridUnload') or jqGrid('gridUnload') in master version

### ISSUE THREAD

**Issue by iamcacy** [tonytomov/jqGrid#693]
hello, function jqGrid('GridUnload') works well in version 4.7.0,but  I get an error message when It's updated to master version today. Is it a bug or something?

**Comment by tonytomov** [comment]
Hello,

These functions (griddestroy too ) are buggy and are no more supported. There will be upgrade notes when the new version is out. Just for your the new method is $.jgrid.gridUnload('jqGridID')
and $.jgrid.gridDestroy('jqGridID'), where the jqGridId is the id of the grid.
