### ISSUE TITLE
Bad link to map file

### ISSUE THREAD

**Issue by danjudex** [tonytomov/jqGrid#694]
Minified version have bad link to map file

**Comment by tonytomov** [comment]
Hello,

Which map file is used. Can you please fork the project and use the grunt to build the map. 
Optionally you can get the map from js/minified directory of the project.

It worked for me fine.

Please let me know if this fixes the problem.
Thank you.

Kind Regards,

**Comment by tonytomov** [comment]
Any chance to answer my question?

**Comment by tonytomov** [comment]
Hello,

This will be closed
