### ISSUE TITLE
Scroll bug with big rows

### ISSUE THREAD

**Issue by AuthorProxy** [tonytomov/jqGrid#695]
Version of Guriddo jqGrid JS: 4.7.0.

    (function ($) {
      'use strict';
      $(function () {
        $('#jqGrid').jqGrid({
          url: some_url,
          mtype: 'GET',
          datatype: 'json',
          colModel: [{
            label: 'id',
            name: 'id',
            hidden: false,
            key: true
          },
          {
            label: 'Примечание',
            index: 'note',
            name: 'note'
          },
          {
            label: 'Логин',
            index: 'userLogin',
            name: 'userLogin',
            hidden: true,
            edittype: 'text'
          }],
          scroll: 1,
          height: 500,
          width: 500,
          rowNum: 50,
          rownumbers: true,
          pager: '#jqGridPager',
          prmNames: {
            nd: null,
            search: null,
            page: 'page',
            rows: 'pageSize',
            sort: 'sortKey',
            order: 'sortOrder',
            totalrows: 'totalQty'
          },
          jsonReader: {
            root: 'data.entries',
            // page: 'data.pager.page',
            total: 'data.pager.totalPages',
            records: 'data.pager.totalQty'
          }
        });
      });
    })(jQuery);

When jqGrid meet the long text fields (that forth grid to render rows with big height) with enabled `scroll: 1` jqGrid became to glitch and don't work. Attach [screencast](http://screencast.com/t/LN85iiMM) to show the problem. ([SO question is here](http://stackoverflow.com/questions/29162609/jqgrid-scroll-bug-with-big-rows)).

**Comment by tonytomov** [comment]
Hello,

This is a a well known problem.
The module need to be rewritten, but this is not a trivial task.

Just want to know if the previou probms with multiselecty and triggerig with certain page are resolved.
If they are resolved, please lclose them if not let me know to provide for you a test cases 

Thank you.

Kind Regards

**Comment by tonytomov** [comment]
Duplicate: https://github.com/tonytomov/jqGrid/issues/175
