### ISSUE TITLE
GridUnload missing from 4.8?

### ISSUE THREAD

**Issue by dizzy0ny** [tonytomov/jqGrid#696]
Getting 'no such method defined' with the latest, but if i go back to an older version, it works fine (i tried 4.7).

$("#gridCot").jqGrid('GridUnload');

**Comment by tonytomov** [comment]
Hello,

The method was chaged. Please read the upgarde notes from the official release download or read them here: http://guriddo.net/?p=123585

Kind Regards

**Comment by dizzy0ny** [comment]
Thanks, if i may suggest...in your release notes, have a section labeled "Breaking Changes". Often times when deciding to upgrade, that is what most users will want to know.

**Comment by tonytomov** [comment]
Hello,

Thanks for the suggestion. This will be added definitley

**Comment by tonytomov** [comment]
Can you please confirm if the problem is fixed, so that I close the issue.
Thank you

**Comment by dizzy0ny** [comment]
Yes it is, thank you!  using the v4.8 api as described in the release notes works.
  
$.jgrid.gridUnload("#grid")
