### ISSUE TITLE
hideCol function hiding group headers

### ISSUE THREAD

**Issue by dizzy0ny** [tonytomov/jqGrid#698]
I have a grid with two levels of grouped headers created by calling setGroupHeaders twice:

        grid.jqGrid('setGroupHeaders', {
            useColSpanStyle: false,
            groupHeaders: data.groups
        });
        grid.jqGrid('setGroupHeaders', {
            useColSpanStyle: false,
            groupHeaders: data.subGroups
        });

When i attempt to hide a column, it also hides the top-level grouped header.
    $("#gridCot").jqGrid('hideCol', filteredCols);

I was trying to create a jsfiddle to test and submit wit this ticket..but i could not get the hideCol to work at all w/ jsfiddle (probably something i'm doing wrong).

If this is indeed an issue, i think for now it can be worked around by using jquery to get the th element and calling the hide method.  i noticed that the the TH element has an id that is generated by concatenating the grid name + the column name: '<grid_id>_<col_name>'.  So in if the grid named 'grid1' and the column i want to hide is named 'product'.  I am able to do the following as a work around:
   $(#grid1_product).hide()

**Comment by tonytomov** [comment]
Hello,

In order this to work you will need to destroy grouping header, hide a col and recreate the headers again according to the new visible columns

**Comment by dizzy0ny** [comment]
how do i destroy the group headers?  is there a way to get the list of group headers from the grid or will i have to maintain that in a separate variable in order to re-create them?  it seems like the jquery solution might be a better solution..

**Comment by tonytomov** [comment]
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:groupingheadar#destroying_group_header

**Comment by dizzy0ny** [comment]
Looks like the jquery solution doesn't actually work, it just hides the header (3rd level in my case) and not the column.
The link you provided doesn't indicate how to get the existing list of headers.  I will need that in order to manipulate the start and count as well.   I am thinking maybe for this i may just do a round trip back to the server.

Another issue..re-sizing of columns using dragging seems to be off.  the column header ends up being larger than the actual column.  Attached is an image showing the issue.
This is a great feature! But i think it needs a bit of work....

![image](https://cloud.githubusercontent.com/assets/855627/6791812/6b07a82c-d188-11e4-9a9c-01ad401101a0.png)

**Comment by yanfen1993** [comment]
maybe that is because there is conflit between jqgrid and bootstrap

**Comment by tonytomov** [comment]
Hello,

Could you please explain, what you mean with conflict between jqGrid and Bootstrap?
As for version 5.0 we support Bootstrap styling.

**Comment by yanfen1993** [comment]
when the bootstrap.css is not included in my code, the table header alligns with the column even it is dragged

**Comment by yanfen1993** [comment]
but there is  another problem, the size of the table header do not change when the size of window changes

**Comment by tonytomov** [comment]
Hello,

I will check this, but in case you use Bootstrap and jQueryUI CSS you will need maybe to add additional css for compatibility. Currently I can not remember the name. In all cases I recommend you to use only one of the CSS frameworks. In case of Bootstrap you can use our new feature introduced in version 5.0. To do this you will need to load the needed css and do
```
$("#grid").jqGrid( {
   ...
   styleUI : "Bootstrap",
   ...
});
```

More you can find here: http://guriddo.net/?p=124091

**Comment by tonytomov** [comment]
> but there is another problem, the size of the table header do not change when the size of window changes

Please set the responsive property set to true.
