### ISSUE TITLE
sorttype 'date' unable to sort string date.

### ISSUE THREAD

**Issue by dizzy0ny** [tonytomov/jqGrid#699]
i have a column that displays a string date in the format 'YYYY-MM-DD'.  If i do not set sorttype on the model, the sorting occassionally is off .this doesn't happen for all data sets, but for some it does..
for example, it will sort '2015-02-03' above '2015-03-17'.
If i set the sorttype to 'date' for this column and then attempt to sort by it, i get an exception on line 119 of jquery.jqGrid.js

Uncaught TypeError: Cannot read property 'parseRe' of undefined

How can i properly sort a STRING date?

**Comment by tonytomov** [comment]
Hello,

thanks for let us know. The problem is fixed and you can download the bug fix 4.8.2.

Kind Regards,

**Comment by dizzy0ny** [comment]
great, thankyou! you guys are fast
