### ISSUE TITLE
rows repeating when using virtual scrolling.

### ISSUE THREAD

**Issue by joshikeerti** [tonytomov/jqGrid#703]
Hi,
I am using the configuration below to et the jqGrid

scrollOffset : 0,
						headertitles: true,
						rownum : 50,
						scroll : 1,
						loadonce : true,
						scrollrows : false,
						altRows : true,
						altclass : 'myAltRowClass',
						viewrecords : false,
						ignoreCase : true,
						sortname : 'srcId',
						sortorder : 'desc',
						gridview : true,
						toppager : true,
						hidegrid : false,
						shrinkToFit : true,
						// height: 720,
						multiselect : true,
						autoencode : true,
						loadui : "disable",

When I have a column with multiline data, the scrolling causes the rows to duplicate. Is this an issue with having multiline data in a column ?

**Comment by tonytomov** [comment]
Hello,

Yes this is a problem. This is duplicated - see here: https://github.com/tonytomov/jqGrid/issues/175
