### ISSUE TITLE
Dynamic select dropdown from Array

### ISSUE THREAD

**Issue by adiyatmubarak** [tonytomov/jqGrid#704]
Hii hi need to create dynamic select dropdown in my inline edit, I saw in documentation that jqGrid already mentioned about it through ajax request on [documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki%3acommon_rules#editoptions) with `dataUrl` & `buildSelect`.

But how if I need construct dropdown from my local array variable instead of ajax request??

Thanks in advanced

**Comment by tonytomov** [comment]
Hello,

For inline edit you can construct dynamic values using the editoptions values property.
This can be a string, array and object.

In case of string

```
editoptions: { 
   value: "ALFKI:ALFKI;ANATR:ANATR;ANTON:ANTON;" ,
   ...
 }

```

in case of object

```
editoptions: { 
   value:  {key1:"value1", key2: "value2"...},
   ...
 }
```
In case of array
editoptions: { 
   value: [[Key1, Value1], [Key2, Value2], ...]
   ...
 }
```

The value can be a variable which can be changed depending on some condition.

Hope this helps

Regards

**Comment by adiyatmubarak** [comment]
@tonytomov ohh thanks, it's worked like a charm!

**Comment by tonytomov** [comment]
Glad to help. I will close the question.

**Comment by pinky11** [comment]
I have a list in the view, How do I form the object from the list.

**Comment by tonytomov** [comment]
Hello,

I'm not sure that I understand your question.

**Comment by pinky11** [comment]
Sorryand thanks for replying , I will explain you with an example
I have an array like
var states= ["ABC", "DEF","GHI"];
how do I form value: [[Key1, Value1], [Key2, Value2], ...] from states list.

**Comment by tonytomov** [comment]
Befor to pass to the grid you can build new array like this:

var my_states = [['ABC','ABC'], ['DEF','DEF'], ['GHI','GHI']];

and you can use it in grid. If you have difficulties to build the new array please let me know.

Kind Regards,
Tony

**Comment by pinky11** [comment]
Yes Tony , I am new to javascript and having difficulty to build the new array. Appriciate your help.

**Comment by tonytomov** [comment]
Ok. I will do it in simple way so that you understand what is happen:
```
var states = ['ABC','DEF','GHI'];
var my_states = [];
for(var i=0, len=states.length; i<len; i++ ) {
	var tmp = [];
	tmp.push(states[i]);
	tmp.push(states[i]);
	my_states.push(tmp);
}
```
now the my_states have the desired values.

Regards,
Tony

**Comment by pinky11** [comment]
You are awesome! very Thankful to you

**Comment by pinky11** [comment]
HI Tony, 
One more question on this, is there any built in function in javascript to delete one of the value from array.
suppose if I want to delete ['ABC','ABC'] from 
my_states = [['ABC','ABC'], ['DEF','DEF'], ['GHI','GHI']]; and I dont want to do that by index.I will send 'ABC' and my_states .

**Comment by tonytomov** [comment]
It all depend where you want not to include or delete certain items.

In the code I provided you can check for ceratin value and can not include it.

If this is not the case you can after loop in the new array, get the array item, check for the array items the value , store the index ind dlete it after that.

There are a different situation, but you know it better.


Kind Regards,
Tony

**Comment by pinky11** [comment]
Got it Tony, Thank you for the help
