### ISSUE TITLE
Initialize jQgrid without colModel

### ISSUE THREAD

**Issue by ShovanDhara** [tonytomov/jqGrid#706]
Is it possible to initialize jqgrid plugin into a table without colModel like - 

jQuery("#gfrc1").jqGrid({
   	rowNum:10,
    width:700,
   	rowList:[10,20,30],
   	pager: '#pgfrc1',
   	sortname: 'invdate',
    viewrecords: true,
    sortorder: "desc",
	jsonReader: {
		repeatitems : false
	},
	shrinkToFit: false,
	caption: "Frozen Header",
	height: 'auto'
});
jQuery("#gfrc1").jqGrid('setFrozenColumns');

This above technique is not working for me.

**Comment by tonytomov** [comment]
Hello,

The short answer is No.
