### ISSUE TITLE
Form dialog jump to left after drag and drop

### ISSUE THREAD

**Issue by MJ-Vakili** [tonytomov/jqGrid#707]
I using jqgrid v4.8.1 . When open form dialog for edit ,I want drag and drop it ,But it jump to left after drop.
You have to drag and drop several times .
for test http://www.guriddo.net/demo/guriddojs/edit_add_delete/dialogs/index.html.

**Comment by tonytomov** [comment]
Thanks,

I see the problem. Will investigate it and let you know.

Regards
Tony

**Comment by tonytomov** [comment]
Hello,

We have fixed the problem.

Kind Regards,
Tony
