### ISSUE TITLE
Require dependency causing issues on apps that don't use requirejs

### ISSUE THREAD

**Issue by begizi** [tonytomov/jqGrid#708]
I don't quite understand why a library like jqGrid would need to use requirejs internally. If there is a need to build out the library in multiple files/modular chunks, then there should be a build script (grunt/gulp/make) that concats all of the dependencies into a single src file.

It should still wrap the library in the proper closure to support AMD, Require, and Global, but shouldn't use either internally and consequently force the user to implement one over the other.

**Comment by tonytomov** [comment]
Hello,

Thanks for this opinion. Actually it is the same as you describe.
The idea of AMD is to load only the needed files and define "define dependencies that must load before a module is executed.."

For information see here: http://en.wikipedia.org/wiki/Asynchronous_module_definition

Actually there is a expression that confirm your opinion: 

> For production and deployment, developers can concatenate and minify JavaScript modules based on an AMD API into one file, the same as traditional JavaScript."

**Comment by begizi** [comment]
I see how you're doing that now. I still believe this is a valid issue as the "requirejs" dependencies in the bower.json file aren't actual dependencies and are forcing requirejs to download via bower (and in my case with the `grunt-bower-install` task, causing it to load into the browser and cause all sorts of havoc)

Can you please remove the require files from the bower.json file?

**Comment by tonytomov** [comment]
Hello,

I see it too. This is correct. I have removed require files from bower.json.

Thanks
