### ISSUE TITLE
Country code or language code?

### ISSUE THREAD

**Issue by mkaag** [tonytomov/jqGrid#714]
Hello,

I am experiencing an issue with the Ukrainian locale as I am using the language code to find out which file to load correctly, however when loading Ukrainian it failed.

After looking at the [file name](/tonytomov/jqGrid/blob/master/js/i18n/grid.locale-ua.js), it appears that the id used is UA. According to the ISO 639-1, the language code for Ukraine is UK, not UA. See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for more details.

So my question is was this naming convention defined on purpose or can we correct it?

Thank you, cheers!
Maurice

**Comment by tonytomov** [comment]
Hello,

Thank you very much for let us know about this. You are absolutley right.
The file extension is set as Country code and not as language one. The problem is fixed https://github.com/tonytomov/jqGrid/commit/7c1289c3dc29e20c5b8a1de660702f7400d013c6

Best Regards,
Tony

**Comment by mkaag** [comment]
Brilliant, tx!
