### ISSUE TITLE
Bootstrap table-condensed does not get applied to the header

### ISSUE THREAD

**Issue by codymullins** [tonytomov/jqGrid#716]
When the table-condensed tag is applied to the table, the header does not have the class table-condensed applied, even though the body does.

**Comment by tonytomov** [comment]
Hello,

Thanks for posting this. Can you please post a example how you set a table-condensed?
In the meantime I will try to prepare a example with table-condensed.

Thanks

Kind Regards,
Tony

**Comment by tonytomov** [comment]
Hello,

I have tested with table-condensed class and everything seems to work as expected. The only problem that I see is the pager and top pager which are unsized according to the table-condensed.

I'm going to fix this in the next couple of days.

By the way the correct setting for table condensed is like this (before loading the grid)

```
$.jgrid.styleUI.Bootstrap.base.headerTable = "table table-bordered table-condensed"
$.jgrid.styleUI.Bootstrap.base.rowTable = "table table-bordered table-condensed"
$.jgrid.styleUI.Bootstrap.base.footerTable = "table table-bordered table-condensed"
```

Regards

**Comment by tonytomov** [comment]
Hello,

I have fixed the problem. The demo is here: http://www.guriddo.net/demo/bootstrap/functionality/table_condensed/index.html

I will close the issue. In case you have problem, please reopen it.
Thank you

Kind Regards
