### ISSUE TITLE
Use JavaScript's toLocaleString rather than Yahoo's NumberFormat

### ISSUE THREAD

**Issue by Lukenickerson** [tonytomov/jqGrid#719]
Is there a reason that a custom function `NumberFormat` (in https://github.com/tonytomov/jqGrid/blob/master/js/jquery.fmatter.js) is being used when JavaScript provides a function similar functionality based off the browser's location? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by tonytomov** [comment]
Hello,

The most important reason is that this function is not supported in all browsers.
By example look here: https://msdn.microsoft.com/library/dn412711%28v=vs.94%29.aspx

This say:

>Requirements

>Supported in the following document modes: Quirks, Internet Explorer 6 standards, Internet >Explorer 7 standards, Internet Explorer 8 standards, Internet Explorer 9 standards, Internet >Explorer 10 standards, Internet Explorer 11 standards. Also supported in Store apps (Windows 8 >and Windows Phone 8.1). See Version Information.

>locales and options parameters:

>Supported in the Internet Explorer 11 standards document mode. Also supported in Store apps >(Windows 8.1 and Windows Phone 8.1). See Version Information. Not supported in the following >document modes: Quirks, Internet Explorer 6 standards, Internet Explorer 7 standards, Internet >Explorer 8 standards, Internet Explorer 9 standards, Internet Explorer 10 standards. Not supported >in Windows 8.

As you can see the list is too long just for IE

**Comment by Lukenickerson** [comment]
The work-around I've used is to add this function to the top of my `grid.locale` file...
```javascript
var thousandsSeparator = (function(){
    if (typeof Number.prototype.toLocaleString === 'function') {
        var num = 1000;
        var numStr = num.toLocaleString();
        if (numStr.length == 5) {
            return numStr.substr(1, 1);
        }
    }
    return ","; // fall-back for older / non-compliant browsers
})();
```
(http://stackoverflow.com/questions/32054025/how-to-determine-thousands-separator-in-javascript)

And then used this separator character down below...
```javascript
...
	formatter : {
		integer : {thousandsSeparator: thousandsSeparator, defaultValue: '0'},
		number : {decimalSeparator:".", thousandsSeparator: thousandsSeparator, decimalPlaces: 2, defaultValue: '0.00'},
		currency : {decimalSeparator:".", thousandsSeparator: thousandsSeparator, decimalPlaces: 2, prefix: "", suffix:"", defaultValue: '0.00'},
...
```

Could do something similar with the decimal character as well.

**Comment by tonytomov** [comment]
Hello,

This is nice.
Another cons is that many people from different Countries can work on one computer - in this case every man should tune the locale which in most cases is not possible and one man can work on different machines outside of its Country - in this case they should tune the settings which too in most cases is not possible.

I think that settings the language settings for formatting number this way (like in current jqGrid) and a possibility to change it quick and without problems like here: http://www.guriddo.net/demo/guriddojs/functionality/localization/index.html  is much simpler and safely than to trust of the locale settings.

Kind Regards,
Tony

**Comment by Lukenickerson** [comment]
Yes, I can understand the need for multiple languages on one computer and the ability to switch easily.  You could change the code I posted above to allow for that, by taking in a language tag as an argument... https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument

```javascript
function getThousandsSeparator (languageTag) {
    if (typeof Number.prototype.toLocaleString === 'function') {
        var num = 1000;
        var numStr = num.toLocaleString(languageTag);
        if (numStr.length == 5) {
            return numStr.substr(1, 1);
        }
    }
    return ","; // fall-back ... but is static so may not be accurate
})();
```

...but it wouldn't have a reliable fall-back for older browsers.

**Comment by tonytomov** [comment]
Hello,

Thanks for this. We really want to make the thinks simple as possible and to use less code, but one of our first priories is to support many browsers as possible.

As you say : 

>>...but is static so may not be accurate

So I will close the question with a hope that after some time all browsers will support this.

Thank you for your efforts.

Kind Regards,
Tony
