### ISSUE TITLE
Use localeCompare when sorting columns

### ISSUE THREAD

**Issue by Lukenickerson** [tonytomov/jqGrid#720]
Currently the columns appears to be sorted using the usual JavaScript sort, which is case sensitive. To allow for regional differences among sorting, could [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) be used instead?
([Related SO answer](http://stackoverflow.com/questions/8996963/how-to-perform-case-insensitive-sorting-in-javascript))

**Comment by tonytomov** [comment]
Hello, 

Thanks for the suggestion.
jqGrid has a mechanism to implement a wide area of sorting possibilities.
1. the option ignoreCase : true ignores the case sensitive sorting
2. sorttype can be a defined as function - see grid docs
3 and finally there is a sortfunc defined in colModel where you directly cann implement localCompare

Please look for [Natural Sorting algorithm in jqGrid](http://stackoverflow.com/questions/14865567/how-to-implement-naturalsort-in-jqgrid)

I suppose you can very easy implement localCompare here.
See [documentation for sortfunc](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:colmodel_options&s[]=sortfunc)

Kind Regards,
Tony

**Comment by tonytomov** [comment]
Can you please consider this issue to closed or you need more assistance for implementing this suggestion
