### ISSUE TITLE
Cannot read property 'decimalSeparator' of undefined. No locale!

### ISSUE THREAD

**Issue by korsun** [tonytomov/jqGrid#721]
Hello! I've tried to make pager work but this error appears.

My jqGrid init:

     $equipTable.jqGrid({
		url: 'assets/data/equip.json',
		mtype: 'GET',
		datatype: 'json',
                rowNum: 6,
		regional: 'ru',
		viewrecords: true,
		loadonce: true,
		gridview: false,
		pager: '#equip-pagination',

and so on.

I've tried not to include any locale file at all, include 'locale-en', include 'locale-ru' and set 'regional' parameter. Result is the same. What can I do?

**Comment by tonytomov** [comment]
Hello,

Can you please post your full code and if possible a data.
The best will be if you prepare online  example.

Please provide additional information about jQuery, jQuery UI (if used), browser OS and etc.
Any additional info will help to solve the problem.

Kind Regards
