### ISSUE TITLE
colModel searchoptions dataEvents for filterToolbar search not working

### ISSUE THREAD

**Issue by ManuelAyaso** [tonytomov/jqGrid#727]
Hi,

I was trying to use the dataEvents property on searchoptions (colModel) to add some custom events I want to be triggered when the user wants to use the filterToolbar search functionality (entering invalid characters, etc). This was working before (previous to 4.8.2 I believe, it was already defined in 4.6 this way and working).

Using latest version this is not working. Having a look at the code, it seems to be overwriting the dataEvents of the searchoptions when it's binding the events (bindEv) depending of the type of field in the filterToolbar (text, etc.), something like: x.dataEvents = [...], so the ones I defined in colModel are lost? Is there any other way to this now?

Regards

**Comment by tonytomov** [comment]
Hello,

Can you please post a simple test case for this?
Thank you.

Kind Regards,
Tony

**Comment by ManuelAyaso** [comment]
Hi Tony,

Thanks for the reply. I created an example based in one of your examples here: http://jsbin.com/wonopeluma/edit?html,output

"Ship Name" contains a dataEvent whereby if you click on it it should show an alert.

I've checked the code and it's kind of overwriting the dataEvents that I define:
soptions.dataEvents =... instead of soptions.dataEvents.push or something like that at bindEv function. I've changed that myself on a local copy of the plugin and it would be working.

Best regards,
Manuel

**Comment by tonytomov** [comment]
Hello Manuel,

Thank you for the test case and bug report. I see that something is wrong here and will analyze it and replay ASAP.

Thank you,
Kind Regards,
Tony

**Comment by tonytomov** [comment]
Hello Manuel,

Thanks again for the bug report.
I have fixed the problem : https://github.com/tonytomov/jqGrid/commit/7bfb73499c8e382f0892f068c6d3eb153678c6a7

Please let me know if everything is ok .

Best Regards,
Tony

**Comment by ManuelAyaso** [comment]
Hi Tony,

It's working now. Thanks!

Best regards,
Manuel

**Comment by tonytomov** [comment]
Now I will close the issue
