### ISSUE TITLE
Two rows selected after cancelling 'add row'

### ISSUE THREAD

**Issue by meterlongcat** [tonytomov/jqGrid#728]
When using inline editing with the toolbar control buttons, it is possible to have two rows selected. The multi-select feature has not been enabled in this case.

Steps to reproduce (note that you'll need a grid with at least one existing row of data):

1 - Click + button to add new row
2 - Click on another existing row already in the grid. jqGrid correctly cancels addition.
3 - The row that was clicked in step 2 now remains in a selected state even when other rows are selected. The only way to clear this is to explicitly select it, then select a different row.

I believe this should just be a matter of removing the ui-state-highlight class at the appropriate time.

**Comment by tonytomov** [comment]
Hello,

Thanks for the detailed explanation. I will try to reproduce this situation and will let you know

**Comment by tonytomov** [comment]
Hello,

I was able to reproduce the problem.
I have fixed it in GitHub https://github.com/tonytomov/jqGrid/commit/acb5d63d4afb16fa84a17f5c5e80b12fd9fb28be .

You can get the build form github and test it.
Please let me know if it is fixed.
Thank you for your effort.

Kind Regards,
Tony

**Comment by meterlongcat** [comment]
Hi Tony,

I have tested your code change and can confirm that it is fixed.

Thank you very much for the quick turnaround, I didn't expect this to be fixed in under 12 hours :)

Kind Regards

**Comment by tonytomov** [comment]
Thanks.
Will close the issue.
