### ISSUE TITLE
All jqGridInline* Events are called as much as value of myGrid.jqGrid('getGridParam','page')

### ISSUE THREAD

**Issue by artvel** [tonytomov/jqGrid#731]
All jqGridInline* Events are called wrong and could not be for any notifications.
jqGrid  4.6.0

Thanks for any help.

**Comment by tonytomov** [comment]
Hello,

Can you please post a simple test case?
Does this happen with jqGrid 4.8 and/or 5.0

**Comment by artvel** [comment]
Hi thx for the fast answer. I made a mistake in the loadComplete function.
Works as it should.
Sorry.
