### ISSUE TITLE
rowNum parameter is not reflecting

### ISSUE THREAD

**Issue by senthilporunan** [tonytomov/jqGrid#738]
Hi,

I am trying to set pagination with help of jqGrid. So, i have set rowNum as 10 (10 records per page) with the help of below configuration. But, its loading 70 records in same page. And in pagination it is showing Page 1 of 0. Please find the attached image. 

$('#gridId').jqGrid({
                     datatype: "local",
                     gridView: true,
                    colNames: ['A','B'],
                    colModel: [ ...],
                    rowNum : 10,
                 loadonce: true ,
                   pager : '#pageDiv',
                   loadComplete: function() {     
                        loadGridData();
                    }
});

var loadGridData = function() {
     var data=  $.parseJSON('${result}');
      for(var i=0;i<=data.length;i++){
                  $('#gridId').addRowData(i+1, data[i]);
      }
}

**Comment by tonytomov** [comment]
Hello,

The addRowData is not a good way to add a records with pagination.
If you result is a json data you can still set data parameter in grid
```
$('#gridId').jqGrid({
datatype: "local",
data: result,
gridView: true,
...
```

Suppose result is JSON.

if the result is a string you can direct use datastr parameter like this

```
$('#gridId').jqGrid({
datatype: "local",
datastr: result,
gridView: true,
...
```

Please let me know if this resolves the problem.

Kind Regards

**Comment by tonytomov** [comment]
In case there is a problem with this, please reopen it
