### ISSUE TITLE
Edit mode to deal with the text and the value of custom controls

### ISSUE THREAD

**Issue by tofdragon** [tonytomov/jqGrid#740]
Processing the text edit mode and the value of the control, the support is not very good,
Situation is as follows: the text and the value of control, after choose the input, will return to the text and the value of the object at the same time, but this jqgrid built-in support deal with the situation of the object, is a single value or a single object.

Modify source grid. The inline. SaveRow in js source code is as follows:

case 'custom' :
		
    if(cm.editoptions && $.isFunction(cm.editoptions.custom_value)) {
			//update for
			if($($t).jqGrid('isCdColumn', cm)){
			      var cdValue = cm.editoptions.custom_value.call($t, $(".customelement",this),'get');
			      tmp[nm] = cdValue[cm.editoptions.custom_labelField];
			      tmp[nm + cm.excdstuffix] = cdValue[cm.editoptions.custom_valueField];
			}else{
			     tmp[nm] = cm.editoptions.custom_value.call($t, $(".customelement",this),'get');
			}				
   } 

 If there are other better ways to solve, and an introduction to the event listeners online dynamic setting text value, this is not very good, because there is no need to according to the code to look up again, and the value and the text controls should be processed in the same process

**Comment by tonytomov** [comment]
Hello,

For me it is not clear what you mean, but in your code you have a lot of things that are not defined and I don't know what they are supposed to do like these: $($t).jqGrid('isCdColumn', cm), cm.editoptions.custom_labelField, nm + cm.excdstuffix, cm.editoptions.custom_valueField

**Comment by tofdragon** [comment]
1.Initial Configuration
 ```javascript
$("#jqGrid").jqGrid({
     url:"../../jqgrid/demo/data/data4.json",
     datatype: "json",
     mtype:"post",
     colNames : ['pkid', 'name', 'customTextValueControl'],
     colModel : [   
	      {name : 'pkid', index : 'pkid',width : 55, hidden:true, exaddeditdata:true, exuniquekey:true}, 
	      {name : 'name',index : 'name asc, invdate',width : 100,  editable: true }, 
	      {name : 'sj_value',hidden:true,exaddeditdata:true},
	      {name : 'sj_text', index : 'sj23',width : 150,editable: true,
	                        	 edittype: "custom",
	                        	 exedittype:"cd",
		                         editoptions: {
		                             custom_value: getListBoxElementValue,
		                             custom_element: createListBoxEditElement,
		                             custom_labelField:"detail",
		                             custom_valueField:"code",
		                             custom_cdStuffix:"_value"
		                         }
	                        } 
	         ],
                 editurl:"clientArray",
	         loadComplete:function(){
         	    $(this).jqGrid("initInlineEditData");
	        },
	       ondblClickRow: editRow
});
```
Why naming cd? 

cd is the first letter of the abbreviation code and detail


2.custom function
```javascript
     function createListBoxEditElement(value, editOptions){
	var cdName = editOptions.name + editOptions.custom_cdStuffix;
    var codeValue = $("#jqGrid").jqGrid("getRowData", editOptions.rowId)[cdName];
	var $listbox = $('<span></span>');
	var listboxConfig = {  
			id:editOptions.id + "_editor",
			name:editOptions.id + "_editor",
	        url:"../../data/listbox.json",
            transUrl:"../../jqgrid/demo/data/listbox.json",
	        value:codeValue,
	        delimiter:";"
	};
	$listbox.sblistbox(listboxConfig); 
	return $listbox;
}

function getListBoxElementValue(elem, oper, value){
	if (oper === "set") {
             $(elem).sblistbox().setValue(value);
        }

        if (oper === "get") {
           var valueObj = {
    	        "code"  : 	$(elem).sblistbox().getValue(),
    	        "detail":  $(elem).sblistbox().getLabel()
             }
       return valueObj;
    }
}
```

2.extend jqgrid function
  ```javascript
  $.extend($.jgrid,{
	
	/**
	 *  Are text-value column
	 * 
	 * @param columnModel: column model
	 */
	isCdColumn: function(columnModel){
		if(columnModel.exedittype !== undefined && columnModel.exedittype === "cd"){ 
			return true;
		}
		return false;
	},
	
	
	/**
	 * Gets the column suffix text-value of
	 * @param columnModel:column model
	 */
	getCdColumnStuffix : function(columnModel){
		if(columnModel === undefined || columnModel === null){
			return "";
		}
		if(columnModel.editoptions === undefined){
			return "";
		}
		return columnModel.editoptions.custom_cdStuffix;
	}
});

**Comment by tofdragon** [comment]
@tonytomov 

Doubt Code
Modify source grid. The inline. SaveRow in js source code is as follows:

case 'custom' :
 try {
   if(cm.editoptions && $.isFunction(cm.editoptions.custom_value)) { 
      if($.jgrid.isCdColumn(cm)){
      var cdValue = cm.editoptions.custom_value.call($t, $(".customelement",this),'get');
          tmp[nm] = cdValue[cm.editoptions.custom_labelField];
          tmp[nm + $.jgrid.getCdColumnStuffix(cm)] = cdValue[cm.editoptions.custom_valueField];
      }else{
      tmp[nm] = cm.editoptions.custom_value.call($t, $(".customelement",this),'get');
     }
      ..........
    break;
1.Initial Configuration

$("#jqGrid").jqGrid({
     url:"../../jqgrid/demo/data/data4.json",
     datatype: "json",
     mtype:"post",
     colNames : ['pkid', 'name', 'customValue', 'customText'],
     colModel : [   
          {name : 'pkid', index : 'pkid',width : 55, hidden:true, exaddeditdata:true, exuniquekey:true}, 
          {name : 'name',index : 'name',width : 100,  editable: true }, 
          {name : 'sj_value',hidden:true,exaddeditdata:true},
          {name : 'sj', index : 'sj',width : 150,editable: true,
                                 edittype: "custom",
                                 exedittype:"cd",
                                 editoptions: {
                                     custom_value: getListBoxElementValue,
                                     custom_element: createListBoxEditElement,
                                     custom_labelField:"detail",
                                     custom_valueField:"code",
                                     custom_cdStuffix:"_value"
                                 }
                            } 
             ],
                 editurl:"clientArray",
             loadComplete:function(){
                $(this).jqGrid("initInlineEditData");
            },
           ondblClickRow: editRow
});
Why naming cd?

cd is the first letter of the abbreviation code and detail

2.custom function

     function createListBoxEditElement(value, editOptions){
    var cdName = editOptions.name + editOptions.custom_cdStuffix;
    var codeValue = $("#jqGrid").jqGrid("getRowData", editOptions.rowId)[cdName];
    var $listbox = $('<span></span>');
    var listboxConfig = {  
            id:editOptions.id + "_editor",
            name:editOptions.id + "_editor",
            url:"../../data/listbox.json",
            transUrl:"../../jqgrid/demo/data/listbox.json",
            value:codeValue,
            delimiter:";"
    };
    $listbox.sblistbox(listboxConfig); 
    return $listbox;
}

function getListBoxElementValue(elem, oper, value){
    if (oper === "set") {
             $(elem).sblistbox().setValue(value);
        }

        if (oper === "get") {
           var valueObj = {
                "code"  :   $(elem).sblistbox().getValue(),
                "detail":  $(elem).sblistbox().getLabel()
             }
       return valueObj;
    }
}
2.extend jqgrid function

  $.extend($.jgrid,{

    /**
     *  Are text-value column
     * 
     * @param columnModel: column model
     */
    isCdColumn: function(columnModel){
        if(columnModel.exedittype !== undefined && columnModel.exedittype === "cd"){ 
            return true;
        }
        return false;
    },


    /**
     * Gets the column suffix text-value of
     * @param columnModel:column model
     */
    getCdColumnStuffix : function(columnModel){
        if(columnModel === undefined || columnModel === null){
            return "";
        }
        if(columnModel.editoptions === undefined){
            return "";
        }
        return columnModel.editoptions.custom_cdStuffix;
    }
});

**Comment by tonytomov** [comment]
Hello,

The recommendation will not be accepted. Sorry.

Kind Regards
