### ISSUE TITLE
Resizing column with group header results in group header out of alignment

### ISSUE THREAD

**Issue by iguana3** [tonytomov/jqGrid#745]
Problem appears to be in mismatch between dragEnd which sets the native style.width, as opposed to jqGridResizeStop.setGroupHeaders event handler which uses jquery width.  These will be in sync if box-sizing is content-box, but if it is border-box, the jquery method will add in padding and border widths, whereas the native style.width will assume the specified width includes padding and border

**Comment by tonytomov** [comment]
Hello,

Can you please post a simple test case?
Using this example http://www.guriddo.net/demo/guriddojs/functionality/group_column_headers/index.html we do not have the problem you speak.

Thank you.

Kind Regards
Tony

**Comment by iguana3** [comment]
Hi Tony, thanks for the prompt response:

Your example works because the box-sizing is content-box

First screen shot before resizing (first row widths for both header and data table are in sync)
Second screen shot after resizing (first row and third row widths for header table and first row widths for data table are all in sync)
Both jquery width() and style.width set the width as specified to exclude borders and padding

Third screen shot before resizing but box-sizing for both tables, all rows, all cells has been reset to border-box
(first row widths for both header and data table are in sync, same as first screen shot)

Fourth screen shot after resizing.   In this case the first row widths for header table are 5px more than third header table row and first data table row
because the cell width for the first header table row was set using jquery width which because box sizing is border-box now adds left and right padding (2px each) and border right width (1px)

                     $(ts).bind('jqGridResizeStop.setGroupHeaders', function (e, nw, idx) {
                           $firstRow.find('th').eq(idx).width(nw);
                     });


Whereas the cell width for third header table row and first row data table are set using style.width which sets the value as specified

                     dragEnd: function() {
                           this.hDiv.style.cursor = "default";
                           if(this.resizing) {
                                  var idx = this.resizing.idx,
                                  nw = this.headers[idx].newWidth || this.headers[idx].width;
                                  nw = parseInt(nw,10);
                                  this.resizing = false;
                                  $("#rs_m"+$.jgrid.jqID(p.id)).css("display","none");
                                  p.colModel[idx].width = nw;
                                  this.headers[idx].width = nw;
                                  this.headers[idx].el.style.width = nw + "px";
                                  this.cols[idx].style.width = nw+"px";

So it seems as if the solution is to be consistent in using jquery width() or style.width in all cases

Regards,
Alan

[cid:image001.png@01D12DD3.42BBD350]

[cid:image004.png@01D12DD3.F8F88140]

[cid:image002.png@01D12DBF.04A30110]

[cid:image003.png@01D12DD2.DC4F4660]

**Comment by iguana3** [comment]
Here is a test page, we run it on IE11, not sure why the grid doesn’t seem to show up in chrome or firefox.



From: Abel, Alan - PENNINGTON NJ
Sent: Thursday, December 03, 2015 2:28 PM
To: 'tonytomov/jqGrid'; tonytomov/jqGrid
Subject: RE: [jqGrid] Resizing column with group header results in group header out of alignment (#745)

Hi Tony, thanks for the prompt response:

Your example works because the box-sizing is content-box

First screen shot before resizing (first row widths for both header and data table are in sync)
Second screen shot after resizing (first row and third row widths for header table and first row widths for data table are all in sync)
Both jquery width() and style.width set the width as specified to exclude borders and padding

Third screen shot before resizing but box-sizing for both tables, all rows, all cells has been reset to border-box
(first row widths for both header and data table are in sync, same as first screen shot)

Fourth screen shot after resizing.   In this case the first row widths for header table are 5px more than third header table row and first data table row
because the cell width for the first header table row was set using jquery width which because box sizing is border-box now adds left and right padding (2px each) and border right width (1px)

                     $(ts).bind('jqGridResizeStop.setGroupHeaders', function (e, nw, idx) {
                           $firstRow.find('th').eq(idx).width(nw);
                     });


Whereas the cell width for third header table row and first row data table are set using style.width which sets the value as specified

                     dragEnd: function() {
                           this.hDiv.style.cursor = "default";
                           if(this.resizing) {
                                  var idx = this.resizing.idx,
                                  nw = this.headers[idx].newWidth || this.headers[idx].width;
                                  nw = parseInt(nw,10);
                                  this.resizing = false;
                                  $("#rs_m"+$.jgrid.jqID(p.id)).css("display","none");
                                  p.colModel[idx].width = nw;
                                  this.headers[idx].width = nw;
                                  this.headers[idx].el.style.width = nw + "px";
                                  this.cols[idx].style.width = nw+"px";

So it seems as if the solution is to be consistent in using jquery width() or style.width in all cases

Regards,
Alan

[cid:image001.png@01D12DE8.C5426360]

[cid:image004.png@01D12DE8.C5426360]

[cid:image005.png@01D12DE8.C5426360]

[cid:image006.png@01D12DE8.C5426360]

**Comment by tonytomov** [comment]
Hello,

Thank you for detailed explanation.
Sorry, but I can not see the pictures and the demo code.

Can you please post this again or send to support at guriddo dot net?
Thank you.

Just curios to ask why we should change the content-box to border-box if this is determined on the grid css?

Kind Regards,
Tony

**Comment by iguana3** [comment]
My apologies Tony, not sure why the attachments did not go thru.
I will attach them here.
Also attached are screenshots of the modified test page, and our application page.  Please note that the effect is more pronounced in our actual page than in the test page, not sure why.

As to why you should change from content-box to border-box, the nature of CSS is that if you are using many different platforms, they may conflict, in our case apparently bootstrap is overriding the box-sizing to border-box, (I don't see anywhere in your css where you explicitly set box-sizing).  So I'm not suggesting that you explicitly specify either of the 2, just to be consistent in using jquery width vs. native style.width, so that it will work in either case

![actualpageafterresizing](https://cloud.githubusercontent.com/assets/16119465/11593363/da7a380c-9a71-11e5-922d-313d8382e9a3.PNG)

[jqGrid Loading Data - Group Columns Headers.htm.txt](https://github.com/tonytomov/jqGrid/files/52133/jqGrid.Loading.Data.-.Group.Columns.Headers.htm.txt)
![borderboxafterresizing](https://cloud.githubusercontent.com/assets/16119465/11592989/d461abd2-9a6f-11e5-9f84-759bbe308ffd.PNG)
![borderboxafterresizingf12](https://cloud.githubusercontent.com/assets/16119465/11592988/d461adda-9a6f-11e5-8d00-f461c9f5b3fe.PNG)
![borderboxbeforeresizingf12](https://cloud.githubusercontent.com/assets/16119465/11592992/d465a836-9a6f-11e5-9a84-f094c5724c19.PNG)
![contentboxafterresizingf12](https://cloud.githubusercontent.com/assets/16119465/11592990/d464580a-9a6f-11e5-9e96-9bfa168061ef.PNG)
![contentboxbeforeresizingf12](https://cloud.githubusercontent.com/assets/16119465/11592991/d4651326-9a6f-11e5-86e8-8f3aa96b074a.PNG)

**Comment by tonytomov** [comment]
Thanks for the explanations, examples and hint of resolving the problem.

I have make the needed changes here : https://github.com/tonytomov/jqGrid/commit/84cc4e47fbe0b7ab38a5ee59c225ab982855625c

Please let me know if this fixes the problem and if yes, please close the issue.

Thank you

Kind Regards,
Tony

**Comment by iguana3** [comment]
Thanks Tony,
I downloaded the zip file from 'browse files' above, the change is in js/grid.grouping.js but not in js/jquery.jqgrid.js. I'm not at all familiar with the build process, there is a gradle.bat, I tried running that, ang got the following:
Exception in thread "main" java.net.UnknownHostException: services.gradle.org
Are there parameters that need to be specified? Or do I just manually concatenate all the grid.*.js files?

**Comment by tonytomov** [comment]
Hello,

When you click on the Download Zip button you will get the last change.
The file is named jquery.jqGrid.min.js and jquery.jqGrid.js and they are in the js sub directory of the downloaded jqGrid-master.

I have checked - the change is present in these files - this is true since of this commit : https://github.com/tonytomov/jqGrid/commit/232ba0abed8b9ab4bbab2d591256b73a40018248

**Comment by iguana3** [comment]
Thanks Tony,

I have downloaded the zip file, looks good. I will close the issue.
