### ISSUE TITLE
Add license to bower file.

### ISSUE THREAD

**Issue by SamMousa** [tonytomov/jqGrid#747]
Please add the license name to the bower.json file.

I have looked it up on your website and it should be `CC-BY-NC-3.0`.

**Comment by linquize** [comment]
Which version is the first version of changing license to CC-BY-NC-3.0?
I remember that it used to be MIT+GPL 3 years ago!

**Comment by tonytomov** [comment]
@SamMousa ,

I have added this property: https://github.com/tonytomov/jqGrid/commit/eb3575558f3be454f91c8810eedf59ec75fe08f4

@ianoxley  
You may need to look at this blog post: http://www.trirand.com/blog/?p=1438

The last MIT GPL2 version is 4.7.0

@SamMousa if everything is ok, consider to close the issue. Thank you.

Kind Regards,
Tony

**Comment by SamMousa** [comment]
Thanks for the prompt reply!
