### ISSUE TITLE
editGridrow postIt()

### ISSUE THREAD

**Issue by zhangqhzz** [tonytomov/jqGrid#750]
......
if(postdata[oper] === opers.addoper ) {
...
       if(rp_ge[$t.p.id].closeAfterAdd) {
		if($t.p.treeGrid !== true){
		    $($t).jqGrid("setSelection",ret[2]);
                   //实际使用时，遇到麻烦
                   //此处是否应该修改成setTimeout(function(){$($t).jqGrid("setSelection",ret[2]);},1000);
                   //实际使用时，修改后麻烦解除
                  .......
	       }
      }
...
}else{
// the action is update
   if(rp_ge[$t.p.id].reloadAfterSubmit) {
       $($t).trigger("reloadGrid");
	 if( !rp_ge[$t.p.id].closeAfterEdit ) {setTimeout(function(){$($t).jqGrid("setSelection",postdata[idname]);},1000);}
	 }
......

**Comment by tonytomov** [comment]
Hello,
I'm not sure what you mean with this.

Can you please explain it again.
Thank you for your effort.

Kind Regards
