### ISSUE TITLE
setGroupHeaders  problem ?

### ISSUE THREAD

**Issue by zhump** [tonytomov/jqGrid#751]
look
http://jsfiddle.net/vtgh8ohs/3/

![mvu6 lt03 3cn9f1u5bc0xt](https://cloud.githubusercontent.com/assets/7962067/11994612/b7d66a44-aa7c-11e5-9aad-eb1b9c483a74.png)

**Comment by tonytomov** [comment]
Hello,

Tanks for the demo. I will investigate this and replay ASAP.
Sorry for delay.

**Comment by zhump** [comment]
Why not use a two-dimensional array( colModel ) to show multi header  ?

**Comment by zhump** [comment]
hi , the grid is great....i have question,Why not use multi-dimensional array( colModel) to show multi header ?

**Comment by zhump** [comment]
hi , the grid is great....i have suggest,Why not use multi-dimensional array( colModel) to show multi header ?

**Comment by tonytomov** [comment]
Better late, than never. Fixed.

Kind Regards,
Tony
