### ISSUE TITLE
How can I take the 'Grand Total' to the first row or column?

### ISSUE THREAD

**Issue by haozecc** [tonytomov/jqGrid#753]
I use the jqGrid's pivot table,I want to take the 'Grand Total' to the first row or column.
Is there no option to set this?And is there another way to solve it?
'Grand Total' is 'rowTotals' or 'colTotals'.
Thank you.

**Comment by tonytomov** [comment]
Hello,

Whne set rowTotals makes total of the row, while colTotals make a total of the column.
You may refer here: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:pivotsettings#pivotoptions
