### ISSUE TITLE
How to override editrules default javascript alert in custom_func ?

### ISSUE THREAD

**Issue by idkw** [tonytomov/jqGrid#757]
Hello

I'm using version 5.0.2 of JqGridJS

I am facing the following problem.

I have a field for which I want some client side validation before sending it to the server.
I'm trying to use editrules with a custom validation function.

```
{
	index : "my_field",
	name : "my_field",
	align : 'center',
	search : false,
	sortable : false,
	width: 150,
	editable : true,
	edittype: 'text', 
	editrules: { 
		custom: true, 
		custom_func: function(value, colName, colId){
			if(value === false){
				return [false, "Sorry this is not a valid entry"];
			}else{
				return [true, ""];
			}
		} 
	}
}
```

However it doesn't seem there is a way to display a custom error message.
JqGrid expects the custom_func function to return an array `[success, errorMessag]` and then displays a basic Javascript alert box which I can't prevent to show up.

**How would I override the JqGrid method which displays that alert box and instead use one of my custom html alert boxes ?**

Thank you

**Comment by tonytomov** [comment]
Hello,

Thank you for this note. I see we have different error functions in case of validation. This not good.
I will try to fix this in the nest days. Will replay when ready.

Thank you.

Kind Regards,
Tony

**Comment by tonytomov** [comment]
Hello,

I have added validationCell https://github.com/tonytomov/jqGrid/commit/eea408f0d0620de637f4bf96e757512d7f6c93d8 event - when defined it can display a custom message. Parameters passed to this are the element, error message, row index and column index

Please let me know if this solves your problem. I will close the issue
