### ISSUE TITLE
afterInsertRow event not called on treeGrid mode

### ISSUE THREAD

**Issue by wlisesrivas** [tonytomov/jqGrid#758]
**jqGrid version: 5.0.1**
Problem: Only when the grid is treeGrid mode the afterInsertRow doesn't execute.
Tested in Google Chrome Version 47.0.2526.111 m
**jQuery version: 1.11.3**

```javascript
$('#grid').jqGrid({
	url: link_to('data/'), // url to my server
	datatype: 'xml',
	mtype: 'POST',
	treeGrid: true, // <- Only when is treeGrid mode 
	treeGridModel: 'adjacency',
	ExpandColumn: 'name',
	ExpandColClick: false,
	gridview: false, // in this version this is required to execute the afterInsertRow method
	// others options
	afterInsertRow:function(rowid,rowdata){
		console.log("afterInsertRow called");
	}
});
```
Note: check that I has the gridview option set to false, for this version is required to execute the afterInsertRow event.

**Comment by tonytomov** [comment]
Hello,

When a treeGrid is set to true the option gridview internally  is set to true from the grid setup process.

If you tell me what is your goal and why you need this option (event) I can maybe recommend you a solution.

Thank you 
Kind Regards,
Tony

**Comment by wlisesrivas** [comment]
I need to modify the column style depend of hes value. Previously I made it without problems, after update to the last version **jqGrid 5.0.1** this does not work. 

For example, the progress of the some task:
![Previews version](http://s28.postimg.org/3nrtsup5p/afterinsert.jpg)

I know that I can do some "force" with jQuery but this may take some blinking.

Thanks in advance.

**Comment by tonytomov** [comment]
Do you have try to use a custom formatter for this purpose?
Here is demo: http://www.guriddo.net/demo/guriddojs/functionality/formatters_custom/index.html

**Comment by wlisesrivas** [comment]
Yeah, exactly.

Thank you!
