### ISSUE TITLE
what does `pt` mean in `pt=$($t).jqGrid('getGridRowById', selection);` ?

### ISSUE THREAD

**Issue by shipengyan** [tonytomov/jqGrid#762]
what does `pt` mean in `pt=$($t).jqGrid('getGridRowById', selection);`  ?

thanks a lot

**Comment by tonytomov** [comment]
Hello,

The method getGridRowById return the row as html object and not as data.
So pt means html object of requested jqGrid row by id.

Regards,
Tony

**Comment by shipengyan** [comment]
@tonytomov ，yeah. I know its real meaning, but I want to know what 'pt' **word** stand for .  'Pure table'? Or something else?

**Comment by tonytomov** [comment]
@shipengyan 
Think of it as you want.  ;-)
The closes that I can remember maybe it mean pointer to the row

**Comment by shipengyan** [comment]
haha，get it
