### ISSUE TITLE
jQuery.browser undefined

### ISSUE THREAD

**Issue by chosroes** [tonytomov/jqGrid#763]
Hi,

I'm using jQuery 2.1.4 in my project and jqGrid seems to be incompatible since jQuery.browser function has been removed from jQuery.

So I get this error : `Uncaught TypeError: Cannot read property 'safari' of undefined`, and I can't use jqGrid...

**Comment by chosroes** [comment]
Please close this issue, I used the jquery.jqGrid.js from the bower jqGrid root dir... The one in js dir is the good one.

**Comment by tonytomov** [comment]
Hello,

You can close this too.
