### ISSUE TITLE
About jqGrid Licensing

### ISSUE THREAD

**Issue by mgallegos** [tonytomov/jqGrid#764]
Is jqGrid not open source anymore? What's the lastest version licensed under the MIT and GPL licenses?

**Comment by tonytomov** [comment]
Hello,

As of December 2014 jqGrid is not under MIT/GPLv2 license : http://www.trirand.com/blog/?m=201412
The last version under MIT/GPL v2 is 4.7.0. 

Best Regards,
Tony

**Comment by garora** [comment]
Sad to know that, its not under GPLv2 anymore now. @tonytomov

**Comment by bouks** [comment]
Hi.

@mgallegos if you're searching for a free to use grid, you can check https://github.com/openpsa/jsgrid
that is based on a fork of the 4.7.0 version of jqgrid and should be fully compatible with your application.
