### ISSUE TITLE
trigger reload grid does not work for local data

### ISSUE THREAD

**Issue by Spurrya** [tonytomov/jqGrid#765]
I have to create and then clear columns. Instead, it should detect a change in the data and automatically update it or create a new trigger that checks if data has changed and forcefully refreshes the grid.

**Comment by Spurrya** [comment]
I am fine with fixing this issue myself but would prefer discussion first :)

**Comment by tonytomov** [comment]
Hello,

Could yo please let us know how you do this? Any code example will be fine.

Thank you.

Best Regards,
Tony

**Comment by tonytomov** [comment]
Hello,

I see you do not have close the issue. Could you please let me know if everthing is ok with this? 
I'm speak about our other discussion via e-mails.

Thank you.

**Comment by Spurrya** [comment]
Oh sorry, yes I'll close it.

Regards,
Spurrya Jaggi
