### ISSUE TITLE
Grid Request JSON breaks API webservice json serializer

### ISSUE THREAD

**Issue by kccarter76** [tonytomov/jqGrid#767]
when using web api and the grid is configured to post JSON to a web service. the filter property for the toolbar search wraps the json filters object with qoutes. This breaks the JSON and creates a bad request. taking the extra step to parseJSON will create a proper JSON object that will be deserialized by a web api service.

**Comment by tonytomov** [comment]
Hello,

Thank you for this note. I understand the problem and think that putting options for every particular case will do the grid like a mastodon with options. 

Fortunately we have enough events which can be used with success to solve this problem.
I speak about serializeGridData event which if defined can modify the posted data to the server.

You code can look like this:
```
$("#grid").jqGrid({
...
serializeGridData : function(postData) {
   if(this.p.search === true ) { // or better you can use postData._search === true
      postData.filters = $.jgrid.parse( postData.filters );
   }
   return postData;
}
...
});
```

The $.jgrid.parse function uses JSON.parse if it is found.

Please, let me know if this solves the problem.

Kind Regards,
Tony

**Comment by kccarter76** [comment]
yes, that code would address the issue. I have already chased down the
lines in question and implemented the parsing.

I have placed the following code in the serializer function that I use.
just in case the code is reverted.

function (data) {
                    var post = {};

                    for (var key in data) {
                        if (key === '_search') {
                            post['search'] = data[key];
                        } else if (key === 'filters' && typeof (data[key])
=== "string") {
                            post[key] = $.jgrid.parse(data[key]);
                        } else {
                            post[key] = data[key];
                        }
                    }

                    return $.toJSON(post);
                }

**Comment by tonytomov** [comment]
Yeahh,

Your code is much better. I just want to show you the way of solving the problem.
Can you please close the issue if you think that the problem is resolved.

Thank you.

Kind Regards,
Tony
