### ISSUE TITLE
jqgrid 5.0 celledit afterSubmitCell get a jquery error

### ISSUE THREAD

**Issue by visonforcoding** [tonytomov/jqGrid#770]
cellsubmit : 'remote',
         cellurl : '/admin/resume/cellEdit'
        afterSubmitCell:function(res, rowid, cellname, value, iRow, iCol){
                                //console.log(res);
                  }
when i add the afterSubmitCell event ,after i submit cellEdit i got a jquery error .
 as this code:
`TypeError: m is undefined
	

...fterSubmitCell.call(e,d,v.id,l,h,b,c)),m[0]===!0?(a(j).empty(),a(e).jqGrid("setC...`

**Comment by tonytomov** [comment]
Hello,

It seems to me you do not have consult the docs: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:cell_editing&s[]=aftersubmitcell

As for this event we have- **afterSubmitCell** - 

> applies only to a cell that is editable; this event Fires after the cell and other data is posted to the server Should return array of type [success(boolean),message] when return [true,””] all is ok and the cellcontent is saved [false,”Error message”] then a dialog appears with the “Error message” and the cell content is not saved. servereresponse is the response from the server. To use this we should use serverresponse.responseText to obtain the text message from the server.

Kind Regards

**Comment by visonforcoding** [comment]
thanks,but i just see this doc,then i add the code 'afterSubmitCell event' listen to the response from the server.Then i got a error,is there a demo about the afterSubmitCell use.

**Comment by tonytomov** [comment]
If you write about this event, then you should know about it. From where you know about this event if you read the doc for first time?

```
afterSubmitCell:function(res, rowid, cellname, value, iRow, iCol){ 
   var text_form_server = res.responseText;
   // depending on state from the server and using the text you can
   if(some_condition_based_on_text_form_server_is wrong) {
      return [false,"Error"];
   } else  {
      return [true,""]
   }
}


```

Hope this helps

**Comment by visonforcoding** [comment]
thanks,jqgird is very useful,thank you very much
