### ISSUE TITLE
colMenu filters and columns sub-menus postion is wrong

### ISSUE THREAD

**Issue by Krokador** [tonytomov/jqGrid#771]
Using the "colmenu with action" demo on this page http://www.guriddo.net/demo/guriddojs/, you can reproduce the issue easily by using the developer toolbar and adding a padding of 100px to the body of the iframe that contains the demo, then opening one of the column menus.

Since the sub-menu is positioned with the offset from the top of the document, the minute you have some content above the grid, position is thrown out of whack. The more content I have above the grid, the more it pushes the sub-menu down.

I'm using the 5.1.0 release version here, lines 3316 and 3321 determine the top position with the following code:
`top1 = $(this).parent().offset().top-40`

I think just basing the top position off of the .position().top would work, but I have yet to really test it out properly. Just thought I would put this out here in the mean time. My current "fix" is the following line:
`top1 = $(this).parent().position().top - 5;`

**Comment by tonytomov** [comment]
Hello,

Thank you very much for this investigation. I will provide tests too and will let you know if your fix is fine.

Best Regards,
Tony

**Comment by tonytomov** [comment]
Hello,

My quick test show me that the fix is fine. I have committed the fix here: https://github.com/tonytomov/jqGrid/commit/263652f7d150fb953fcde604b1d6cd111ac75ba0

I have make a new build. Please check the fixed code and if everything is fine, close the issue.

Once more again, Thank you.

Kind Regards

**Comment by Krokador** [comment]
Yep, all looks good!
