### ISSUE TITLE
Frozen columns are no longer visible in IE11

### ISSUE THREAD

**Issue by Krokador** [tonytomov/jqGrid#773]
Since we updated from version 5.0.1 to 5.1.0, the frozen columns were no longer visible in IE11 (the width of the frozen-div was set to 0 for some reason). I compared the styles in both versions and finally figured out the ui-jqgrid-htable had an extra style of "height: 100%" added to it in the most recent version. Removing that rule fixed the frozen columns. 

Going off of that, I found this line (3844) in the jqGrid.js file:
`if(isMSIE) { if(String(ts.p.height).toLowerCase() === "auto") { ts.p.height = "100%"; } }`

Commenting it out fixes my issue in IE11, and a quick test in emulation mode shows it working properly all the way back to IE8.

However, I am guessing there was a reason this was added, so I am not sure what to do with it.

**Comment by tonytomov** [comment]
Hello,

Thank you for the investigation. Could you please post or send me  a simple test case which show the problem?

Does this mean that you use frozen columns with height set to auto?

Thank you

**Comment by Krokador** [comment]
Hi,

I'm actually still trying to figure it out. Thought I had it, but I was actually not working on the right file, so that line is not helping after all. However I know it is something that sets the height to 100% somewhere, so it shouldn't be that hard to pinpoint.

It is hard to isolate our test case as our grid has a lot of customizations, but I can reproduce the same issue with the frozen column demo here: http://www.guriddo.net/demo/guriddojs/

(in IE11, the data is frozen but the header is not).

Thank you for the quick response. I will let you know if I manage to fix it.

**Comment by Krokador** [comment]
There we go. The culprit is at line 5220
`$(htbl).width(1).css("height","100%");`

if I comment out the height part, my header is fine. Tested all the way back to IE8 in emulation mode, as well as the latest versions of firefox and chrome.

The height part is clearly an addition to the most recent version, so I don't know if it serves a purpose that I am not aware of.

**Comment by tonytomov** [comment]
I have checked this part and it exists in 5.0.1

**Comment by Krokador** [comment]
Odd, the file I have of the 5.0.1 version (The date at the top of the file is 2015-10-30) doesn't have that part. Unless you mean the first line I thought was causing the issue, in which case I am truly sorry for the confusion). 

I just realized my line numbers might be off as my jscript editor tends to realign code as I go along and modify it.

Either way, that particular line, situated within the setFrozenColumns function is what was causing the header to not be frozen in IE in my case. Other browsers were working fine prior to the change. I hope that helps.

**Comment by tonytomov** [comment]
Hello,

Many thanks. I have found the code and the change the change from  5.0.1
```
$(htbl).width(1);
```
to 5.1.0
```
$(htbl).width(1).css("height","100%");
```

I will check what was the reason from this change

**Comment by tonytomov** [comment]
The reason to add this fix was that the frozen div height does not match the original and there was a 1 pixel difference. This can be seen when using bootstrap styling. I will try to analyze this deeper and will replay to this.

**Comment by tonytomov** [comment]
I have fixed the problem going back with the initial set only for IE browsers.
Please let us know if it is fine for you.

**Comment by tonytomov** [comment]
I will close the problem - it seems to be fixed.
