### ISSUE TITLE
Duplicate code in grouping grid source file

### ISSUE THREAD

**Issue by huang-x-h** [tonytomov/jqGrid#775]
Hi

There is something confuse with me.
See the grouping grid code, https://github.com/tonytomov/jqGrid/blob/master/js/grid.grouping.js#L185-L215

There are nothing different between this two blocks, why not just call the block and remove the `grp.showSummaryOnHide` condition? or am i misunderstand something?

**Comment by tonytomov** [comment]
Ohh,
Thanks. It must stay here from fixing some other bug. Thanks. I have removed it
