### ISSUE TITLE
Checkbox selection grid disabled problem

### ISSUE THREAD

**Issue by huang-x-h** [tonytomov/jqGrid#777]
Hi, tony

When we use checkbox selection grid, disabled the checkbox column.

So we hope when user click the checkbox column, it can not be checked

It works fine in chrome, but not is IE.

It maybe different browser has different behavior about a container contain a disabled element can be click

I write a example about checkbox disabled [JSBin](http://output.jsbin.com/hukozi/13)

So in the `grid.base.js` files https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L3733

`$(td).hasClass("cbox")` can change to `$(td).filter(":enabled").hasClass("cbox")`, check the checkbox is `disabled` or not

**Comment by tonytomov** [comment]
Hello,

Thank you. Just publish the fix.

Kind Regards,
Tony

**Comment by huang-x-h** [comment]
Ok, thanks.
