### ISSUE TITLE
column chooser multiple click on plus(+) icon create a duplicate entry

### ISSUE THREAD

**Issue by Anknit** [tonytomov/jqGrid#780]
Multiple click on plus(+) icon create a duplicate entry on Add column area.
Add all and remove all does not work more than once.

**Comment by tonytomov** [comment]
Hello,

More information and examples are highly appreciated.
With this type of description we can loss a lot of time in order eventually to reproduce the problem.

Which version is of jqGrid used? Which version of multiselect plugin is used? Which browser and etc. That are conditions which are very important.

I hope you understand what I mean.

Kind Regards,
Tony

**Comment by tonytomov** [comment]
Hello,

I will close the issue.
Please consider reopen the issue if the problem exists and you have a test case for it.

Kind REgards
