### ISSUE TITLE
Why use `&#160;` instead of ''

### ISSUE THREAD

**Issue by huang-x-h** [tonytomov/jqGrid#781]
Hi

See the code https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L1610-L1612

when the `cellValue` is `null` or empty string then return `&#160;`

HTML entities for escaping are this

    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#x27;',
    '`': '&#x60;'

So, why use `&#160;` instead of `''`, why not just return `''`?

**Comment by tonytomov** [comment]
Hello,

The reason for this was is the behavior of some browsers. Historically you can read this article:
https://www.cs.tut.fi/~jkorpela/HTML/emptycells.html

Kind Regards,

**Comment by huang-x-h** [comment]
@tonytomov Thanks a lot.
