### ISSUE TITLE
Problem in multiselect functionality (Bootsrap)

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#783]
Hello,
There is a problem in multiselect functionality. When a checkbox is checked, the respective row is not selected.  I noticed that this functionality breaks on commit  f90160b. 

Thanks

**Comment by tonytomov** [comment]
HEllo,

What are the other settings? Is only a multiselect options set to true or there are other related multiselect options.

Can you please put a simple test case? Is a celledit true or etc. Any additional information is welcome.

Kind Regards,
Tony

**Comment by yannniskargakis** [comment]
Hello,
I have set only one multiselect option to true. [Here] (https://github.com/tonytomov/jqGrid/files/250121/index.txt) is a simple test case (modified one of your own examples)

**Comment by tonytomov** [comment]
Thanks. 

I have found the problem. The fix will follow. I will let you know

**Comment by tonytomov** [comment]
Hello,

I have fixed the problem. Please let me know if it is ok.


Kind Regards,
Tony

**Comment by yannniskargakis** [comment]
It works! 
Thanks

**Comment by tonytomov** [comment]
I will close the issue.
Thank you for the feedback.

Kind Regards
