### ISSUE TITLE
Add new inline-editing parameter to allow auto-saving

### ISSUE THREAD

**Issue by meterlongcat** [tonytomov/jqGrid#785]
Good afternoon,

I'd like to propose an enhancement to the inline editing functionality. jqGrid already has an existing property called _restoreAfterSelect_, which is true by default. When true this causes row edits to be discarded when another row is selected. When false this leaves the row in edit mode. This functionality works great, but leaves no option for those that would like rows to be auto-saved when another row is selected. **Please note:** I'm aware of existing "solutions" to this, for example [this](http://stackoverflow.com/questions/11021992/jqgrid-not-saving-inline-row-edits).

I propose adding a new property called _saveAfterSelect_ to sit alongside the existing _restoreAfterSelect_. These values are mutually exclusive, e.g. if one is true the other must be false. Both can be false, but both can't be true. The code in grid.inlinedit.js needs to be extended as follows:

    if(o.restoreAfterSelect === true) {
        // this is all existing code, omitted for brevity
    }

    if(o.saveAfterSelect === true) {
        $($t).bind("jqGridBeforeSelectRow.inlineNav", function( event, id ) {
            if($t.p.savedRow.length > 0 && $t.p.inlineNav===true && ( id !== $t.p.selrow && $t.p.selrow !==null) ) {
                if($t.p.selrow === o.addParams.rowID ) {
                    $($t).jqGrid('delRowData', $t.p.selrow);
                } else {
                    $($t).jqGrid('saveRow', $t.p.selrow, o.editParams); // this is the only line different from the o.restoreAfterSelect logic
                }
                $($t).jqGrid('showAddEditButtons');
            }
        }
    }

Kind Regards,
Jan

**Comment by tonytomov** [comment]
I find your suggestion usefull and have added it. The code is shorted, but the logic remain.

Please let me know if it is ok for you and close the requierment.

Kind Regards,
Tony

**Comment by meterlongcat** [comment]
Thanks Tony, all looks good. Will close out now.

Cheers
