### ISSUE TITLE
Reload grid from database 

### ISSUE THREAD

**Issue by jgarcia99** [tonytomov/jqGrid#786]
I am trying to reload the grid on a callback but it keeps the same data from the original onload. Ajax after the post and after the get is being used.

```
///POST
function(data,jsonData,name) {
name = $('input##listName').val();
data = jQuery.jgrid.saveState("jqgrid");
	
///GET
$('##jqgrid').jqGrid('setGridParam', {
     data: response.LIST_DATA, dataType: 'jsonstring'
});
```

**Comment by tonytomov** [comment]
Hello,

I'm not sure that I understand the problem.
Could you please explain me again in simple words what you do - what you expect and actually what is happen.

Thank you.

Kind Regards,
Tony

**Comment by jgarcia99** [comment]
I fixed the problem it was a data issue thanks! But while your here having some styling issues with the Bootstrap version for the navGridPager it does not want to center correctly like the demo

**Comment by tonytomov** [comment]
Hello,

Can you please prepare a test case? 
I will close this, so please feel   free to open new issue

Thank you

Kind Regards,
Tony
