### ISSUE TITLE
Bug with cancelling addRow

### ISSUE THREAD

**Issue by meterlongcat** [tonytomov/jqGrid#787]
**Part 1:**
The inline nav functionality of jqGrid suppots the _beforeAddRow_ method, which the user can provide. If false is returned then the row creation doesn't happen (good). Unfortunately the add/edit buttons at the bottom remain greyed out, and the save/cancel buttons remain active. 

Saving is currently aborted via:
`if(!bfar) { return; }`

**Part 2:**
I want to do the same thing with _beforeEditRow_, where the same problem exists.

Kind Regards,
Jan

**Comment by tonytomov** [comment]
Hello,

I see the problems you describe and yes this is bug
The problem is that these methods return the grid instance and not true or false on adding/editing. Will try to resolve the issue.

**Comment by tonytomov** [comment]
Hello,

I have fixed the problem. Please test and close the issue if it is fixed.
Thank you for reporting

Best Regards,
Tony

**Comment by meterlongcat** [comment]
Hi Tony,

I just tested this and it's fixed, so will close out.

Thank you for actioning so quickly.

Kind Regards,
Jan
