### ISSUE TITLE
Update jqGrid from server

### ISSUE THREAD

**Issue by bravojohny91** [tonytomov/jqGrid#789]
We are using jgGrid and it works perfectly fine. Let me explain how the grid is setup, we are fetching json data from server, loadonce: true.

Now we want to update the grid every 20 seconds, so

```
setInterval(function () {
                $("#jqGrid").setGridParam({ datatype: 'json', page: 1 }).trigger('reloadGrid', [{ current: true }]);

            }, 20000);
```

This is working fine. Issue is that, it entirely refreshes the grid, we want to update the data which is changed. I mean if there is change in only one cell of a column, only that cell should be changed.

So this will have an impact like updating data from server real time, like NYSE indices

Any help is really appreciated

**Comment by tonytomov** [comment]
Hello,

jqGrid does not work the way you want to be. The data is cleared and replaced with the new one.

One possible solution for your problem is to use setRowData. Before this you will need to obtain the needed new fresh data from the sever and set it in grid. This will work for relative not big data.


Below is just idea (not tested)

````setInterval(function() {
$.ajax({
url: 'jqgrid_url_for_thata_page',
dataType: 'json',
succes : function(data, status, xhr) {
// suppose the data[i][id] is the id
for(var i=0; i < data.length; i++) {
$("#jqgrid").jqGrid('setRowData', data[i]['id'], data[id]);   
}
}
}, 20000)
````

Hope this helps

**Comment by bravojohny91** [comment]
@tonytomov  thanks for the quick reply. Really appreciate.
data[i][id] is the id, id of row?
How to get the id in jqgrid, 

My grid is like

```
<script type="text/javascript">
        $(function () {
            $("#list").jqGrid({
                url: '/Home/MyData/',
                datatype: "json",
                contentType: "application/json; charset-utf-8",
                mtype: 'GET',
                colNames: ['CP', 'CP1', 'Cp2', 'Cp3']
                colModel: [
                    { name: 'CP', index: 'CP', width: 55 },
                    { name: 'CP1', index: 'CP1', width: 90 },
                    { name: 'CP2', index: 'CP2', width: 100 }
    { name: 'Cp3', index: 'Cp3', width: 100 }
                ],
                rowNum: 5,
                rowList: [5, 10, 15],
                pager: '#pager',
                sortname: 'CP',
                viewrecords: true,
                sortorder: "asc",
                caption: "JSON Example"
                loadonce: true, autoencode: true
            });
            $("#list").jqGrid('navGrid', '#pager',
                { edit: false, add: false, del: false });

        });


    </script>
```

**Comment by tonytomov** [comment]
Which column in this grid act as id (the grid colModel property key:true). Suppose this is the first field Cp, then you will need data[i]['CP'] is the id of the grid.

Regards

**Comment by bravojohny91** [comment]
![datavalue](https://cloud.githubusercontent.com/assets/236996/15959621/3d56a320-2f19-11e6-9b34-3f6171978664.PNG)

Please check the values I am getting in 'data'

**Comment by tonytomov** [comment]
OK. 
Which value from cell array act as id in the grid - the cell values form index 0 to 7

**Comment by bravojohny91** [comment]
If I am getting you correct, this is '0'. Please check the screenshopt of the html the grid rendered

![gridval](https://cloud.githubusercontent.com/assets/236996/15960045/87d41926-2f1b-11e6-81f7-49f3cd3e2706.PNG)

**Comment by tonytomov** [comment]
Your  code in success function can look like this: (sorry no time to test)
```
sucess : function (data, status, xhr) {
   var mydata = data['rows'], len = mydata.length, i ;
   for ( i = 0; i< len; i++) {
      var row = mydata[i].cell;
      $("#gird").jqGrid('setRowData', row[0], { 'CP':row[0], 'CP1':row[1], 'CP2':row[2],....});
   }
}
```
Be a sure to make this object : 

{ 'CP':row[0], 'CP1':row[1], 'CP2':row[2],....}

equal  with the names of colModel

**Comment by bravojohny91** [comment]
@tonytomov  really superb. It works really well. Let me test with the sorting and search filters. Many Thanks
