### ISSUE TITLE
Key property in colModel not working correctly when retrieving data as an array of strings

### ISSUE THREAD

**Issue by mdprw** [tonytomov/jqGrid#800]
I’m using an array of strings as input data as I once saw in the jqGrid demos “Data Mapping”->”Data Optimization” to reduce the size of the response (it's no longer available).

**Example of json input:**
`{"d":{"page":1,"total":1,"records":100,"rows":[["13570","Some name 1","Australia"],["34233","Some name 2","Washington"]]}}; `

If I set **key:true** in colModel definition the id is not used to create the row. The id created corresponds to the number of the row.

This problem was discussed before:
[http://guriddo.net/?topic=strange-behaviour-after-updating-to-jqgrid-4-7-0](url)

And is referenced in this PR:
#669

**Comment by tonytomov** [comment]
Hello, 

When data is not in name value pair a id property in jsonReader/xmlReader should be set.
Usually this is a number which represent the position of the cell in rowData.

In your example when set

```jsonReader : {
...
id : 0
...
}
```

The id of these two rows will have the following id values 13570 and 34233.

Please let us know if this fixex the problem and close the issue.

**Comment by mdprw** [comment]
Hello Tony,

I'm currently using that configuration and it works fine, but in older versions it wasn't needed so I thought it was a bug.

Thanks!
