### ISSUE TITLE
Align headers on the right and sorting

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#801]
Hello,

I am using the method setLabel (jqGrid JavaScript) to align the header of a column to the right i.e:
`$("#myGrid").jqGrid('setLabel', 'name', '', {'text-align':'right'}); `
I have also set this column to be sortable (`sortable:true`)

The problem is that sorting arrows are still on the right side of the column header and as result are going out of the grid and are not appear to the grid.

Any solution?

Thanks

**Comment by tonytomov** [comment]
Thanks,
Will look into this.

**Comment by tonytomov** [comment]
Hello,

To be a honest currently I haven't find any resolution of the problem. Try with different margins  and paddings, but without success.

Maybe in this case the icons can be placed at left of the text, which means another  option. We see if this can be done without big problems.

Kind Regards,
Tony

**Comment by yannniskargakis** [comment]
Hello,
Thanks for your time.
I have already tried to add padding using the setLabel method on the header of the column without success too.
I think that putting the icons on the left is the most efficient solution.
Please inform me for a fix

**Comment by tonytomov** [comment]
Hello,

I have added a method setSortIcon https://github.com/tonytomov/jqGrid/commit/50f3452a6d9e385028acc64709b03e464d82f8c2 , which changes the position of the sort icon.

Please let me know if it is working as expected.

Kind Regards,
Tony

**Comment by yannniskargakis** [comment]
I am using jQuery UI.
I have performed a number of changes in the css in order to adapted in my needs,
but the problem of misalignment is appeared also in a clean css. 
[Here](https://github.com/tonytomov/jqGrid/files/361216/ex.txt) is one of your own examples (jqgridjs\edit_add_delete\dialogs) that i have modified, in screenshots you can see the problem with the misalignment

![capture](https://cloud.githubusercontent.com/assets/18188368/16799643/8e11a602-48fa-11e6-8021-8175013cbd5c.JPG)

![snap2](https://cloud.githubusercontent.com/assets/18188368/16799649/93d8d628-48fa-11e6-92a5-9a70453cad4c.JPG)

**Comment by tonytomov** [comment]
Hello,

I have simplified the code. : https://github.com/tonytomov/jqGrid/commit/d19d1b9b0d2bb2b38dc56c564d0978530e5fd2b6

The problem is the the element where the icons  reside  - they are inside the text,
Anyway, please test and let me know if it is fine.

Kind Regards
Tony

**Comment by tonytomov** [comment]
Hello,

Please reopen if this is not fixed for you
