### ISSUE TITLE
Could we initialize jQgrid with settings came from server? 

### ISSUE THREAD

**Issue by YozhEzhi** [tonytomov/jqGrid#804]
What I'd like to do is to get jQgrid settings from server. Like this:
```
$grid.jqGrid({
  url: url,
  styleUI: 'Bootstrap',
  datatype: 'json',
  colModel: parseSettingsFromServer(),
  loadonce: true,
  viewrecords: true,
  width: 1170,
  height: 480,
  rowNum: 30,
  pager: '#jqGridPager',
  onSelectRow: editRow,
});
```
What I've tried to do:
- loading settings data from [here](https://gist.github.com/YozhEzhi/699e4272b939775eb74e6cee4d5478ca);
- parse it like [here](http://stackoverflow.com/a/16214042);

It works. **But:** I couldn't now pass an function as `formatter: removeTag`.

How to deal with having settings that comes from server & custom events for jQgrid?

**Comment by tonytomov** [comment]
Hello,

This is a known problem with parsing json string which contain a function definition.
For this purpose you can either build your own JSON.parse/stringify functions wich correctly parses/ stringify function or use our created functions for this purpose in grid.uitils module - see jqGridUtils.stringify and jqGridUtils.parse functions here: https://github.com/tonytomov/jqGrid/blob/master/js/grid.utils.js

Kind Regards

**Comment by YozhEzhi** [comment]
Hello!
This code helped me:
Convert string to `colModel`:
```
/**
 * Convert raw string to JSON.
 * @link http://stackoverflow.com/a/16214042
 * @param rawString - string that should be parsed to an array;
 */
function stringToArray(rawString) {
  let newJson = rawString.replace(/([a-zA-Z0-9]+?):/g, '"$1":');
  newJson = newJson.replace(/'/g, '"');

  return JSON.parse(newJson);
}
```
Custom `removeTag` formatter:
```
  /**
   * Render html for Product removing.
   * Extend jQgrid formatter.
   * @link http://goo.gl/9xcr7q
   */
  $.extend($.fn.fmatter, {
    removeTag() {
      return `
        <div class="jqgrid-remove-icon glyphicon glyphicon-trash"></div>
      `;
    },
  });
```
