### ISSUE TITLE
when i use trigger("reloadGrid")  fun.  to clear selected row,but it look like not work 

### ISSUE THREAD

**Issue by DebugOfTheRoad** [tonytomov/jqGrid#805]
Use  adjacency mode init  grid when treegrid set true.  

what ever i do ....... i can't clear row selected status,  through i use trigger('reloadGrid") function.

**Comment by tonytomov** [comment]
Did you mean that you can not clear the selected row when you reload the grid?

**Comment by tonytomov** [comment]
The issue will be closed. If you think you can provide working example please reopen it.

Regards
