### ISSUE TITLE
why have`t success event for ajax in jqgrid?

### ISSUE THREAD

**Issue by 198907026139** [tonytomov/jqGrid#807]
I want do it like this:
`$("#xxx").jqGrid({
			url:"xxxx",
			datatype:"json",
			colNames:[],
			colModel:[]
success: function() {
			//TODO
			}
		});`

but the success event is NULL.

**Comment by tonytomov** [comment]
Hello,

You may need to use beforeProcessing event (which is called in ajax sucess) and return false to stop future processing

````
$("#xxx").jqGrid({
...
beforeProcessing : function( data, status, xhr) {
// do something
return false;
}
...
});
````
Regards
