### ISSUE TITLE
Group summaryPosition [header] offset columns by one when "Groupfield" is a select dropDown

### ISSUE THREAD

**Issue by boulepick** [tonytomov/jqGrid#808]
Good day,

pointing out a flaw on the group header summary offsetting the columns by one when the groupSummaryPos  is set to ['header'] and the group filed is a select dropdown. If the groupSummaryPos is set to [footer'], it works ok and do not offset the columns. see below. 
![jqgrid col offset](https://cloud.githubusercontent.com/assets/9008447/18012501/bf2f2c46-6b87-11e6-925f-5350ac0ad014.PNG)
,
and this is how it is showing when set to footer
![jqgrid col offset-good](https://cloud.githubusercontent.com/assets/9008447/18012947/bef230aa-6b89-11e6-97e1-143ffc444198.PNG)

it seems also when the groupField is a dropdown to messes up the grouping view text, Instead of showing the text of the grouping filed column it is showing the value of the dropdown when you set the hideFirstGroupCol to true,. see below 

![jqgrid - wrong value](https://cloud.githubusercontent.com/assets/9008447/18012561/1619bc74-6b88-11e6-8498-f02ce4a5c1b0.PNG)
this should be showing "**_Time 2_**" instead of "**_2_**" like in the previous image

**Comment by tonytomov** [comment]
Hello,

Thank you for the report.

Could you please send us a test case which demonstrates the problem?
You know that there are a lot of options, which may cause this, so if you provide a test case you will help us a lot.

Thank you.

Kind Regards,
Tony

**Comment by boulepick** [comment]
Hello Tony,

so the issue may not be with the select dropdown, it looks like it is happening when the first column is set to hidden : true.  see at http://fiddle.jshell.net/c01t5t22/21/ so any other column that is set to false does not seem to affect it, only the first column and this on any type of column. in this Example the first column is of type number. Also note that i'm using the CDN version 4.6 in the fiddle, could not find the latest 5.1.1 version.

**Comment by tonytomov** [comment]
Hello @boulepick ,

Thank you very much for the test cases and explanation. Seems to be a bug. Will get on this later today and let you know.

Kind Regards,
Tony

**Comment by tonytomov** [comment]
Confirm the bug. Have fixed it, but I need more tests.

Kind Regards

**Comment by tonytomov** [comment]
It is fixed.
