### ISSUE TITLE
select dropdown dataUrl:  editOptions dataType and Type options

### ISSUE THREAD

**Issue by boulepick** [tonytomov/jqGrid#810]
in line 6435 and 6436 of jquery.JqGrid ver 5.1.1 you have in the ajax options set as type : 'get'  and dataType : 'html'. Would it not be better to change the code to something like this
var ajaxType = options.type || 'get', ajaxDataType = options.dataType || 'html';

and at line 6435 and 6436 you would have 
.....
					$.ajax($.extend({
						url: $.isFunction(options.dataUrl) ? options.dataUrl.call($t, rowid, vl, String(options.name)) : options.dataUrl,
type : ajaxType,
dataType: ajaxDataType,
....

this way it would allow to set your preferred fetch method and datatype.

**Comment by tonytomov** [comment]
Hello,

There is a much easier way to do this using grid pasrameter ajaxSelectOptions
````
$("#grid").jqGrid({
...
ajaxSelectOptions : { 
   type:'POST',
   dataType: 'JSON'
}
...
});
````

Kind Regards,
Tony
