### ISSUE TITLE
jqGrid 5.1  getRowData return empty array

### ISSUE THREAD

**Issue by raindy29** [tonytomov/jqGrid#811]
I am try jqGrid 5.1, but found `getRowData`  method return empty

`var  Data = jQuery('#grid').jqGrid('getRowData');    `

**Comment by tonytomov** [comment]
Hello,

Please provide test case (code with test data). As you know it is not possible for us to simulate your conditions in order  reproduce the problem. 

Thank you

Kind Regards,
Tony

**Comment by hldgaofeng** [comment]
I got a problem: when real rows = 5, getRowData() return 4 rows.
when real rows = 1, getRowData() return 0 rows.

**Comment by tonytomov** [comment]
Hello,

Test case please. 

The fix is not accepted. Len describes the number of records available. Since java script begin from zero based array we decrement it.

````
while(j<len){
   if(getall) { ind = $t.rows[j]; }
   if( $(ind).hasClass('jqgrow') ) {
   ...
    }
}

````

One possible solution is that the new added row does not have a class jwgrow

**Comment by hldgaofeng** [comment]
example:
```
when $t.rows.length == 7,  // row index: 0 1 2 3 4 5 6 (total 7 rows)
then len = $t.rows.length -1; // len = 6
j =0;
while(j < len) {
    ... // j values: 0, 1, 2, 3, 4, 5,  lost( row index: 6) ??
   j++;
}
```

**Comment by xiongmeiqiang123** [comment]
I met the same problem with the newest jqgrid this morning.

**Comment by tonytomov** [comment]
Thanks all. Fixed : https://github.com/tonytomov/jqGrid/commit/77ce82fc017af0405a41efee503a2ff345fed280
