### ISSUE TITLE
Search，Filter，Position not align，see picture

### ISSUE THREAD

**Issue by shun634501730** [tonytomov/jqGrid#814]
see this picture：
![default](https://cloud.githubusercontent.com/assets/13994196/19380712/f600fcd0-922a-11e6-91c6-c6f79cabd3e1.png)

**Comment by sept08** [comment]
you can add a custom function of `afterShowSearch` that you can fix the style of form by jQuery after search form show. Read more on the [docs](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:singe_searching#options)
看你的截图是中文，我以前解决类似问题就是自定义afterShowSearch函数，在搜索表单显示后通过jQuery调整样式的，仅供参考。

**Comment by tonytomov** [comment]
Hello,

Could you please post a demo and describe the sequence of actions you do in order to think that this is a problem?
Thank you

Kind Regards,
Tony
