### ISSUE TITLE
shrinkToFit:true cause horizontal scrollBar in firefox v48.0

### ISSUE THREAD

**Issue by qhj1990** [tonytomov/jqGrid#815]
i use jgGrid v5.1.1,  shrinkToFit:true. it causes horizontal scroll bar in firefox V48.0,maybe 2px more than expected , but it works well in  chrome latest version

**Comment by tonytomov** [comment]
Hello,

Can you please provide a demo? Which CSS framework is used - Bootstrap or jQuery UI?
This is  important information.

Unfortunately all our Firefox browsers are updated to the v49.0

**Comment by qhj1990** [comment]
the css framework I used is bootstrap v3.3.4.
when the os is windows 10, it happens in the firefox v49.0(updated) and the old version of chrome,but not happen in the chrome v55.0.

‘shrinkToFit:true’ ，'vertical scrollbar'   is   a must

when the os is Mac os ,it doesn't happen neither chrome nor firefox 

the demo as follows
$("#grid-table").jqGrid({
	styleUI : 'Bootstrap',
            datatype: "json",
            url: '',
            mtype: 'get',
            postData:postData,
            height: size.height,
            width:size.width,
            altRows:true,
            shrinkToFit:true,
            colModel:colModel,
            viewsortcols: [true],
            rowNum:20,
            rowList:[20,50,100,200,500],
            pager : '#grid-pager',
            page: 1,
            pagerpos: 'center',
            viewsortcols: [true],
            jsonReader: {
	            root: "data.rows",
	            page:'data.page',
	            total:'data.total',
	            records: "data.records",
	            repeatitems: false,
	            id: "id"
	        },
            viewrecords:true,
            loadComplete:function(data){
            },
            gridComplete: function(){

    		},
           
        });

**Comment by tonytomov** [comment]
Hello,

Thank you for the test case.
Checked with your settings and it is ok for me on FireFox v49.0 / Chrome on Unix machines.
On windows 7 is ok too.

Will try later on Windows 10. Hope that this is a problem in FireFox.

Kind Regards,
Tony

**Comment by qhj1990** [comment]
it is also ok for me on Windows 8 too,Maybe it only happens in firefox and old version of chrome on Windows 10 when there is a vertical scrollbar

**Comment by qhj1990** [comment]
it is ok in microsoft Edge on Windows 10, it is not ok in IE11 on windows 10

**Comment by tonytomov** [comment]
Hello,

Thank you for information. In IE11 on Win 10 this will maybe not be fixed, while in FireFox it can be fixed. The issu will stay opened when a new release on FireFox is on.

Regards
