### ISSUE TITLE
multiselect checkbox behavior

### ISSUE THREAD

**Issue by gitfengjing** [tonytomov/jqGrid#816]
Dear ALL,
There have two problems that I can‘t deal which about Multiselect and Multikey:
    1、When Multikey is "ctlkey",and unselect using checkbox doesn't work,how to fix this bug?
    2、When row has selected, that I turn page, and the primary selected rows turn to unselected.
    Who can tell me how to deal with it,if you can show the code?
    Best regards!

**Comment by tonytomov** [comment]
Hello,

Which version is used?
1. This work for me as expected
2. I can't understand what you mean with this.

Please, try to use the latest stable version.

Kind Regards,
Tony

**Comment by gitfengjing** [comment]
I have used the version is jqGrid 4.6.0("jquery.jqGrid.src.js")，and it is work OK.
but I meet a new problem：my column name is chinese,when it transfer "sidx" by ajax that I get wrong words.If you can tell me how to add function escape() before "get/post" jqGrid' self parms ?It need to edit the file "jquery.jqGrid.src.js" or "jquery.jqGrid.min.js".

**Comment by tonytomov** [comment]
This version is too old and is no more supported. Please use the latest one and if the problem persist, please reopen it.
