### ISSUE TITLE
it can disable other checkbox when i click the outside of one checkbox(the td this checkbox in)

### ISSUE THREAD

**Issue by saipanan** [tonytomov/jqGrid#817]
it work well when i click the checkbox but it can disable other checkbox when i click the outside of one checkbox(the td this checkbox in)

**Comment by tonytomov** [comment]
Hello,

I it difficult for me to understand what you mean.
Could you please prepare a demo and steps to reproduce the problem?

Thank you.

Kind Regards,

**Comment by tonytomov** [comment]
I will close the issue. If you prepare a test case, please feel free to reopen it
