### ISSUE TITLE
jqGrid 5.1.0 jqgrid.min.js file  issue

### ISSUE THREAD

**Issue by bejjm** [tonytomov/jqGrid#818]
Hi,
I want to download jqGrid 5.1.0 version.
Where to download ？
I downloaded the 5.1.0 version of the GitHub, but the jqgrid.min.js file version is 5.0.2, you are wrong？？？？

**Comment by tonytomov** [comment]
Hello,

First of all, please do not post your problem in all possible places at our organization. We see the problem too if it is written once. Note that writing this post everywhere will consume time and you answer will be delayed. Hope you understand what I mean.

Now to the problem. Could you please tell me the link from where you download this version, which is mean to be 5.1, but it is not. 

Thank you.

Regards

**Comment by bejjm** [comment]
Ok, I got it.
my download link  :  https://github.com/tonytomov/jqGrid/releases/tag/v5.1.0

**Comment by tonytomov** [comment]
Thanks for the feedback.
Usually if you open the issue and if it is resolved it is a good idea to close it.

Thank you

Regards,

**Comment by bejjm** [comment]
Where can download  jqGrid 5.1.0 version in guriddo.net  ? 
I can not find in guriddo.net.
Thank you
