### ISSUE TITLE
Based on ASP framework,and how I export jqGrid data to EXCEL file(.xls)?

### ISSUE THREAD

**Issue by gitfengjing** [tonytomov/jqGrid#823]
Dear ALL,
     My project is based on ASP framework,and use javascript and vbScript,that how I export excel file(.xls) easy?Who can give me demo or code that teach me how to use it?
My code is this, but it dose not work:
`		
$("#jqGrid").jqGrid('navGrid', '#jqGridPager').jqGrid( //#pager
            'navButtonAdd', "#jqGridPager", {
            caption: "Excel export",
            buttonicon: "ui-icon-arrowthickstop-1-s",
            onClickButton: function(){$("#jqGrid").excelExport();},
            position: "first",
            title: "Excel export",
            cursor: "pointer",
			exportfile: "Report.xls"
        });
`
		
Best Regards!

**Comment by tonytomov** [comment]
See the last release here:  http://guriddo.net/?p=125685

**Comment by tonytomov** [comment]
Will close it.
