### ISSUE TITLE
Easy way to apply fix for issues #460 and #599

### ISSUE THREAD

**Issue by ahummel25** [tonytomov/jqGrid#826]
I'm making small bug fixes to an existing app that uses jqGrid 4.3.0. I know the grid cell height issue mentioned in issues 460 and 599 have been fixed in the latest release of Guriddo jqGrid (specifically in the setFrozenColumns function), but is there an easy way to apply this fix if you're already on an older version of jqGrid? Copying over the newest version of the function breaks other existing code in that function.

Any suggestions?

**Comment by ahummel25** [comment]
`setFrozenColumns : function () {
		return this.each(function() {
			if ( !this.grid ) {return;}
			var offset = 0;
		    if (!$.browser.mozilla)
		    {
				offset =2;
		    }
			var $t = this, cm = $t.p.colModel,i=0, len = cm.length, maxfrozen = -1, frozen= false;
			// TODO treeGrid and grouping  Support
			if($t.p.subGrid == true || $t.p.treeGrid === true || $t.p.cellEdit == true || $t.p.sortable || $t.p.scroll || $t.p.grouping )
			{
				return;
			}
			if($t.p.rownumbers) { i++; }
			if($t.p.multiselect) { i++; }
			
			// get the max index of frozen col
			while(i<len)
			{
				// from left, no breaking frozen
				if(cm[i].frozen === true)
				{
					frozen = true;
					maxfrozen = i;
				} else {
					break;
				}
				i++;
			}
			if( maxfrozen>=0 && frozen) {
				var top = $t.p.caption ? $($t.grid.cDiv).outerHeight() : 0,
				hth = $(".ui-jqgrid-htable","#gview_"+$.jgrid.jqID($t.p.id)).height();	
				if($.browser.msie) {
					top -=1;
				}
				$t.p.orgEvents = {};
				//headers
				if($t.p.toppager) {
					top = top + $($t.grid.topDiv).outerHeight();
				}
				if($t.p.toolbar[0] == true) {
					if($t.p.toolbar[1] != "bottom") {
						top = top + $($t.grid.uDiv).outerHeight();
					}
				}
				$t.grid.fbDiv = $('<div style="position:absolute;left:0px;top:'+(parseInt(top,10)+parseInt(hth,10) + 1)+'px;overflow-y:hidden" class="frozen-bdiv ui-jqgrid-bdiv"></div>');			
				// data stuff
				//TODO support for setRowData
				$("#gview_"+$.jgrid.jqID($t.p.id)).append($t.grid.fbDiv);
				jQuery($t.grid.bDiv).scroll(function () {
					jQuery($t.grid.fbDiv).scrollTop(jQuery(this).scrollTop());
				});
				if ($.isFunction($t.p._complete)) {
					$t.p.orgEvents.complete = $t.p._complete;
				} else {
					$t.p.orgEvents.complete = null;
				}
				if($t.p.hoverrows === true) {
					$("#"+$.jgrid.jqID($t.p.id)).unbind('mouseover').unbind('mouseout');
				}
				$t.p._complete = function() {
					$("#"+$.jgrid.jqID($t.p.id)+"_frozen").remove();
					jQuery($t.grid.fbDiv).height( jQuery($t.grid.bDiv).height()-16);
					var btbl = $("#"+$.jgrid.jqID($t.p.id)).clone(true);
					$("tr",btbl).each(function(){
						$("td:gt("+maxfrozen+")",this).remove();
					});

					$(btbl).width(1).attr("id",$.jgrid.jqID($t.p.id)+"_frozen");
					$($t.grid.fbDiv).append(btbl);
					if($t.p.hoverrows === true) {
						$("tr.jqgrow", btbl).hover(
							function(){ $(this).addClass("ui-state-hover"); $("#"+$.jgrid.jqID(this.id), "#"+$.jgrid.jqID($t.p.id)).addClass("ui-state-hover "); },
							function(){ $(this).removeClass("ui-state-hover"); $("#"+$.jgrid.jqID(this.id), "#"+$.jgrid.jqID($t.p.id)).removeClass("ui-state-hover"); }
						);
						$("tr.jqgrow", "#"+$.jgrid.jqID($t.p.id)).hover(
							function(){ $(this).addClass("ui-state-hover"); $("#"+$.jgrid.jqID(this.id), "#"+$.jgrid.jqID($t.p.id)+"_frozen").addClass("ui-state-hover");},
							function(){ $(this).removeClass("ui-state-hover"); $("#"+$.jgrid.jqID(this.id), "#"+$.jgrid.jqID($t.p.id)+"_frozen").removeClass("ui-state-hover"); }
						);
					}
					$("#"+$t.p.id+"_frozen tr.jqgrow").each(function() {
						$(this).height(( $('#'+$t.p.id+' tr[altid='+$(this).attr('altid')+']').height()+offset));
					});
					
					btbl=null;
					if($.isFunction($t.p.orgEvents.complete)) {
						$t.p.orgEvents.complete.call($t);
					}
					return true;
				};
				$t.p.frozenColumns = true;
			}
		});
	}`

**Comment by tonytomov** [comment]
Hello,

Unfortunately no. You use a very old version.
One possible resolution is to see the way the problem is resolved and add similar code to the appropriate module, but personally I think you should upgrade to the last version.

Kind Regards,
Tony
