### ISSUE TITLE
Problem with not unique filter input id per several grids on the page

### ISSUE THREAD

**Issue by popovsergiy** [tonytomov/jqGrid#827]
Hello,
I have complicated grid structure on my project where one column model is using in different grids on page. Everything is working correctly until I try bind `datepicker` plugin to filter toolbar input. There I have problem with error `TypeError: o is undefined` which mean that I have not unique  input id on page ([more detailed](http://stackoverflow.com/a/20528620/1335142))

For example I instantiate two grids with same column *cart_dateCreate*. This create two filter toolbar inputs with same id `gs_cart_dateCreate`
```
var grid1 = $('#grid1').jqGrid({
	// ...
	colModel: [{
		name: "cart_dateCreate",
		index: "cart_dateCreate",
		label: "Order date",
		width: "2",
		hidden: false,
		sortable: true,
		search: true,
		searchoptions: {
			dataInit: function (elm) {
				$(elm).addClass('datepicker').change(function() {
					grid1[0].triggerToolbar();
				});
			},
		}
	}]
});

var grid2 = $('#grid2').jqGrid({
	// ...
	colModel: [{
		name: "cart_dateCreate",
		index: "cart_dateCreate",
		label: "Order date",
		width: "2",
		hidden: false,
		sortable: true,
		search: true,
		searchoptions: {
			dataInit: function (elm) {
				$(elm).addClass('datepicker').change(function() {
					grid2[0].triggerToolbar();
				});
			},
		}
	}]
});
```
As a proposal can add grid identifier to input to ensure uniqueness.

**Comment by tonytomov** [comment]
Hello,

This is a old problem with a jqGrid. Fortunately we have resolved it adding a idPrefix parameter in the grid options. This way you have unique id not only in the filter toolbar, but in the grid id. In your configuration do:
````
var grid1 = $('#grid1').jqGrid({
....
idPrefix: 'grid1',
....
});

var grid2 = $('#grid2').jqGrid({
...
idPrefix : 'grid2',
...
});
````
or what you want for the prefix name.

Please let me know if this issue is resolved and if it is, close it

Thank you.

Kind Regards,
Tony

**Comment by popovsergiy** [comment]
Thank you, that's what I was looking for! You can close.

**Comment by tonytomov** [comment]
Ok. I will close it
