### ISSUE TITLE
An Issue about loadBeforeSend and paging.

### ISSUE THREAD

**Issue by renyd** [tonytomov/jqGrid#829]
I want do a filter for request. When page no > 10 then rejected the request.But hava a question with follow code.When I clicked last page button (page no = 20) will rejected the request, but the paging event is already fire.So when I clicked the last page button again JQGrid do noting.... Some other way?
`jQuery.extend(jQuery.jgrid.defaults, {
    loadBeforeSend: function () {
        var postData = $(this).getGridParam('postData');
        if (postData && postData["page.pageNo"] && postData["page.pageNo"] > 10) {
            swal("Not allowed!");
            return false;
        } else {
            return true;
        }
    }}`

**Comment by tonytomov** [comment]
Hello,

I think it is a better to control this at server - at server you already have this information - if the number of pages is > 10 then you should return empty or what you want request.

If you can not do this you can analyze if you are in search mode - this can be achieved if you analyze the grid parameter search: true which is set to true if perform searching and beforeProcessing event : http://www.trirand.com/jqgridwiki/doku.php?id=wiki:events&s[]=beforeprocessing.

the pseudo code in before processing can be:

..jqGrid({
... 
beforeProcessing : (data, status xhr) {
   if( this.p.search ) { // if we are in search mode
       // if the number of pages from data parameter are > 10 return false
   }
   //return true;
}

**Comment by tonytomov** [comment]
Sorry - it seems I do not read read carefully.

This is not a problem in loadBeforeSend, but a way you use it.
Check in loadBreforeSend if you are in search mode as of previous example and then you will have the desired result.

Regards,
Tony

**Comment by renyd** [comment]
Thanks  for your answer!
The control at server is already exist. 
Finally , I add a onpaging with the grid like this:
`  onPaging: function (pgButton) {
        var lastPage = $(this).getGridParam("lastpage");
        var page = 1;
        var str = pgButton.substring(0, 4);
        if (str == 'user') {
            var pager = $(this).getGridParam('pager');
            page = $("input.ui-pg-input", pager).val();
            if (page > lastPage) {
                return "stop";
            }
        } else if (str == "last") {
            page = lastPage
        } else if (str == "next") {
            page = $(this).getGridParam('page') + 1;
        }
        if (page > 100) {
            return "stop";
        }
    }`
I am poor at English.Thanks for your patience.

**Comment by KiranVH** [comment]
Suppose in the above onPaging event, if I want to set the page to the last page of the grid how can I do that?

**Comment by tonytomov** [comment]
You can do it like this:

```js
onPaging: function (pgButton) {
   this.p.page = $(this).jqGrid('getGridParam',"lastpage");
   $(this).trigger('reloadGrid');
   return 'stop'
}
```

Regards
Tony

**Comment by KiranVH** [comment]
Thank you very much.It worked
