### ISSUE TITLE
constructTr function not properly escaping attributes

### ISSUE THREAD

**Issue by Lukenickerson** [tonytomov/jqGrid#830]
The [function `constructTr`](https://github.com/tonytomov/jqGrid/blob/d04ecb26911966b4b7af2f33d728188c64c6d039/js/grid.base.js#L1762) creates a string of HTML made with potentially untrusted data without properly escaping the attribute strings as per [OWASP rule 2](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.232_-_Attribute_Escape_Before_Inserting_Untrusted_Data_into_HTML_Common_Attributes), which causes a XSS vulnerability.

You can setup a grid so that it gets data from an API that contains bad/XSS values (for example `"><script>alert('xss')</script>`). Inside `addJSONData` the bad values will be p[ropagated to `idr` via `getAccessor`](https://github.com/tonytomov/jqGrid/blob/d04ecb26911966b4b7af2f33d728188c64c6d039/js/grid.base.js#L2046), and then will be sent to `constructTr` which [builds the vulnerable HTML string](https://github.com/tonytomov/jqGrid/blob/d04ecb26911966b4b7af2f33d728188c64c6d039/js/grid.base.js#L1796). That HTML is assigned to `rowData`, and eventually [appended to the DOM](https://github.com/tonytomov/jqGrid/blob/d04ecb26911966b4b7af2f33d728188c64c6d039/js/grid.base.js#L2130), which the browser runs. 

There are likely other flaws like this, so to be extra safe I would recommend that all functions that construct HTML strings should be properly escaping the values that are used for attributes.

**Comment by tonytomov** [comment]
Hello,

You can use autoencode grid option which do this encoding: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:options&s[]=autoencode

This way any data coming from the server will be encoded. 

Regards,
Tony
