### ISSUE TITLE
the problem of configing colmenu

### ISSUE THREAD

**Issue by quoniammm** [tonytomov/jqGrid#833]
this is my version of jqgrid.js
```
/* 
 * jqGrid  5.1.1  
 * Copyright (c) 2008, Tony Tomov, tony@trirand.com 
 *  License: http://guriddo.net/?page_id=103334 
 *
 * Modules: grid.base.js; jquery.fmatter.js; grid.common.js; grid.formedit.js; grid.filter.js; grid.inlinedit.js; grid.celledit.js; jqModal.js; jqDnR.js; grid.subgrid.js; grid.grouping.js; grid.treegrid.js; grid.pivot.js; grid.import.js; grid.utils.js; grid.jqueryui.js; jquery.sortable.js;
 */
```

i think colmenu is very cool, so i use it in 
```javascript
$('#jqGrid').jqGrid({
...
colmenu: true,
...
})
```
But when i want to config it, i search it in [jqgrid wiki](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:methods&s[]=getrowdata).I can not find a API to config it.

So I see the source code, I find a way to config it.
```javascript
j = $.extend({ sorting: !0, columns: !0, filtering: !0, seraching: !0, grouping: !0, freeze: !0 }, i.coloptions) //source code
j = $.extend({ sorting: !0, columns: !0, filtering: 0, seraching: 0, grouping: 0, freeze: 0 }, i.coloptions) //the change
```

But it is not a good way.is this a bug? do i miss someting else,Is there a API  that I can config it?
Please help me.Thank you very much

**Comment by tonytomov** [comment]
Hello,

Sorry it is not documented, hope that the new docs will to be done finally this year.

I think it is better to search not in the minified file, but in the source file in case you want to investigate certain feature.
Here are some description.

The gobal grid option **colMenu** enables or disables this feature. 

Additionally in colModel you can enable/disable the menu for certain column with the option **colmenu** which can be true or false. Again with this you can define which actions to appear in the colmenu for that column. It is done with **coloptions**  object which default values are:
```js
...
{sorting:true, columns: true, filtering: true, seraching:true, grouping:true, freeze : true}
...

If you have any other questions please let me know. Here is a demo: http://www.guriddo.net/demo/guriddojs/functionality/column_menu/index.html#/

Regards
Tony

**Comment by quoniammm** [comment]
@tonytomov thank you very much, if i have other questions, i will tell you.I wish the  jqgrid can be better than better.
