### ISSUE TITLE
In jqgrid 5.1.0 , While searching date alone matched in datetime , time mismatched

### ISSUE THREAD

**Issue by NeelaveniT** [tonytomov/jqGrid#835]
Hi ,
  I am using grid 5.1.0 , I tried to search the pattern using datetime ,while giving date it matched properly.
  While giving time with date it didn't matched.

  Below I have attached the issue 

![datetime](https://cloud.githubusercontent.com/assets/22112236/22236863/5cdba2e0-e22e-11e6-938f-34c89c55861c.png)
![date_matched](https://cloud.githubusercontent.com/assets/22112236/22236872/66233f3e-e22e-11e6-98ea-60e5846e04cb.png)
![datetime_not_matched](https://cloud.githubusercontent.com/assets/22112236/22236878/6a99b8d6-e22e-11e6-84bb-07f60ca09bc3.png)

  Code in view :                
  {
                      label: "Start Time",
                      name: 'start_time',
                      formatter:'date',
                      formatoptions:{
                        srcformat: 'ISO8601Long',
                        newformat: 'Y-m-d H:i:s O'
                      },
                      //formatter: 'date',
                      width: 170,
                 },
                 {
                      label : "End Time",
                      name: 'end_time',
                      formatter:'date',
                     formatoptions:{
                       srcformat: 'Y-m-d H:i:s O',
                       newformat: 'Y-m-d H:i:s O'
                     },

Kindly help me,to resolve this issue.
I wish to match the search pattern both datetime.

**Comment by tonytomov** [comment]
Hello,

Could you please post a full test case with data?

Thank you.

**Comment by NeelaveniT** [comment]
My view code : 
<html lang="en">
<head>
</head>
<h3>Reports</h3>
<body>
    <div id="container" class="my_container"></div>
    <input id="show" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" value="Show" type="button" align="right">

<div>
    <table id="jqGrid">
    </table>
    <div id="jqGridPager"></div>
</div>
<script type="text/javascript">

jQuery("#show").click(function(){
    var parentsel = jQuery('#jqGrid').jqGrid('getGridParam','selrow');
    var subsel = jQuery('#jqGrid_'+parentsel+'_t').jqGrid('getGridParam','selrow');
    var capname = jQuery('#jqGrid_'+parentsel+'_t').jqGrid('getCell', subsel, 1);
    var capid = jQuery('#jqGrid_'+parentsel+'_t').jqGrid('getCell', subsel, 2);

        //console.log("subgrid id:"+subsel);
        //console.log("parent grid id:"+parentsel);
        //console.log("cap  id:"+capid);
        if( subsel ){
                // window.location = 'show?id=' + parentsel+ '&sid='+subsel ;
                document.getElementById("container").style.width=parseInt($(window).width());
                //jQuery('#jqGrid').trigger('reloadGrid');
                $("#container").load("show.html?id="+ parentsel+'&sid='+subsel+'&capid='+capid+'&name='+capname);
        }
        else {
                        alert("please select row");
        }
        return false;
});
        function my_close(){
                $("#container").html(" ");
        }

        var DataGrid = $('#jqGrid');

         //sets the grid size initially
         //DataGrid.jqGrid('setGridWidth', parseInt($(window).width()) - 10);
        //-- $(window).load(function () {
        //--       DataGrid.jqGrid('setGridWidth', parseInt($(window).width()) - 10);
        //-- });
         //handles the grid resize on window resize
         $(window).resize(function () {
               DataGrid.jqGrid('setGridWidth', parseInt($(window).width()) - 10);
         });

        $(document).ready(function () {
            $("#jqGrid").jqGrid({
                url: 'index',
                mtype: "GET",
                datatype: "json",
                page: 1,
                //colMenu : true, // display menu bar in grid
                rowList:[10,20,30,50,100,"1000:All"],
                loadtext:"Loading CAP Reports...",
                sortname: "id",  // sorting field in grid
                sortorder:"asc", // grid sorting order
                subGrid: true,
                autowidth: true,
                colModel: [
                 {   label : "ID",
                      name: 'id',
                      key: true,
                      width: 95,
                 },
                 {
                      label: "Status",
                      name: 'status',
                      width: 120,
                 },                 {
                      label: "Call Type",
                      name: 'call_type',
                      width: 150,
                 },
                 {
                      label: "Start Time",
                      name: 'start_time',
                      formatter:'date',
                      formatoptions:{
                        srcformat: 'ISO8601Long',
                        newformat: 'Y-m-d H:i:s'
                      },
                      //formatter: 'date',
                      width: 170,
                 },
                 {
                      label : "End Time",
                      name: 'end_time',
                      formatter:'date',
                     formatoptions:{
                       srcformat: 'Y-m-d H:i:s O',
                       newformat: 'Y-m-d H:i:s O'
                     },
                      //formatter:'showlink',
                      //formatoptions:{baseLinkUrl:'edit', addParam: '&action=edit', idName:'parent_id'},
                      width: 170,
                 },
                 {
                        label: "MSC Address",
                        name: 'location',
                         width: 130
                 },
                 {
                        label: "Called Number",
                        name: 'called_number',
                         width: 130
                 },
                 {
                        label: "Calling Number",
                        name: 'calling_number',
                         width: 130
                 },
                 ],
               loadonce: false,
               viewrecords: true,
               height: 350,
               rowNum: 10,
               pager: "#jqGridPager",
               caption: "Reports",
               jsonReader: {
                    root: "rows",
                    page: "page",
                    total: "total",
                    records:"records",
                    cell: "",
                    id: "id"
                },
        onSelectRow: function (rowId) {
            //$("#jqGrid").jqGrid ('toggleSubGridRow', rowId);
            $("#jqGrid").jqGrid ('expandSubGridRow', rowId);
        },
        subGridRowExpanded: function (subgridDivId, rowId) {
                // subgridDivId = Jqgrid_rowId
                // rowId = parent table row id
                // pureRowId = parent table row id
            var mainGridPrefix = "s_";
            var $pid =rowId;
            var $subgrid = $("<table id='" + subgridDivId + "_t'></table>"),
                pureRowId = $.jgrid.stripPref(mainGridPrefix, rowId),
                subgrids = $(this).jqGrid("getGridParam", "userData");

            $subgrid.appendTo("#" + $.jgrid.jqID(subgridDivId));
            $subgrid.jqGrid({
                datatype: "json",
                url: "cap",
                loadtext:"Loading CAP messages...",
                colNames: ["R","CAP Message","ID","STATUS"],

                colModel: [
                {
                   name: "ref",
                   index: "ref",
                   width: 20,
                },
                {
          name: "name",
          index: "name"
        },
                {
          name: "cap_id",
          index: "cap_id"
                },
                {
          name: "status",
          index: "status"
        }],
                sortname: pureRowId,
                sorttype: "asc",
                height: "100%",
                rowNum: 10,
                onSelectRow: function(id){
                        //console.log("sub grid id:"+id);
                        //console.log("parent grid id:"+$pid);
                         if($pid){
                                var row = document.getElementById($pid);
                                //console.log("row:"+row);
                                //   var oCells = oTable.rows.item(i).cells;
                                row.style.color="red";
                                row.setAttribute("aria-selected", "true");
                                jQuery("#jqGrid").setSelection($pid, true);
                                //alert("parent row id:"+$pid)
                        }
                },
            });
        }        }).navGrid('#jqGridPager',{excel:true,add: false,edit: false,view: false, del:false,search:false});

        // activate the toolbar searching
        $('#jqGrid').jqGrid('filterToolbar');
        // add export button in navigator
        $('#jqGrid').jqGrid('navButtonAdd','#jqGridPager',{
                caption:"Export",
                onClickButton : function () {
                //jQuery("#jqGrid").jqGrid('jqGridExport', );
                        $("#jqGrid").jqGridExport({
                                exptype: "jsonstring"
                        });
                        //---jQuery("#jqGrid").jqGrid('excelExport',{url:"/users/index",exptype:"remote"});
                       jQuery("#jqGrid").excelExport({url:"/report/export",exptype: "remote"});
                }
        });
});
    </script>
</body>
</html>

Controller Code  for index: 
  def index
    # Render the html or json based on request
    respond_to do |format|
      # Render the HTML page for drawing listview
      format.html

      # Render the JSON page loading listview data
      format.json {

        @conditions, @values, records = [], [], []
        # get details if it have fillters
        order = "#{params[:sidx]} #{params[:sord]}" if params[:sidx]
        if params[:_search] == "true"

        filters = {
            "id"             => "id::text          ILIKE '%'||?||'%'",
            :status          => "status::text      ILIKE '%'||?||'%'",
            :call_type       => "call_type         ILIKE '%'||?||'%'",
            :start_time      => "start_time::text       ILIKE '%'||?||'%'",
            :end_time        => "end_time::text    ILIKE '%'||?||'%'",
            :location        => "location::text    ILIKE '%'||?||'%'",
            :called_number   => "called_number::text   ILIKE '%'||?||'%'",
            :calling_number  => "calling_number::text   ILIKE '%'||?||'%'",
        }
        #@conditions=Array.new
        #@values=Array.new
        @conditions << "enterprise_id"+"::text ILIKE '%"+session[:user_eid].to_s+"%'" if session[:user_eid]
        filters.each do |field,cond|
                if cond.to_s =~ /\?/
                   # Conditions which requires arguments
                   if params[:_search] == "true" and params[field]
                     @conditions << cond
                     @values << params[field]
                   end
                else
                   # Conditions with no arguments
                   @conditions << cond
                end
        end        @conditions = @conditions.join(" AND ")
                # @recent_report=RecentReport.where(@conditions,*@values).order(order)
                 @report=Report.where(@conditions,*@values).order(order).paginate(:page => params[:page], :per_page => params[:rows])
        else

        if session[:user_eid]
        @conditions << "(enterprise_id = ?)"
        @values << "#{session[:user_eid]}"

        @conditions = @conditions.join(" AND ")
        @report=Report.where(@conditions,*@values).order(order).paginate(:page => params[:page], :per_page => params[:rows])
                else
                        @report=Report.order(order).paginate(:page => params[:page], :per_page => params[:rows])
                end
        end

        page=(@report.total_entries.to_f / params[:rows].to_i).ceil
        render :json => {"records":"#{@report.total_entries}","page":params[:page],"total":page,"rows":@report.as_json}

      }
    end
  end   # end for index function


Data on database : 
camel=# select * from reports;
 id |    status    | call_type | camel_message_id | enterprise_id |        start_time         |             end_time          
   |   location   | called_number | calling_number |            created_at            |            updated_at            
----+--------------+-----------+------------------+---------------+---------------------------+-------------------------------
---+--------------+---------------+----------------+----------------------------------+----------------------------------
  2 | DIALING      | OUTGOING  |           161960 |               | 2015-05-05 16:14:25+05:30 |                               
   | 919814047278 | 53500         | 919855544246   | 2017-01-19 15:21:58.414715+05:30 | 2017-01-19 15:21:58.414715+05:30
  3 | DIALING      | OUTGOING  |           161961 |               | 2015-07-10 16:59:08+05:30 |                               
   | 919092004000 | 919962219488  | 918680052960   | 2017-01-19 15:27:14.011266+05:30 | 2017-01-19 15:27:14.011266+05:30
  4 | DISCONNECTED | OUTGOING  |           161962 |               | 2015-07-10 18:33:19+05:30 | 2017-01-19 15:35:20.769085+05:
30 | 919092004000 | 919962219488  | 918680052960   | 2017-01-19 15:29:14.557619+05:30 | 2017-01-19 15:35:20.770068+05:30
  5 | DISCONNECTED | OUTGOING  |           161963 |               | 2015-07-10 18:19:13+05:30 | 2017-01-19 15:38:22.816556+05:
30 | 919092004000 | 919962219488  | 918680052960   | 2017-01-19 15:36:21.143996+05:30 | 2017-01-19 15:38:22.817739+05:30
  6 | DISCONNECTED | OUTGOING  |           161964 |               | 2016-04-25 07:24:45+05:30 | 2017-01-19 15:46:04.24334+05:3
0  | 919702000506 | 9840042792    | 8680052951     | 2017-01-19 15:45:38.256078+05:30 | 2017-01-19 15:46:04.244194+05:30
  1 | DIALING      | OUTGOING  |           161959 |               | 2016-02-19 10:14:44+05:30 |                               
   | 919092004000 | 919952248266  | 918680052951   | 2017-01-19 15:19:17.193059+05:30 | 2017-01-19 15:47:40.316685+05:30
  7 | DIALING      | INCOMING  |           161965 |               | 2015-08-06 20:39:37+05:30 |                               
   | 919092004000 | 918680052960  | 919840042792   | 2017-01-19 15:48:45.889152+05:30 | 2017-01-19 15:48:45.889152+05:30
  9 | DIALING      | INCOMING  |           161967 |               | 2016-04-25 12:11:52+05:30 |                               
   | 919092004000 | 918680052951  | 919962279088   | 2017-01-19 15:52:57.738041+05:30 | 2017-01-19 15:52:57.738041+05:30
 10 | DISCONNECTED | INCOMING  |           161968 |               | 2016-04-25 12:11:52+05:30 | 2017-01-19 15:54:04.1872+05:30
   | 919092004000 | 918680052951  | 919962279088   | 2017-01-19 15:53:38.279451+05:30 | 2017-01-19 15:54:04.188268+05:30
 11 | DIALING      | INCOMING  |           161969 |               | 2016-04-13 12:34:17+05:30 |                               
   | 919092004100 | 918680052951  | 919962219488   | 2017-01-19 15:54:44.628265+05:30 | 2017-01-19 15:54:44.628265+05:30
 12 | DISCONNECTED | INCOMING  |           161970 |               | 2016-04-13 12:34:17+05:30 | 2017-01-19 15:55:00.812569+05:
30 | 919092004100 | 918680052951  | 919962219488   | 2017-01-19 15:54:50.188144+05:30 | 2017-01-19 15:55:00.813381+05:30
 13 | DIALING      | INCOMING  |           161971 |               | 2015-07-25 21:46:16+05:30 |                               
   | 919092004000 | 918680052960  | 919962219488   | 2017-01-19 15:55:51.274847+05:30 | 2017-01-19 15:55:51.274847+05:30
 14 | DISCONNECTED | INCOMING  |           161972 |               | 2015-07-25 21:46:16+05:30 | 2017-01-19 15:56:27.120685+05:
30 | 919092004000 | 918680052960  | 919962219488   | 2017-01-19 15:56:16.769309+05:30 | 2017-01-19 15:56:27.121352+05:30
 15 | DIALING      | INCOMING  |           161973 |               | 2015-02-28 14:08:05+05:30 |                               
   | 919092004000 | 918680052960  | 919962219488   | 2017-01-19 16:17:07.748196+05:30 | 2017-01-19 16:17:07.748196+05:30
 16 | DISCONNECTED | INCOMING  |           161974 |               | 2015-02-28 14:08:05+05:30 | 2017-01-19 16:23:29.660578+05:
30 | 919092004000 | 918680052960  | 919962219488   | 2017-01-19 16:22:49.052434+05:30 | 2017-01-19 16:23:29.661516+05:30
  8 | DISCONNECTED | INCOMING  |           161966 |               | 2015-08-06 20:39:37+05:30 | 2017-01-19 16:24:10.048868+05:
30 | 919092004000 | 918680052960  | 919840042792   | 2017-01-19 15:48:51.393039+05:30 | 2017-01-19 16:24:10.049828+05:30
 17 | DIALING      | OUTGOING  |           161975 |               | 2016-02-19 10:14:44+05:30 |                               
   | 919092004000 | 919952248266  | 918680052951   | 2017-01-19 16:25:21.413631+05:30 | 2017-01-19 16:25:21.413631+05:30
 18 | DIALING      | OUTGOING  |           161976 |               | 2015-05-05 16:14:25+05:30 |                               
   | 919814047278 | 53500         | 919855544246   | 2017-01-19 16:25:52.202613+05:30 | 2017-01-19 16:25:52.202613+05:30
 19 | DIALING      | OUTGOING  |           161977 |               | 2015-07-10 16:59:08+05:30 |                               
   | 919092004000 | 919962219488  | 918680052960   | 2017-01-19 16:26:12.86812+05:30  | 2017-01-19 16:26:12.86812+05:30
 20 | DISCONNECTED | OUTGOING  |           161978 |               | 2015-07-10 18:33:19+05:30 | 2017-01-19 16:26:44.047322+05:
30 | 919092004000 | 919962219488  | 918680052960   | 2017-01-19 16:26:38.69352+05:30  | 2017-01-19 16:26:44.048411+05:30
 21 | DISCONNECTED | OUTGOING  |           161979 |               | 2015-07-10 18:19:13+05:30 | 2017-01-19 16:27:20.385819+05:
30 | 919092004000 | 919962219488  | 918680052960   | 2017-01-19 16:27:09.802522+05:30 | 2017-01-19 16:27:20.386565+05:30
 22 | IN CALL      | OUTGOING  |           161980 |               | 2016-04-25 07:24:45+05:30 |                               
   | 919702000506 | 9840042792    | 8680052951     | 2017-01-19 16:27:40.733472+05:30 | 2017-01-19 16:27:46.058709+05:30

**Comment by NeelaveniT** [comment]
Jqgrid I used 5.1.0 version

**Comment by tonytomov** [comment]
Hello,

It is always good to know the code in order to get resolution.

Your problem is not related with jqGrid, but with your server side code when a search is performed.

jqGrid just send this string (2016-02-09 10) to your server and your server is not able to recognize it in order to return results.

Please check your server side code how when search on such dates.

I will close the issue. If you think  there is jqGrid problem, please consider reopen it.

Kind Regards
Tony

**Comment by NeelaveniT** [comment]
Hi,

In my log , The query is D, [2017-01-25T14:38:03.834916 #11259] DEBUG -- :   Report Load (0.5ms)  SELECT  "reports".* FROM "reports" WHERE (start_time::text       ILIKE '%'||'2016-02-19 10'||'%')  ORDER BY id asc LIMIT 10 OFFSET 0

I checked with same query in database result is follow

camel=# SELECT  "reports".* FROM "reports" WHERE (start_time::text       ILIKE '%'||'2016-02-19 10'||'%')  ORDER BY id asc LIMIT 10 OFFSET 0;
 id | status  | call_type | camel_message_id | enterprise_id |        start_time         | end_time |   location   | called_nu
mber | calling_number |            created_at            |            updated_at            
----+---------+-----------+------------------+---------------+---------------------------+----------+--------------+----------
-----+----------------+----------------------------------+----------------------------------
  1 | DIALING | OUTGOING  |           161959 |               | 2016-02-19 10:14:44+05:30 |          | 919092004000 | 919952248
266  | 918680052951   | 2017-01-19 15:19:17.193059+05:30 | 2017-01-19 15:47:40.316685+05:30
 17 | DIALING | OUTGOING  |           161975 |               | 2016-02-19 10:14:44+05:30 |          | 919092004000 | 919952248
266  | 918680052951   | 2017-01-19 16:25:21.413631+05:30 | 2017-01-19 16:25:21.413631+05:30
(2 rows)

But not displayed on grid.
Same thing for date also it displayed properly in grid.
Kindly  help me to resolve this issue.

**Comment by tonytomov** [comment]
Hello,

it is not the same to execute the sql command in console and in the application.
Check really the result from your server and not from the console.

If possible trace the result an server when the search is in action.

You should look into the debug console in browser in order  to see the response.
If the response is empty, then you should really check your server side code

**Comment by NeelaveniT** [comment]
Hi,
  The problems occurs due to timezone between psql and rails server differ.
  So it datetime not matched properly.After updating the timezone in rails.It is working properly.
  Thank you so much for your kindly suggestion and reply.
