### ISSUE TITLE
rowNum -1 not all items shown

### ISSUE THREAD

**Issue by rulyotano** [tonytomov/jqGrid#836]
When set rowNum: -1, only show 'Total Items' - 1, I tested it for local data:

                 `//creates the table
                    this.jdGrid = $(tableId).jqGrid({
                        altRows: true,
                        datatype: "local",
                        data: this.tableData,
                        autowidth:true,
                        shrinkToFit:true,
                        colModel: colModel,
                        altclass: 'rel-table-alt-row',
                        rowNum: -1
                    });`

**Comment by tonytomov** [comment]
Hello,
The option rowNum -1 is not valid since a long time See here: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:options
To show all the records use length property of your data:

```js
             /creates the table
                this.jdGrid = $(tableId).jqGrid({
                    altRows: true,
                    datatype: "local",
                    data: this.tableData,
                    autowidth:true,
                    shrinkToFit:true,
                    colModel: colModel,
                    altclass: 'rel-table-alt-row',
                    rowNum: this.tableData.length
                });
```

Regards
