### ISSUE TITLE
Question about columns

### ISSUE THREAD

**Issue by chucky2183** [tonytomov/jqGrid#837]
Good night Tony. I don't know if i can ask here. But how i can change columns? I want to do with a mouse click and change the columns. I can do this? I see the remapColumns method, but don't work for me. 

 ![screenshot_39](https://cloud.githubusercontent.com/assets/9493223/22636858/ee7ca422-ec1c-11e6-8afb-4fb7bf6b4bef.png)

Can you help me please. 

Thanks
Regards

**Comment by tonytomov** [comment]
HEllo,

You may want to look here: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jquery_ui_methods

**Comment by tonytomov** [comment]
Hope you have solved the problem. I will close the issue. I case you have problems, please reopen
