### ISSUE TITLE
Column chooser height option not working, dialog_opts height only sets the popup height but multiselect height is still not set.

### ISSUE THREAD

**Issue by Abhishek2792** [tonytomov/jqGrid#844]
Hello,
 $(this).jqGrid('columnChooser', { dialog_opts :{ height:300} ,...}); only sets the dialog box height. In case of many columns, bottom part of scrollbar is hidden and some items from multi select list are not visible since it's height is not adjusted with respect to dialog box. Observed that manual resizing of dialog sets the proper height for multi select list but this is not the solution.

**Comment by tonytomov** [comment]
Hello,

Thank you. The problem is fixed.
Please let me know if it is fixed for you too.

Kind Regards,
Tony

**Comment by Abhishek2792** [comment]
Thanks Tony. Column chooser working as expected and the issue has been fixed.
