### ISSUE TITLE
Method 'getRowData' lose some data

### ISSUE THREAD

**Issue by heyusysu** [tonytomov/jqGrid#845]
This is my option.
```
var options = {
	url: xxx, //this is ajax request url
	datatype: 'json',
	colModel: [
		{
			name: 'code',
			label: 'Code'
		},
		{
			name: 'desc',
			label: 'Description'
		}
	],
	//other options
};
```
This is the data loaded by ajax.
```
{
	page: 1,
	records: 100,
	total: 3,
	rows: [
		{id: 1, code: 'a', desc: 'b', active: true},
		{id: 2, code: 'c', desc: 'd', active: false},
		//...other data
	]
} 
```
Now I call `$(myTable).jqGrid('getRowData', 1)`, It will return` {code: 'a', desc: 'b'}`, 'id' and 'active'  attribute disappear. This is a bug?

**Comment by tonytomov** [comment]
Hello,

This is not a bug. 
getRowData return the data only from the html grid content and not from the response - 
i.e. only the data from colModel.

To get what you want you will need to extend your colModel
```js
var options = {
	url: xxx, //this is ajax request url
	datatype: 'json',
	colModel: [
		{
			name: 'code',
			label: 'Code'
		},
		{
			name: 'desc',
			label: 'Description'
		},
                {      
                        name : 'active',
                        hidden :  true
                }
	],
	//other options
};

```

Regards

**Comment by heyusysu** [comment]
Thanks a lot. I have already resolved this problem. I store the data when trigger` afterInsertRow` like `datatype="jsonstring"`.
