### ISSUE TITLE
IE8 Expected identifier where cm[j].export is used

### ISSUE THREAD

**Issue by Krokador** [tonytomov/jqGrid#846]
I was testing a fairly recent version in Internet Explorer 8, because we're still supporting it (it makes me cry a little)...

As it turns out, export is a restricted keyword, so any reference to cm[j].export (see line 16687 for example) causes an issue. I worked around it by replacing every instance of **.export** in the code with **["export"]** - there were about 6-8 of them -, and that's pretty okay for me for now cuz I'm not using the built-in exports anyway. 

Would probably also require using quotes in the json of the colModel for those older Internet Explorer versions, and that's workable, too. Would have to be documented, though.

Since the addition is fairly recent, perhaps replacing the property with exportGrid instead might be a little more user-friendly for those of us who still have to deal with those legacy browsers?

**Comment by Krokador** [comment]
Also, a bit unrelated to this particular issue, but it's got to do with IE8 again: that outerheight fix for the frozen columns offset I had found really doesn't work well in versions 8 and lower, and going back to using only height only gives a tiny offset at the bottom of the grid. 

My project has a reference to a jquery browser plugin (I'm not great at browser detection, makes it easier) so I basically just replaced the line 
`mh.push( $(this).outerHeight() );`

with 
`if ($.browser.msie && $.browser.version <= 8)
  mh.push($(this).height());
else
  mh.push($(this).outerHeight());
`

but obviously it would have to be adjusted to work without that plugin and more recent versions of jquery where that's been deprecated

**Comment by tonytomov** [comment]
Hello,

First of all thank you for posting this issue.
IE8 is not supported anymore form Guriddo, but it is a good to know in the future  that we need to pay attention for the resered words.

Anyway I will see if I can do this change.

If you do not know jqGrid has its own browser function which of course detect only IE.
The above can be expressed in the code like

```js
....
mh.push( $.jgrid.msie() && $.jgrid.msiever() <= 8 ? $(this).height() : $(this).outerHeight() );
..
```
Will see if I I can put these changes.

Regards
Tony

**Comment by tonytomov** [comment]
Hello,

Since the change is not published I have renamed the export property to _exportcol_  (see here https://github.com/tonytomov/jqGrid/commit/d7dcd7b84e15fb1e472d74c89d9f04a63f4e176f ) in order to overcome similar problems.

Regards,
Tony

**Comment by tonytomov** [comment]
I will close the issue.
