### ISSUE TITLE
a question about "reformatAfterEdit" param

### ISSUE THREAD

**Issue by HadeAs** [tonytomov/jqGrid#849]
hi, when I edit a row, then I do not want formatter some column of the row after edit the row(these columns has "formatter" option). Is "reformatAfterEdit" param control above operate? but jqgrid source code do not has detail description about this param. so hope ypur answer.

**Comment by tonytomov** [comment]
Hello,

Thank you for the note about the docs. It will be fixed very soon.
Now to the question: The option have sense only when  formatter:'date' is used and have the same sense as from its name - the date entered when edit is not reformatted when inserted in the grid.

Please, let me know what for fields you need not to be reformatted - maybe I will help and make some improvement into the code.

Thank you.

Kind Regards,
Tony

**Comment by HadeAs** [comment]
Thank for your detailed reply. Now we hope for the option have sense not only 'date' but also 'number', 'select', 'currency', 'integer' and so on. Personally, now your code has supported the column that formatter:'date' will not to be reformatted after edit or other operate, why do not write similar code to make the column that formatter type mentioned above not to be reformatted

**Comment by tonytomov** [comment]
Hello,

To not reformat the date is clear- it is not  need in some casee (by example local data) to reformat the inputed from the user date to srcformat and then back to grid as new format

The same apply to the other types, but you will need to know that after this operation in case of local data if we have reformnatAfter edit false the data will be formatted (using the formatter)  on the next sort, paging and etc. 

I will see, if I can prepare this for the next release - it up to developer what to do at end

Thank you.

Kind Regards

**Comment by tonytomov** [comment]
In order to be a clear for me where and why it is this needed, could you please let me know the situation and/or grid setup where you need this. This way I can help you much better.

Kind Regards,
Tony

**Comment by tonytomov** [comment]
The solution of the problem for you is to create a custom unformat function which will return the formatted value. By example if you have a currebcy formatter and do not want to reformat the number do like this

````js
...
   colModel: [
      ...
      {
        name:'price',
        index:'price',  
        editable: true,
        formatter:'currency',
        unformat: function(cellvalue, options, cell) {
            return cellvalue;
        }
      },
      ...
   ]
...
});
````

Hope this helps
