### ISSUE TITLE
Why aJqgrid[0].grid.headers[i].el.hidden≠aJqgrid.getGridParam('colModel')[i].hidden

### ISSUE THREAD

**Issue by monice** [tonytomov/jqGrid#850]

**Comment by monice** [comment]
How can I get a visible table header？for example: I have 10 columns, after columnchooser (sort and hide) after 8 columns, how can I get the current table header information, I wrote getGridParam ('colModel'), these Object sets are not sorted

**Comment by tonytomov** [comment]
Use the grid option remapColumns (not the function) to get the order from colModel.
