### ISSUE TITLE
TreeGrid Bootstrap

### ISSUE THREAD

**Issue by krosoftware** [tonytomov/jqGrid#851]
Hello
I can not find any simple example using JSON and Bootstrap style for Treegrid.
Thank you for any help.

**Comment by tonytomov** [comment]
Hello,

Nothing special. The same way the TreeGrid work with jQuery UI it work with Bootstrap.
You will need to load the needed Bootstrap files.

If you need Example we can prepare it.
As example you can get idea using our demo here: http://www.guriddo.net/demo/bootstrap/

and more detailed explanation in our new documentation:  http://www.guriddo.net/documentation/guriddo/javascript/#using-bootstrap-css-framework

**Comment by krosoftware** [comment]
Hello, thank you so much. I already checked those links but I'm not able to use Treegrid with Bootstrap. It will be great if you can make Bootstrap sample based on this: http://www.guriddo.net/demo/treegridjs/
Thanks.

**Comment by tonytomov** [comment]
Here you are: http://guriddo.net/demo/treegridjs/bootstrap/

**Comment by krosoftware** [comment]
Awesome, thank you so much.
