### ISSUE TITLE
Treegrid pager

### ISSUE THREAD

**Issue by krosoftware** [tonytomov/jqGrid#852]
I see that one of limitations of the Treegrid is the disabled pager.
Is that solved in the meantime?
If not, how to load large data?
Thank you.

**Comment by tonytomov** [comment]
Personally I do not think that using pager in treegrid have sense.

To load big data you can use loading on demand example - i.e first load the root nodes and then when user click to load only the child nodes. 

You can look at these examples in our new documentation: 
See auto loading tree here:
http://www.guriddo.net/documentation/guriddo/javascript/user-guide/treegrid/#nested-set-example
or here
http://www.guriddo.net/documentation/guriddo/javascript/user-guide/treegrid/#adjacency-model-example

Regards,

**Comment by krosoftware** [comment]
Hello, it is not always good option to load only root nodes and then children's on demand.. there are some components which use pagination:
https://www.jeasyui.com/tutorial/tree/treegrid4.php
https://www.jeasyui.com/tutorial/tree/treegrid4.php
it is OK if every page have root nodes with no parents (each node without parent on that page can be on Level1) but important is to see nodes with parents..
Thank you for consideration.

**Comment by tonytomov** [comment]
Initially you can load as many nodes as you want just need to set loaded property to true of the loaded row.

**Comment by krosoftware** [comment]
Yes I know I can load all nodes but what if I have 50000 of them? Will that be slow without pagination?

**Comment by tonytomov** [comment]
Sure it will be slow.
Instead of what I mean, we plan to include into next major release a treegrid pagination.
Just check our Roadmap  http://guriddo.net/?page_id=103317 which will be published after a week or two.

Kind Regards,
Tony

**Comment by krosoftware** [comment]
Awesome. Thank you so much.
