### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by krosoftware** [tonytomov/jqGrid#853]
Hello
how to avoid display of horizontal scroll-bar when using Hierarchy?
Please take a look here: http://imgur.com/RjEtCut
Thank you

**Comment by tonytomov** [comment]
Hello,

You can either make the width of the subgrid columns smaller ( see the width parameters) or if possible make the main grid wider.

Regards

**Comment by krosoftware** [comment]
Hello
thank you for your answer but it's not about width. If you navigate here:
http://www.guriddo.net/demo/bootstrap/
and if you click on "Next page button" (please see image: http://imgur.com/4FHr2zS) you will see what I mean - you will see something like this: http://imgur.com/5lZbfsc
Thank you for your support.

**Comment by tonytomov** [comment]
Hello,

Understand. In some OS and browsers the width of the scroll change during releases.
I suppose this Chrome on Windows.

To resolve the problem increase the width of the scroll (look scrollOffset option) in grid. Default is 18px, maybe you can set it to 20.

Kind Regards

**Comment by tonytomov** [comment]
I have fixed the problem: https://github.com/tonytomov/jqGrid/commit/8841e8d917785575059ddbdab9ce2fd9b1e0eea0

Please reopen it if there is a problem.

Thank you

Kind Regards
