### ISSUE TITLE
VirtualLoad - how to?

### ISSUE THREAD

**Issue by krosoftware** [tonytomov/jqGrid#854]
Hello
I'm checking this example: http://www.guriddo.net/demo/bootstrap/loading_data/scrollbar/index.html
and I don't see how/where you send current page to server, like page x of y ?
Thank you.

**Comment by tonytomov** [comment]
Hello,

Page x of y is not send - we send only the requested  page.

Look at the grid option prmNames in our docs here: http://www.guriddo.net/documentation/guriddo/javascript/user-guide/basic-grid/#options

Regards

**Comment by krosoftware** [comment]
Hello
please let me ask on different way - if we take this example: http://www.guriddo.net/demo/bootstrap/loading_data/scrollbar/index.html
how you "know" what data client requested? What is that what client "ask" server?
Please forgive me for all my questions - as you can see I'm pretty new in this world and your help is very appreciated.

**Comment by tonytomov** [comment]
Since we know the number of records that is provided we create a div with certain height and based on thhis high when the user moves the scroll - changes the height we set the needed page.

If you interested you can look into the source code - function populateVisible

Regards

**Comment by tonytomov** [comment]
Closing the issue. Please reopen it if you have any other question or problem.
