### ISSUE TITLE
Show the results of chaos

### ISSUE THREAD

**Issue by M7lrv** [tonytomov/jqGrid#860]
My data：
`{
    "values": [
        {
            "id": "1",
            "mac": "64:09:80:57:A6:EE",
            "username": "WIFI-DQ",
            "company": "Xiaomi Communications Co Ltd",
			"isLeaf": false,
            "expanded": true,
			"level":0,
            "p_id": "0"
        },
        {
            "id": "2",
            "mac": "F0:B4:29:5A:B5:0F",
            "username": "1001",
            "company": "Tenda Technology Co., Ltd.",
			"isLeaf": false,
            "expanded": true,
			"level":0,
            "p_id": "0"
        },
        {
            "id": "3",
            "mac": "64:09:80:57:A6:EF",
            "username": "WIFI-DQ_5G",
            "company": "TP-LINK TECHNOLOGIES CO.,LTD.",
			"isLeaf": false,
            "expanded": true,
			"level":0,
            "p_id": "0"
        },
        {
            "id": "4",
            "mac": "00:1C:BF:8B:DF:8E",
            "username": "QCL16",
            "company": "Intel Corporate",
			"isLeaf": true,
            "expanded": true,
			"level":1,
            "p_id": "2"
        },
        {
            "id": "5",
            "mac": "98:2F:3C:07:56:36",
            "username": "admin23",
            "company": "Xiaomi Communications Co Ltd",
			"isLeaf": true,
            "expanded": true,
			"level":1,
            "p_id": "2"
        },
        {
            "id": "6",
            "mac": "34:80:B3:FC:3F:0B",
            "username": "Iphone",
            "company": "Iphone",
			"isLeaf": true,
            "expanded": true,
			"level":1,
            "p_id": "2"
        },
        {
            "id": "7",
            "mac": "35:85:B3:DC:3F:0B",
            "username": "Lenovo PC",
            "company": "Iphone",
			"isLeaf": true,
            "expanded": true,
			"level":1,
            "p_id": "3"
        }
    ],
    "start": 0,
    "limit": 15,
    "end": 15,
    "pageNumber": 1,
    "totalSize": 7,
    "totalPages": 1
}`

my html：
`$('#tree').jqGrid({
				"url":"wifi.json",
				"styleUI" : 'Bootstrap',
				"colModel":[
					{
						"name":"id",
						"index":"id",
						"sorttype":"int",
						"key":true,
						"hidden":true,
						"width":50
					},{
						"name":"username",
						"index":"username",
						"sorttype":"string",
						"label":"Name",
						"width":170,
						formatter: function (value, grid, rows, state) { 
							return "test："+value;
						}
					},{
						"name":"mac",
						"index":"mac",
						"sorttype":"string",
						"hidden":false,
						"width":50
					}
				],
				"width":"600",
				"hoverrows":false,
				"viewrecords":false,
				"gridview":true,
				"height":"auto",
				"loadonce":true,
				"rowNum":100,
				"scrollrows":true,
				// enable tree grid
				"treeGrid":true,
				// which column is expandable
				"ExpandColumn":"username",
				// datatype
				"treedatatype":"json",
				"treeIcons":{plus:'glyphicon-triangle-right',minus:'glyphicon-triangle-bottom',leaf:''},
				// the model used
				"treeGridModel":"adjacency",
				"tree_root_level":0,
				// configuration of the data comming from server
				"treeReader":{
					"level_field":"level",//
					"parent_id_field": "p_id",//
					"leaf_field":"isLeaf",
					"expanded_field":"expanded",
					"icon_field":"icon"
				},
				jsonReader: {  
                    root: "values",  
                    repeatitems : false  
                }, 
				"sortorder":"asc",
				"datatype":"json"
			}); `

I follow this configuration out, but the result is chaotic, I would like to ask, where there is a problem?

**Comment by tonytomov** [comment]
Hello,

Data should come sorted - i.e root element and it childs and not chaotic like yours.
try this:

Data:
```js
{ "values": [ 
		{ "id": "1", "mac": "64:09:80:57:A6:EE", "username": "WIFI-DQ", "company": "Xiaomi Communications Co Ltd", "isLeaf": true, "expanded": false, "level":0, "p_id": null }, 
		{ "id": "2", "mac": "F0:B4:29:5A:B5:0F", "username": "1001", "company": "Tenda Technology Co., Ltd.", "isLeaf": false, "expanded": true, "level":0, "p_id": null }, 
		{ "id": "4", "mac": "00:1C:BF:8B:DF:8E", "username": "QCL16", "company": "Intel Corporate", "isLeaf": true, "expanded": true, "level":1, "p_id": "2" }, 
		{ "id": "5", "mac": "98:2F:3C:07:56:36", "username": "admin23", "company": "Xiaomi Communications Co Ltd", "isLeaf": true, "expanded": true, "level":1, "p_id": "2" }, 
		{ "id": "6", "mac": "34:80:B3:FC:3F:0B", "username": "Iphone", "company": "Iphone", "isLeaf": true, "expanded": true, "level":1, "p_id": "2" }, 
		{ "id": "3", "mac": "64:09:80:57:A6:EF", "username": "WIFI-DQ_5G", "company": "TP-LINK TECHNOLOGIES CO.,LTD.", "isLeaf": false, "expanded": true, "level":0, "p_id": null }, 
		{ "id": "7", "mac": "35:85:B3:DC:3F:0B", "username": "Lenovo PC", "company": "Iphone", "isLeaf": true, "expanded": true, "level":1, "p_id": "3" } 
	], 
	"start": 0, "limit": 15, "end": 15, "pageNumber": 1, "totalSize": 7, "totalPages": 1 }
```
Grid:
```js
		   $('#tree').jqGrid({ 
			   "url":"data.json",
				"styleUI" : 'Bootstrap', 
				"colModel":[ 
					{ "name":"id", "index":"id", "sorttype":"int", "key":true, "hidden":true, "width":50 },
					{ "name":"username", "index":"username", "sorttype":"string", "label":"Name", "width":170, formatter: function (value, grid, rows, state) { return "test："+value; } },
					{ "name":"mac", "index":"mac", "sorttype":"string", "hidden":false, "width":50 } 
				], 
				"width":"600", 
				"hoverrows":false, 
				"viewrecords":false, 
				"gridview":true, 
				"height":"auto", 
				"loadonce":true, 
				"rowNum":100, 
				"scrollrows":true, 
				// enable tree grid 
				"treeGrid":true, 
				// which column is expandable 
				"ExpandColumn":"username", 
				// datatype 
				"treedatatype":"json", 

				// the model used 
				"treeGridModel":"adjacency", 
				"tree_root_level":0, 
				// configuration of the data comming from server 
				"treeReader":{ 
					"level_field":"level",
					"parent_id_field": "p_id",
					"leaf_field":"isLeaf", 
					"expanded_field":"expanded", 
					"icon_field":"icon" 
				}, 
				jsonReader: { 
					root: "values", 
					repeatitems : false 
				}, 
				"sortorder":"asc", 
				"datatype":"json" 
			});
```

**Comment by M7lrv** [comment]
Thank you for the answer, I still have a question if the treegrid can not use the checkbox?

**Comment by tonytomov** [comment]
Hello,

Currently checkboxes in treegrid are not supported. 

Regards

**Comment by M7lrv** [comment]
Ok thanks for your answer, I think you can add this feature, this feature is still very necessary.

**Comment by M7lrv** [comment]
Hello, I seem to find a bug,my data:`

var sname="<span value=\"{v}\">"+
		 "		<input type=\"checkbox\" id=\"chx{rowId}\" value=\"{rowId}\" onclick=\"clickCheckbox({rowId}, this);\" />"+
		 "		<i class='icon iconfont icon-{i}'></i>"+
		 "		&nbsp;{v}"
		 "</span>";
{"name":"name","index":"name","sorttype":"string","width":90,sortable:false,
            	   formatter: function (value,options, rows) {
            		   if(rows.devicetype == 0)
                      		return sname.replace("{i}","luyouqi").replace(/\{v\}/g,value).replace(/\{rowId\}/g,rows.id);
                      	else if(rows.devicetype == 1)
                      		return sname.replace("{i}","iphone").replace(/\{v\}/g,value).replace(/\{rowId\}/g,rows.id);
          				else if(rows.devicetype == 2)
          					return sname.replace("{i}","anzhuo").replace(/\{v\}/g,value).replace(/\{rowId\}/g,rows.id);
          				else if(rows.devicetype == 3)
          					return sname.replace("{i}","pc").replace(/\{v\}/g,value).replace(/\{rowId\}/g,rows.id);
          				else
          					return value;
       			},
       			unformat:function(cellvalue,options,cell){return $("span",cell).attr("value");}
               },`

When i use getRowData method ，Get out of the data is html, get out of the real data is wrong.
I think that this is a problem with the name of the keyword，Do not know how you look。At the moment, I have used other strings instead of resolving

**Comment by tonytomov** [comment]
Hello,

It is a good idea if you have new problem to create new post and if this one is resolved to close it.

Kind Regards

**Comment by tonytomov** [comment]
Please check the description of getRowData in our [docs here](http://www.guriddo.net/documentation/guriddo/javascript/user-guide/basic-grid/#method-list)

getRowData return what you inserted in the custom formatter and not the actual value of the input. Suppose you have inserted two or more input tags in one field, then  which value and we should return

**Comment by M7lrv** [comment]
I see jqgrid updated, I would like to ask, whether the treegrid can not be displayed? I see jqxTreeGrid do not need any sort can show treegrid, do jqgrid have to sort to show?If it is so I feel this is not a perfect function.I am a Chinese, China with a lot of this type of data

**Comment by tonytomov** [comment]
What you mean with sorted data? The data should come from the server in appropriate way. In case of nested set model it is a matter of simple sort (order by ) In case of adjency set model we need a recursive function which is very difficult to do. I highly recommend you to read our treegrid  documentation here: http://www.guriddo.net/documentation/guriddo/javascript/user-guide/treegrid/

**Comment by M7lrv** [comment]
Is the top of the problem that data，JqxTreeGrid css write too dead, resulting in other plug-ins can not be used together,At present I think the best is jqgrid, but this problem is a bit cumbersome
