### ISSUE TITLE
set background of row based on cell value

### ISSUE THREAD

**Issue by Wang-NQXB** [tonytomov/jqGrid#862]
hello!
i want to set background of row based on cell value.
is there anyway to do this efficiently？
please have a look, thank you.

**Comment by tonytomov** [comment]
Hello,

Please look at this forum post here: http://guriddo.net/?topic=how-to-add-css-class-for-a-row-with-specific-criteria

Regards

**Comment by tonytomov** [comment]
I will close the issue
