### ISSUE TITLE
Grouping after Clear & Reload Grid 

### ISSUE THREAD

**Issue by willy40** [tonytomov/jqGrid#864]
Situation:
Grid is load with data and grouping is enabled on one column
```
url: "/GetProducts",
datatype: "json",
editurl: "clientArray",
```
```
grouping: true,
                groupingView: {
                    groupField: ["ColA"],
                    groupColumnShow: [false],
                    groupText: ["<b>{0}</b>"],
                    groupOrder: ["asc"],
                    groupSummary: [false],
                    groupCollapse: false

                }
```
after clear data in grid and again reload with different data, grid remembers previous grouped rows
```
$grid.jqGrid("clearGridData");
$grid.setGridParam({ url: "/GetProducts", datatype: "json", page: 1 }).trigger("reloadGrid");
```
Workaround of that situation is to call groupingGroupBy

```
$grid.jqGrid("clearGridData");
$grid.jqGrid('groupingGroupBy', 'ColumnA');
$grid.setGridParam({ url: "/GetProducts", datatype: "json", page: 1 }).trigger("reloadGrid");
```
in that sequence, rows with grouped values has been cleared, and grid is showing correct grouped values.
clearGridData should clear grouped rows too.

**Comment by tonytomov** [comment]
Hello,

Thank you posting this problem. I will let you know about the status.

Kind Regards

**Comment by tonytomov** [comment]
Hello,

I have fixed the problem: https://github.com/tonytomov/jqGrid/commit/c3d4ecb667dfa80a305f7ab5e49600522f0b5c44 

Please let me know if this is working for you and if so do not forget to close the issue.

Thank you

Kind Regards,
Tony

**Comment by willy40** [comment]
Thank you Tony, 
now everything is ok :)
