### ISSUE TITLE
gridDnD and bindKeys not working together

### ISSUE THREAD

**Issue by Rikaelus** [tonytomov/jqGrid#865]
Perhaps this is known or even by design, but I cannot find any documentation to that effect.

Simply put, only one of gridDnD or bindKeys seems to work at any one time. Whichever is set last takes precedence. Seeing as though we're talking a clear divide between mouse actions and keyboard actions, I'd assume they could co-exist nicely.

I'll post a demonstration if needed but the problem is pretty straightforward.

Thanks

**Comment by tonytomov** [comment]
Hello,

Thank you for posting this problem.
To be a honest I never check this situation. Suppose there is a problem. I will investigate this and replay to you ASAP.

Thank you

**Comment by tonytomov** [comment]
Hello,

I have fixed the problem: https://github.com/tonytomov/jqGrid/commit/ad71303535c0662ba31bb5f507a26d9d9b6ba8bc

Please test it and if it is fine, please close the issue.

Kind Regards,
Tony

**Comment by Rikaelus** [comment]
Looks good! Thanks for the quick turnaround!
