### ISSUE TITLE
加载完数据后不自动分页，也不能排序？求大神指点

### ISSUE THREAD

**Issue by sunziyu** [tonytomov/jqGrid#866]
var mydata = json;
var width = $(".data-table1").width() - 20;
jQuery("#CXdata").jqGrid({
colNames: ['测项名称', '点检时间', '点检结果', '诊断结果', '上限', '下限', '上上限', '下下限', 'ID'], 
colModel: [
		{
		name: 'NodeName',
		align: 'center',
		formatter: function(cellvalue, options, rowObject) {
				return "<a href=\"cedian.html?nodeid=" + rowObject["NodeID"] + "\" style='text-decoration:underline;'>" + cellvalue + "</a>";
		     }
		},
		{
		name: 'TestTime',
		align: 'center',
		},
		{
		name: 'TestValue',
		align: 'center',
		formatter: function(cellvalue, options, rowObject) {
		return(toDecimal(cellvalue) + rowObject["Unit"]);
			}
		},
		{
			name: 'Ttype',
									align: 'center',
									formatter: function(cellvalue, options, rowObject) {
										return result(cellvalue);
									}
								},
								{
									name: 'AnodeHigh',
									align: 'center'
								},
								{
									name: 'AnodeLow',
									align: 'center'
								},
								{
									name: 'AnodeHighest',
									align: 'center'
								},
								{
									name: 'AnodeLowest',
									align: 'center'
								},
								{
									name: "NodeID",
									//				hidedlg:true,
									hidden: true
								}
							],
							viewrecords: true,
							height: 310,
							rowNum: 10,
							loadonce: true,
							pager: "#CXpage"
						});
						for(var i = 0; i <= mydata.length; i++) {
							jQuery("#CXdata").jqGrid('addRowData', i + 1, mydata[i]);
						}

**Comment by tonytomov** [comment]
Hello,

I can not understand the problem (instead of google translate). Can you please describe the problem?

Thank you.

**Comment by sunziyu** [comment]
@tonytomov 
jqgrid Can't automatic paging,sort,My English is bad,sorry

**Comment by sunziyu** [comment]
@tonytomov 
but I have written "rowNum: 10,".
and the same way in other page normal

**Comment by tonytomov** [comment]
Remove this code

```js
for(var i = 0; i <= mydata.length; i++) {
jQuery("#CXdata").jqGrid('addRowData', i + 1, mydata[i]);
}
```

and add the following to your grid settings:

```js
jQuery("#CXdata").jqGrid({
colNames: ['测项名称', '点检时间', '点检结果', '诊断结果', '上限', '下限', '上上限', '下下限', 'ID'],
colModel: [ 
...
],
viewrecords: true,
height: 310,
rowNum: 10,
datatype: 'local'
pager: "#CXpage",
data : mydata
});
```
