### ISSUE TITLE
bindKeys - Add onDownKey / onUpKey

### ISSUE THREAD

**Issue by Rikaelus** [tonytomov/jqGrid#869]
While my ultimate goal is to change pages based on the user going "up" and "down" passed the limits of the current page, more generically I'd just suggest adding "onDownKey" and "onUpKey" callbacks to the bindKeys configuration. It'd give me the flexibility to change pages but also open up other possibilities for other developers.

**Comment by tonytomov** [comment]
Hello,

This have sense. Added https://github.com/tonytomov/jqGrid/commit/9532fb2c220c5a8943fb768e50c392b012b81d2e

**Comment by Rikaelus** [comment]
Nice, thanks! I'll take it for a test drive later today. Love the quick response!

**Comment by Rikaelus** [comment]
Is there any chance the previously selected row can be passed to the callback? Right now it's sending the new selected row but without knowing what it was before the built-in operation, and whether or not the built-in operation changed it, we can't really append logic based on what the selected row was when they pressed up/down.

Alternatively, I saw that when defining gridDnD options, the "drag" and "drop" options have default functionality which can be overridden entirely by specifying new callbacks. A similar solution for key events might be nice -- especially for onUpKey/onDownKey where my intention is to handle movement, myself, to account for pagination and to loop to the bottom of the results when a person goes "up" passed the top of the list.

**Comment by tonytomov** [comment]
The solution is to call these events before setSelection. This methods selects the new row and set the appropriate id. Calling the events before it would give a possibility to query the previous selected row very easy - like

```js
   onKeyUp : function( newid ) {
      var lastid = this.p.selrow;
      ...
   }
```

**Comment by Rikaelus** [comment]
I'm slightly confused. You're suggesting you could move the callback call up in your code, to before you perform the setSelection, yes? That would accomplish the goal of getting the originally selected row in the callback but then any setSelection I'd do in that callback would be undone by the setSelection you'd be doing afterward.

That could be avoided if you check to see if the currently selected row changed after you call the callback -- meaning someone wanted to control that explicitly -- but that would strike me as a bit awkward.

**Comment by tonytomov** [comment]
Have added a second parameter previous selected id. Please let me know if it is ok. see the commit here: https://github.com/tonytomov/jqGrid/commit/c591cad4d34d7514f8685fbaf6a846ec9261cf49

**Comment by Rikaelus** [comment]
That'll be perfect. Much appreciated.
