### ISSUE TITLE
DnD: .ui-jqgrid-bdiv as drop target instead of table

### ISSUE THREAD

**Issue by Rikaelus** [tonytomov/jqGrid#871]
I think this is a repeat of the misunderstood https://github.com/tonytomov/jqGrid/issues/206, but given its age I thought I'd start a new issue.

The suggestion then, which I'd second, is to have the table's parent DIV (div.ui-jqgrid-bdiv) serve as the "drop" container instead of the table, itself. Large, empty grids can be confusing to drop to because only the small table will actually receive the drop. And there's the hack right now that if the table is empty, an empty faux row is added just to give the user a place to drop. If the parent DIV (which is 100% of available space) can be the receiver then that hack is no longer needed and it's a lot easier for the user to drop.

An easier alternative (though perhaps still somewhat hacky) might be to temporarily add however many faux rows are needed for the table to fill its .ui-jqgrid-bdiv parent's visible area.

I have a user calling this a nonstarter "bug" for drag&drop behavior, so I might play with how the code can be tweaked to improve the drop area.

**Comment by Rikaelus** [comment]
Pull request https://github.com/tonytomov/jqGrid/pull/872 added with bonus addition of tolerance config option, so users can specify "pointer" or "touch" to ease drag requirements. Should be a pretty straight forward update and while my test platform uses a pretty sophisticated implementation of jqGrid, DOM variations I might not be aware of might affect this change.

**Comment by tonytomov** [comment]
Thank you. Seems Ok. I will perform some tests and if there are no problems will merge it.
Yes -  a source code should be updated and nothing more

**Comment by tonytomov** [comment]
@Rikaelus ,
I like this addition. Thank you.
