### ISSUE TITLE
New version bug

### ISSUE THREAD

**Issue by ymofen** [tonytomov/jqGrid#874]
5.x loadData and clearData have bugs, please check. , 3ks
The 4.9.2 version is OK, 

`<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="https://cdn.bootcss.com/jqgrid/4.6.0/css/ui.jqgrid.css" />

		<script type="text/javascript" src="https://cdn.bootcss.com/jquery/1.12.1/jquery.min.js"></script>
		
		
		<script type="text/javascript" src="http://cdn.cdnjs.net/free-jqgrid/4.9.2/js/jquery.jqgrid.min.js"></script>
	</head>

	<body>
		<div>
			<button id="btnLoad">btnLoad</button>
			<button id="btnClear">btnClear</button>
		</div>
		<div id="pnlMain"></div>
	</body>

	<script>
		parent = document.getElementById("pnlMain");
		var __div = document.createElement("div");
		var __table = document.createElement("table");
		__div.appendChild(__table);
		parent.appendChild(__div);

		$("#btnLoad").click(function() {
			var data = [{
				"label": "AIRCONS",
				"description": "AIRCONS",
				"decimal": 2,
				"value": 30.4,
				"unit": "kg/h"
			}, {
				"label": "TORQUE",
				"description": "TORQUE",
				"decimal": 1,
				"value": 2,
				"unit": "nm"
			}];
			for(var i = 0; i <= data.length; i++) {
				$(__table).jqGrid('addRowData', i + 1, data[i]);
			}
		});

		$("#btnClear").click(function() {
			$(__table).jqGrid("clearGridData");
		});

		$(__table).jqGrid({
			datatype: "local",
			height: 250,
			colNames: ['label', 'description', 'decimal', 'value', 'unit'],
			colModel: [{
					name: 'label',
					index: 'label',
					width: 60
				},
				{
					name: 'description',
					index: 'description',
					width: 90
				},
				{
					name: 'name',
					index: 'name',
					width: 100
				},
				{
					name: 'value',
					index: 'value',
					width: 80,
					align: "right",
					sorttype: "float"
				},
				{
					name: 'unit',
					index: 'unit',
					width: 80,
					align: "right"
				}
			],
			caption: "数据"
		});
	</script>

</html>`

**Comment by tonytomov** [comment]
I have not tested this, but the table should have id and you should apply these methods not to _table, but to the id.

**Comment by ymofen** [comment]
>> the table should have id.
thanks

**Comment by tonytomov** [comment]
I will close the issue. If there is a problem, please consider a reopen
