### ISSUE TITLE
responsive:true when window resize cause horizontal bar 

### ISSUE THREAD

**Issue by sunplum123** [tonytomov/jqGrid#876]
version:5.2.1，StyleUI is Bootstrap 3.3.5 ,browser is chorme on windows 10 ,if set responsive :true ， it's ok!  but when window resize , horizontal scroll bar is appear ,you can see [https://imgur.com/gallery/mMkLv](url)； the data is not full in the grid

**Comment by tonytomov** [comment]
Hello,

Thanks. Can you please test the latest code from GitHub. We have done some changes in this direction

**Comment by sunplum123** [comment]
still have the same problem! I clone the latest Aug.8, when the grid is not filled with data , it has scroll offset ,when window resize horizontal scroll bar  is appear;  [https://imgur.com/gallery/mMkLv](https://imgur.com/gallery/mMkLv)

**Comment by tonytomov** [comment]
Please provide a demo demonstrating the problem - only this way we can resolve it. In all cases we can not reproduce the user setup and individual settings

**Comment by tonytomov** [comment]
Please reopen when you  can prepare a test case

**Comment by sunplum123** [comment]
sorry I forget it! 

It's here [reproduce](https://codepen.io/sunplum123/pen/xWrPaq)

when I reduce or enlarge the window sometimes horizontal scroll bar is appear,sometimes it's not appear.
![default](https://user-images.githubusercontent.com/13252563/38225828-566cda9a-3729-11e8-8048-ab76706ba0d7.JPG)

**Comment by sunplum123** [comment]
@tonytomov

**Comment by tonytomov** [comment]
Hello,

Thanks. Will look into this deeper next week.

**Comment by tonytomov** [comment]
It is fixed in the upcoming release.  See here: https://github.com/tonytomov/jqGrid/commit/3274f8be49746725eb08340dc4d421e218a0f1ab
