### ISSUE TITLE
Problem in the view option of the toolbar (Bootstrap UI)

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#879]
It seems that there is a bug in the view functionality of the toolbar. 
You cannot navigate to the previous object of the table through the arrows by selecting an object from the grid to view.  Instead console returns the following error: ` "Uncaught ReferenceError: npos is not defined"`

You can reproduce this bug in your own bootstrap examples: Fuctionality -> Toolbar Settings

**Comment by tonytomov** [comment]
Please let us know if the fix is ok for you.

**Comment by yannniskargakis** [comment]
Previous navigator button now works but for some reason #779 is now back.

**Comment by tonytomov** [comment]
Hello,

Regarding https://github.com/tonytomov/jqGrid/issues/779 - we an not reproduce the problem. Can you please send us a example with the new build where this happen?

Thank you

**Comment by yannniskargakis** [comment]
Hello,
It is exactly the same problem  (Bootsrtap UI / Windows 7 / both Chrome 60 and Firefox 54)  as before your fix on 3 Aug (see related comments on #779 ).  I have reproduced the problem using my old [example](https://github.com/tonytomov/jqGrid/files/1291974/index.txt)  on #779 using your latest build.

**Comment by tonytomov** [comment]
Sorry, I should test your example before to ask. The problem appear to be something like Catch 22 - in your example if you set shrinkToFit  : true it will work with the last code correct, but if shrinkToFit false it will work with the old code (before my fix).

Will see how to solve the problem.  

Regards 
Tony

**Comment by yannniskargakis** [comment]
Unfortunately shrinkToFit : true it's not an option for us, since we have grids with a lot of columns.
Please inform me for an fix asap.
Thanks

**Comment by tonytomov** [comment]
Yes, I know. The script should work in both cases - I do not mean "use" shrinkToFit : true when I posted this.

**Comment by tonytomov** [comment]
Can you please check the new fix. I hope we have fixed the issue this time. Here is the commit https://github.com/tonytomov/jqGrid/commit/c40aeacbf013779fcaaf57cd759f03a38a6d01b7

**Comment by yannniskargakis** [comment]
It seems that now it's ok. I hope to not bother you again with this issue :-)
Thank you for the fix

**Comment by tonytomov** [comment]
I will close it. If something is not working consider reopen
