### ISSUE TITLE
Responsive Bootstrap Grids

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#880]
Hello,
I am trying to make my grids (Bootrap UI) responsive and usable from a mobile device. Despite I have achieved the responsivity about the width of grids and columns i am facing difficulties on the toolbar. 

For example the toolbar does not fit properly.:

![img1](https://user-images.githubusercontent.com/18188368/29610794-049d73b6-8804-11e7-8979-5409819dbfe5.jpg)

Also popups are going out of the screen:

![img2](https://user-images.githubusercontent.com/18188368/29610803-0a3262aa-8804-11e7-977a-ad1649ffc7f9.jpg)

Could you suggest a solution?
I am attaching the code of above example [here](https://github.com/tonytomov/jqGrid/files/1245034/index.txt).

Thanks

**Comment by tonytomov** [comment]
Hello,

Thank you for the problems posted.
We know about these problems and currently we working on it. Hope to be ready very soon.
I will let you know when we have fixed these problems.


Kind Regards,

**Comment by tonytomov** [comment]
Already fixed in the latest version
