### ISSUE TITLE
Issue about the overlay (in CSS)

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#881]
Here is another issue about overlay in checkOnUpdate :

![capture](https://user-images.githubusercontent.com/18188368/29872797-b61f3bca-8d99-11e7-9b4f-538ad6d18fb7.JPG)

I noticed that this happens only in a Chrome browser.

**Comment by tonytomov** [comment]
Hello,

We have fixed the problem. Please let us know if the fix work for you and if it is ok, please close the issue.

Thank you

Kind Regards

**Comment by yannniskargakis** [comment]
Your fix works fine!
Thanks you.

**Comment by tonytomov** [comment]
Closing the bug
