### ISSUE TITLE
How to import with NPM

### ISSUE THREAD

**Issue by Lunatig** [tonytomov/jqGrid#885]
could you explain please How to import jqGrid with NPM?

Thanks

**Comment by tonytomov** [comment]
Look into the installation [guide here](http://www.guriddo.net/documentation/guriddo/javascript/#installation)

**Comment by Lunatig** [comment]
how can i import with webpack ?
require('jqGrid') 

This dependency was not found:

* jqGrid in ./index.js

To install it, you can run: npm install --save jqGrid


but i have already install it
