### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Dovgani** [tonytomov/jqGrid#886]
Hello Tony

I could not find the answer on my problem.
After drop target moves row columns for one column left, as you can see below.
I have 2 grids with the same model.

colModel: [
  { label: 'ID',        name: 'id',        width: 35,   editable: false, align: 'right', key: true },
  { label: 'Name',  name: 'name',  width: 100, editable: true },
  { label: 'Type',    name: 'type',    width: 100, editable: true,  align: 'right' },
  { label: 'Size',     name: 'size',     width: 100, editable: true,  align: 'right' },
  { label: 'Template', name: 'template', width: 100, editable: true,  align: 'left'  }
],

![image](https://user-images.githubusercontent.com/28760192/32617978-74f00c96-c544-11e7-981a-fe0c6d7603de.png)

![image](https://user-images.githubusercontent.com/28760192/32618021-877ec398-c544-11e7-945a-f42d67eeb7c5.png)

Thank you

**Comment by tonytomov** [comment]
Hello,

Could you please post the whole code including the two grids and drag and drop set-up?

Using only pictures and colModel only will not help.

Regards

**Comment by Dovgani** [comment]
Hello Tony,

I put my test project here: [https://github.com/Dovgani/jqGrid](url)
It is angular.
I removed as much as possible (just to have min to reproduce that behavior)
If you really need, I can publish, it in github pages to show that behavior in action.

Thank you 
Ghennady

**Comment by tonytomov** [comment]
Hello,

The url you give meis not working.You can simple post the two grid configurations and athe drag and drop setup

**Comment by tonytomov** [comment]
I will close the issue. If possible prepare a test case and reopen it.
