### ISSUE TITLE
about  setGroupHeaders

### ISSUE THREAD

**Issue by github-nbj** [tonytomov/jqGrid#887]
I am using JQGrid to represent tabular data. Version is 4.8.2
I want to group 2 column headers. I am using setGroupHeaders method of JQGrid, but it's not working.  
The error in console : cannot evaluate script: jqGrid - No such method: destroyGroupHeader
Here is my code. Where am I going wrong? Thanks in advance.

$("#AAA").jqGrid('setGroupHeaders', {	
	useColSpanStyle: true,
	groupHeaders:[
		{startColumnName: 'A', numberOfColumns: 2, titleText: 'tt1'},
		{startColumnName: 'B', numberOfColumns: 3, titleText: 'tt2'},
		{startColumnName: 'C', numberOfColumns: 2, titleText: 'tt3'}
		]
	});

**Comment by tonytomov** [comment]
Hello,

Can you please post the full code - only this way we can help resolve the issue

**Comment by tonytomov** [comment]
Close the issue. Feel free to reopen it when you prepare a test case.
