### ISSUE TITLE
Subsequent coucurrent calls on sortgrid ignored

### ISSUE THREAD

**Issue by jingyibo123** [tonytomov/jqGrid#888]
Hello everyone:

When calling the sortgrid method with reload = true, an ajax request is sent and before getting the response, any subsequent calls to this function will not fire an ajax request which could cause incoherence between GUI and data. 
Is there a way, upon subsequent call to this function, to abort the previous ajax request and fire a new one? 
Thanks for any help.

**Comment by tonytomov** [comment]
Hello,

You can use the [loadBeforeSend event](http://www.guriddo.net/documentation/guriddo/javascript/user-guide/basic-grid/#list-of-events). Define a variable and do
````js
loadBeforeSend: function (xhr) { 
    lastRequestXHR = xhr; 
}````
and then when you do reload by button or something elese do

````js
...
lastRequestXHR.abort();
````

**Comment by jingyibo123** [comment]
Hi, 
Thanks for super quick response. 
I juste tested, the event `loadBeforeSend` is fired between `ajaxStart` and `ajaxSend`, however when a ajax request is in progress, calling the `sortgrid` function won't fire any of them.

**Comment by tonytomov** [comment]
Use onSortCol event to abort the ajax call. See the docs for parameters

**Comment by jingyibo123** [comment]
Thanks I managed to get it working, although speed somewhat compromised when repeat sorting. I'll close the issue
