### ISSUE TITLE
Version is not updated in v5.3.0 

### ISSUE THREAD

**Issue by gs-rpal** [tonytomov/jqGrid#891]
Lib version is not updated in v5.3.

**Comment by gs-rpal** [comment]
Check jquery.jqGrid.js file

**Comment by tonytomov** [comment]
Hello,

Which jquery.jqGrid.js to check. [This one](https://github.com/tonytomov/jqGrid/blob/master/js/jquery.jqGrid.js) is upto date

**Comment by gs-rpal** [comment]
I mean the above mentioned file has version still set to 5.2.1. See line no 27

**Comment by tonytomov** [comment]
Thanks. Really forgot to update it.
