### ISSUE TITLE
subgrid expandOnLoad bug

### ISSUE THREAD

**Issue by Markus1980Wien** [tonytomov/jqGrid#892]
modify jquery.jqGrid.js to fix a bug with subgrid - expandOnLoad when "multiselect"

		if(ts.p.subGridOptions.expandOnLoad === true) {
			$(ts.rows).filter('.jqgrow').each(function (index, row)
			{
                // MBU 06.11.2017 Bugfix.
                // Don't perform a click on the first column.
                // if 'multiselect' is enabled for the grid, first column will be a checkbox - column
				//$(row.cells[0]).click();
				$(row).find("td.ui-sgcollapsed").click();
			});
		}

**Comment by tonytomov** [comment]
Thanks. Will be fixed.
