### ISSUE TITLE
onSelectRow and focus event in v5.3

### ISSUE THREAD

**Issue by raindy29** [tonytomov/jqGrid#894]
Upgrade from 5.2 to 5.3
focus event can't execute
`  $("#grid0").jqGrid("setGridParam", { onSelectRow: function(id) {
          $("#input").focus();  
      } 
  });`

**Comment by tonytomov** [comment]
Please provide a demo. Suppose maybe you will need to use setTimeout to focus the element.

**Comment by tonytomov** [comment]
Please reopen when you  can prepare a test case
