### ISSUE TITLE
uncorrect display when use  function cellattr in colModel

### ISSUE THREAD

**Issue by rookieBirdOne** [tonytomov/jqGrid#895]
when i use function  cellattr in  colModel，i find it display uncorrect if the return string  contains "style" key word. because the  function formatCol  in the source code will replace and split by "style" word 。 So can i  have a Solution here?

**Comment by tonytomov** [comment]
Which version is used? and can you please post a simple return string which causes the problem?

**Comment by rookieBirdOne** [comment]
jQGrid4.6  
e.g.:
cellattr: function(rowId, tv, rawObject, cm, rdata) {		  	    	
	  	    		return "id='xwkcmc" + rowId + "' tmp ='xwkcmc"+rawObject[XXX]+"'";
	    	 }
  i use tmp  to data something which inputed by user from page  .
  if user type " i have a  freestyle song for u "  then  gg.

**Comment by tonytomov** [comment]
Have fixed the problem here: https://github.com/tonytomov/jqGrid/commit/3fef030c9e54130f917670c1034e2918ef2c10ad
