### ISSUE TITLE
datatype: function() returns empty rows

### ISSUE THREAD

**Issue by jgotthelf** [tonytomov/jqGrid#896]
It seems like the readInput function doesn't handle datatype as a function.  It sets a local variable datatype = p.datatype, then has a switch statement checking if it is the string "xml", "xmlstring", "json", "jsonp", or "jsonstring".  As it is a function none of these get hit, thus the dataReader variable does not get populated.

Adding code like:
if (isFunction(datatype))
                        datatype = 'jsonstring';

Before the switch statement addresses the problem, but I'm not sure it is the best fix.

**Comment by tonytomov** [comment]
Sorry, but I need to ask - What is readInput function and where to find it?
