### ISSUE TITLE
Not showing nav bar icons like search, export icons when loadState call

### ISSUE THREAD

**Issue by satya9m** [tonytomov/jqGrid#897]
i am trying save the jqGrid state. i can able to save the state and load the state using buttons. but i need to load the state when page load. i can able to save the state at window.unload.

when i try to load the state in document.ready function, through java script error "beforeprocessing" null or ...

The search and export icons are not showing on custom menu bar icons on jqgrid when click on loadState button. this issue is occurring when i load the state through button.
$("#loadstate").click(function () {
        $.jgrid.loadState("jqGrid");});

 
 
Please provide any solution to load the state without using button and display all the custom menu bar icons(search,ExporttoExcel) on navbar

**Comment by tonytomov** [comment]
Please reopen when you  can prepare a test case
