### ISSUE TITLE
using jqGrid('getRowData') to get row data，but lose one;

### ISSUE THREAD

**Issue by NotLaugthingMe** [tonytomov/jqGrid#898]
hello
i have read the source code; the code in 'getRowData ' function,'len = $t.rows.length-1;' should be 'len = $t.rows.length;'
sorry,my English is poor

**Comment by tonytomov** [comment]
I suggest you to read the whole code carefully, especially this part:
````js
while(j<len){
   if(getall) {
      ind = $t.rows[j+1];  // ignore first not visible row
   }
...
````

**Comment by NotLaugthingMe** [comment]
thanks for your reply,but i really lost one, after trying to modify 'len = $t.rows.length-1'  to 'len = $t.rows.length', i have got the right rows;

**Comment by tonytomov** [comment]
Please provide a demo. Feel free to reopen the issue
