### ISSUE TITLE
Enter key press event issue on filter grid

### ISSUE THREAD

**Issue by satya9m** [tonytomov/jqGrid#900]
Please provide any help to solve the issue regarding Enter key press on Filter grid functionality(Raise Find button click event with Enter key press)  I tried below code, it's working only for the first option in the dropdown. it's not not working when i change the dropdown value.
`      $.extend($.jgrid.search, {
                            multipleSearch: false,
                            multipleGroup: false,
                            recreateFilter: true,
                            closeOnEscape: true,
                            closeAfterSearch: true,
                            overlay: 0,
                            afterRedraw: function (p) {
                               
                                var $form = $(this), formId = this.id, // fbox_list
                                    bindKeydown = function () {
                                        $form.find("td.data>.input-elm").keydown(function (e) {
                                            if (e.which === $.ui.keyCode.ENTER) {
                                                $(e.target).change();
                                                $("#" + $.jgrid.jqID(formId) + "_search").click();
                                            }
                                        });
                                    },
                                    oldOnChange = p.onChange,
                                    myOnChange = function (param) {
                                        var $input = $form.find("td.data>.input-elm"), events;
                                        oldOnChange.call(this, param);
                                        if ($input.length > 0) {
                                            events = $input.data("events");
                                            if (events && !events.keydown) {
                                                bindKeydown();
                                            }
                                        }
                                    };
                                p.onChange = myOnChange;
                                bindKeydown.call(this);
                            }
                        });`

**Comment by tonytomov** [comment]
Did you have chance to look carefully into the docs? - http://www.guriddo.net/documentation/guriddo/javascript/user-guide/searching/#single-searching
If I understand correct the requirement there is a option called **searchOnEnter**

**Comment by satya9m** [comment]
Could you please provide any sample code for "searchOnEnter" functionality?

**Comment by tonytomov** [comment]
No need of example, just set this item to true in your search options and after enter some value in serch text press enter to search
