### ISSUE TITLE
Clear Footer Only 

### ISSUE THREAD

**Issue by buttflattery** [tonytomov/jqGrid#903]
Looking at the documentation it says that I can clear the footer row by using `true` for the `clearfooter` parameter

`$("#jqGrid").jqGrid('clearGridData',true)` 

but this clears the footer along with the body section too is there any way I can clear the footer data without clearing the whole grid.

You can try the above statement in the console for this grid [here](http://www.trirand.net/demo/javascript/jqgrid/grouping/summary_and_grand_total/index.html)

**Comment by tonytomov** [comment]
Try with this code:

````js
var grid = $("jqGridId")[0];
$(".ui-jqgrid-ftable td", grid).html("&#160;");
````

**Comment by tonytomov** [comment]
This is correct 

```js
$(".ui-jqgrid-ftable td", "#jqGridId_gbox").html("&#160;");
```

Sorry for the mistake
