### ISSUE TITLE
Grid has no styling

### ISSUE THREAD

**Issue by bradykelly** [tonytomov/jqGrid#904]
I have included the following two css files I found with jqGrid, yet the rendered grid is still plain, black and whit, without even proper padding in cells.

`ui.jqgrid.css`
`ui.jqgrid-bootstrap-ui.css`

**Comment by tonytomov** [comment]
Please, look into the documentation here Bootstrap 3: http://www.guriddo.net/documentation/guriddo/javascript/#using-bootstrap-v3-css-framework 
and here for Bootstrap 4: http://www.guriddo.net/documentation/guriddo/javascript/#using-bootstrap-v4-css-framework

**Comment by tonytomov** [comment]
Please, reopen the issue if you have problems with this
