### ISSUE TITLE
Currency formatter issue

### ISSUE THREAD

**Issue by kodyli** [tonytomov/jqGrid#905]
Hi there,

When I try to use the currency formatter with a number 256.525 and decimal places is 2, I get 256.52 instead of 256.53; but if I change the number to 2.525, I get 2.53 which is I expect.

You may find useful information from http://www.jacklmoore.com/notes/rounding-in-javascript/

Have a good one.
[index.zip](https://github.com/tonytomov/jqGrid/files/1831593/index.zip)

**Comment by tonytomov** [comment]
Hello,

Thanks for the demo and find this bug. The problem is fixed. Please let me know if you have problems with this fix.

Thank you
