### ISSUE TITLE
Header cell tooltip different than cell value

### ISSUE THREAD

**Issue by onedevteam** [tonytomov/jqGrid#909]
Hi, while working with version 4.6.0 of jqgrid, i run in to a problem. 
Tooltip for header cell could not be set to anything other than actual cell value.

I fixed this by replacing line: 2511 in jquery-ui.jqGrid.js
 `               var tooltip = ts.p.headertitles ? (" title=\""+$.jgrid.stripHtml(ts.p.colNames[i])+"\"") :"";`

with this one: 
`                var tooltip = ts.p.headertitles ? (" title=\"" + (ts.p.colModel[i].tooltip ? ts.p.colModel[i].tooltip : $.jgrid.stripHtml(ts.p.colNames[i])) + "\"") : "";`

Do you think this is a viable solution for my problem, or do you have any other suggestion?

**Comment by tonytomov** [comment]
Thank you.

Your suggestion is added
