### ISSUE TITLE
setFrozenColumns and bindKeys

### ISSUE THREAD

**Issue by MonkSoul** [tonytomov/jqGrid#911]
This is my code：
```
tableGrid.jqGrid("setFrozenColumns");
tableGrid.jqGrid('bindKeys');
```
I try use the up key to switch row, over and over again ,but it's don't working.
if i don't use `tableGrid.jqGrid("setFrozenColumns");`，that is right.

**Comment by tonytomov** [comment]
Hello,

This work (with small exceptions)
Remember when using FrozenColumns, this method should be called as last one if you have other methods.  This to work you should

````js
tableGrid.jqGrid('bindKeys');
tableGrid.jqGrid("setFrozenColumns");
````

I have made some small fix to work this better when frozen columns are on. See here:
https://github.com/tonytomov/jqGrid/commit/c1806f857d419572e9f12b9c38c0f596c77b3583
