### ISSUE TITLE
After locking the column, it can be dragged and dragged[bug]

### ISSUE THREAD

**Issue by kenni0124** [tonytomov/jqGrid#912]
I think the lock column is not allowed to drag and drop.

**Comment by tonytomov** [comment]
Hello,

What you mean with lock column. Did you mean some feature in column model.
Sorry that we do not understand this.

Regards

**Comment by kenni0124** [comment]
http://www.guriddo.net/demo/bootstrap/functionality/bootstrap4/

1.freeze 'price' col: price Category Name Product Name Country Quantity
2.move srcoll
3.move 'Category Name' to first col
4.price is not freeze , move srcoll 
( i think this time 'Category Name' It should not be allowed to move to the first column )

I don't know if I am Express clearly

:)

**Comment by tonytomov** [comment]
Hello,

Understand. Drag and drop with forzen columns are not supported, this will not not work.
We already have described this limitation. Please look here: http://www.guriddo.net/documentation/guriddo/javascript/user-guide/frozencols/#notes-limitations

**Comment by tonytomov** [comment]
I you think there is a problem, please reopen the issue. I will close it.
