### ISSUE TITLE
Colum menu wrong position

### ISSUE THREAD

**Issue by BogMil** [tonytomov/jqGrid#913]
Dislocated col menu when some elements are before table tag. It is related to bug fixed on April 11. 

Pic below is from official demo, just some h1 tags inserted to show the issue.

![capture](https://user-images.githubusercontent.com/25194010/42777792-5ac8817a-893b-11e8-889a-0b9813509974.PNG)

**Comment by BogMil** [comment]
You're welcome.
But still, there is the same issue... 
Nothing changed. It is dislocated by X and Y axis.

**Comment by tonytomov** [comment]
Do you have downloaded from github the build? We don't put the change in the site. Please download from here: https://github.com/tonytomov/jqGrid/archive/master.zip

**Comment by BogMil** [comment]
Yes, I downloaded latest version form github and copied .js files over existing ones...  In fact, only one line is changed in jquery.jqGrid.js.

**Comment by tonytomov** [comment]
Yes one line is changed, but it should work. Do you need a online demo?

**Comment by tonytomov** [comment]
Try with this: http://guriddo.net/demo/bootstrap/functionality/column_menu_test/

**Comment by BogMil** [comment]
But if you wrap h1 tags and jqgrid into div with class="container" it is dislocated again. I tried it within demo.

**Comment by tonytomov** [comment]
Please post  demo (or at least html code )  which causes the problem?

**Comment by BogMil** [comment]
https://jqgriddemo.000webhostapp.com/

**Comment by tonytomov** [comment]
Thanks. Have do some other changes. You can get the last build from GitHub

**Comment by BogMil** [comment]
It is fixed now. Thanks!
