### ISSUE TITLE
You need a conditional to FIX

### ISSUE THREAD

**Issue by thefantas** [tonytomov/jqGrid#914]
https://github.com/tonytomov/jqGrid/blob/0e427df9e6fedece458cb6a9afd4bb8a05114f60/js/grid.base.js#L5826

You need a conditional to activate the focus otherwise when you activate inlineNav and bindKeys does not respect the focus.

"FIX gridDnd"
https://github.com/tonytomov/jqGrid/commit/ad71303535c0662ba31bb5f507a26d9d9b6ba8bc

This fix brings me a lot of problems when I activate inlineNav and bindKeys, click on add then click on the other inputs and the focus is lost, but if I comment on this "FIX" it works very well.
Conclusion, they fixed one problem but generated another.

http://jsfiddle.net/5otf826j/21/

I will listen to your comments.

**Comment by tonytomov** [comment]
I can't reproduce the problem with your demo in jsfiddle. I do the following:

Click on the link you provide, the system is direct in add mode, the I click on the other inputs of the same row, but the focus is here.  

Tested with FireFox and Chrome latest versions

**Comment by thefantas** [comment]
You're right, I uploaded the javascript modified by me... now I've updated the original jqGrid again.
http://jsfiddle.net/5otf826j/21/
Check again. Check again.
Greetings.

**Comment by thefantas** [comment]
Hello, with that conditional the problem has been solved, thanks :)
