### ISSUE TITLE
when i open my website the console throw an error: Uncaught jqGrid - No such method: jqGridExport

### ISSUE THREAD

**Issue by wangqiCQU** [tonytomov/jqGrid#915]

**Comment by tonytomov** [comment]
Be a sure the jqGrid Javascript file is loaded and you use the right version, which support the export.

**Comment by wangqiCQU** [comment]
l download the jqgrid from the github  some days ago. It is may be the lastest version.i have not  use the export funtion,  now i only use the base funtion, the question doesn't happend all time, it happened ony a few tims.  when the error happened, the error may be solve by refresh the page.  this is not a good solution.

**Comment by tonytomov** [comment]
Hello,

Please prepare a demo which describes the problem. You can use jsfiddle for this purpose. Only this way we can help resolving the problem
