### ISSUE TITLE
subgird with actionformatter - edit mode stays on cancel

### ISSUE THREAD

**Issue by stefancvetkovic** [tonytomov/jqGrid#917]
I have this issue only with subgrid. When I click the "pencil" icon, and I change something.. for example set checkbox to true, and then I click cancel icon, the row stays in edit mode.

`{ name: 'IsConnected', index: 'IsConnected', label: connected, width: 8, formatter: "checkbox", search: false, align: "center", editable: true, edittype: "checkbox", editoptions: { value: "True:False" } },
                            {
                                name: 'actions', index: 'actions', label: "test", formatter: 'actions', width: 50, fixed: true, align: 'center', sortable: false, search: false,
                                formatoptions: {
                                    editbutton: true,
                                    keys: false,
                                    delbutton: false,
                                    onSuccess: function (jqXHR) {
                                      return [true];
                                    }
                                }
                            }`

**Comment by tonytomov** [comment]
Please post your full jqGrid code and if possible put a demo data.

**Comment by stefancvetkovic** [comment]
this is my whole document.ready():
`$(document).ready(function () {
    var grid = $(pc.cdl.insuranceproduct.gridSelector).jqGrid({
        url: app.getApiUrl("CodelistApi", "GetInsuranceProducts"),
        datatype: 'json',
        mtype: 'GET',
        pager: '#' + pc.cdl.insuranceproduct.prefix + '_pagerGridInsuranceProduct',
        rowNum: 10,
        rowList: [10, 20, 30, 50],
        sortable: true,
        sortname: 'Code',
        sortorder: 'asc',
        height: '100%',
        viewrecords: true,
        loadonce: false,
        gridview: true,
        headertitles: true,
        autowidth: true,
        shrinkToFit: true,
        ondblClickRow: function (rowid) {
            custom.modal(app.getUrl('Codelist', 'InsuranceProductDetails') + '/' + rowid + '?ro=1', 'productcatalog_codelists_insuranceproduct', false, '', '', BootstrapDialog.SIZE_WIDE);
        },
        colModel: [
            { name: 'ID_Surrogate', index: 'ID_Surrogate', hidden:true, width: 10 },
            { name: 'Code', index: 'Code', label: app.translateString("productcatalog_codelists_insuranceproduct_code"), width: 10 },
            { name: 'CoreCode', index: 'CoreCode', label: app.translateString("productcatalog_codelists_insuranceproduct_corecode"), width: 10 },
            { name: 'Name', index: 'Name', label: app.translateString("productcatalog_codelists_insuranceproduct_name"), width: 10 },
            { name: 'CompanyName', index: 'CompanyName', label: app.translateString("productcatalog_codelists_insuranceproduct_insurancecompany"), width: 10 },
            { name: 'InsuranceType', index: 'InsuranceType', label: app.translateString("productcatalog_codelists_insuranceproduct_insurancetype"), width: 10 },
            { name: '', index: '', width: 50, fixed: true, align: 'center', search: false, formatter: pc.cdl.insuranceproduct.actionFormatter },
        ],
        gridComplete: function () {
            app.resizeJQGrid();
        },
        subGrid: true,
        subGridRowExpanded: function (productlistgrid_id, row_id) {
            var rowData = grid.getRowData(row_id);
            var surrid = rowData['ID_Surrogate'];
            var ids = grid.jqGrid("getDataIDs");
            if (ids && ids.length > 0)
                grid.jqGrid("setSelection", row_id);

            if (surrid != null && surrid != undefined) {
                var productlistgrid_table_id;
                productlistgrid_table_id = productlistgrid_id + "_t";
                pager_id = "p_" + productlistgrid_table_id;
                jQuery("#" + productlistgrid_id).html('<div class="jqGrid" id="div_' + productlistgrid_table_id + '"><table id="' + productlistgrid_table_id + '" class="scroll"><tr><td></td></tr></table><div id="' + pager_id + '" class="scroll"></div></div>');
                var productsGrid = jQuery("#" + productlistgrid_table_id).jqGrid({
                    url: app.getApiUrl("ProductCatalogApi", "GetProducts") + '?surrid=' + surrid,
                    editurl: function () {
                        return app.getApiUrl('ProductCatalogApi', 'SaveProductInsuranceProductData');
                    },
                    datatype: 'json',
                    mtype: 'GET',
                    pager: pager_id,
                    rowNum: 10,
                    rowList: [10, 20, 30, 50],
                    sortable: true,
                    sortname: 'Code',
                    sortorder: 'asc',
                    height: '100%',
                    viewrecords: true,
                    loadonce: false,
                    gridview: true,
                    headertitles: true,
                    autowidth: true,
                    shrinkToFit: true,
                    ondblClickRow: function (rowid) {
                        window.location.href = app.getUrl('Product', 'ProductDetails') + '/?id=' + rowid + '&ro=1';
                        return false;
                    },
                    beforeSelectRow: function (rowid, status, e) {
                        if (ids && ids.length > 0)
                            grid.jqGrid("setSelection", row_id);
                        $.each($('[id^="' + pc.cdl.insuranceproduct.prefix + '_gridInsuranceProduct"][id$="_t"]').not(pc.cdl.insuranceproduct.gridSelector), function (i) {
                            var id = $(this).attr('id');
                            $('#' + id).jqGrid('resetSelection');
                        });
                        pc.cdl.insuranceproduct.gridProductList = "#" + productlistgrid_table_id;
                    },
                    colModel: [
                                { name: 'Name', index: 'Name', label: app.translateString("productcatalog_codelists_product_name"), width: 10 },
                                { name: 'Code', index: 'Code', label: app.translateString("productcatalog_codelists_product_code"), width: 10 },
                                {
                                    name: 'ActivationDate', index: 'ActivationDate', label: app.translateString("productcatalog_codelists_product_activationdate"), width: 10, searchoptions: {
                                        dataInit: function (elem) {
                                            $(elem).datepicker({
                                                onClose: function (selectedDate) {
                                                    productsGrid.get(0).triggerToolbar();
                                                }
                                            });
                                        }
                                    }
                                },
                                {
                                    name: 'ClosureDate', index: 'ClosureDate', label: app.translateString("productcatalog_codelists_product_closuredate"), width: 10, searchoptions: {
                                        dataInit: function (elem) {
                                            $(elem).datepicker({
                                                onClose: function (selectedDate) {
                                                    productsGrid.get(0).triggerToolbar();
                                                }
                                            });
                                        }
                                    }
                                },
                                { name: 'ProductType', index: 'ProductType', label: app.translateString("productcatalog_codelists_product_producttype"), width: 10 },
                                { name: 'InProduction', index: 'InProduction', label: app.translateString("productcatalog_codelists_product_isinproduction"), width: 3, align: 'center', search: false, formatter: pc.cdl.insuranceproduct.inProductionFormatter },
                                { name: 'IsConnected', index: 'IsConnected', label: app.translateString("productcatalog_codelists_product_isconnected"), width: 8, formatter: "checkbox", search: false, align: "center", editable: true, edittype: "checkbox", editoptions: { value: "True:False" } },
                                {
                                    name: 'actions', index: 'actions', label: app.translateString("productcatalog_codelists_product_actions"), formatter: 'actions', width: 50, fixed: true, align: 'center', sortable: false, search: false,
                                    formatoptions: {
                                        editbutton: true,
                                        keys: false,
                                        delbutton: false,
                                        onSuccess: function (jqXHR) {
                                            return [true];
                                        }
                                    }
                                }
                    ],
                    gridComplete: function () {
                        app.resizeJQGrid();
                    },
                });
                productsGrid.jqGrid('filterToolbar');
            }
        },
    });
    grid.jqGrid('filterToolbar');
});`

as you can see the data doesnt matter..itc calling mny WebAPI in MVC ASP.NET project.

**Comment by tonytomov** [comment]
I see you use free-jqGrid (you post the same problem here: https://stackoverflow.com/questions/51710296/jqgrid-subgrid-stucks-on-edit-mode ). Here is Guriddo jqGrid, which is commercial. Since free-jqGrid have its on way, which differ from Guriddo we can't help you.

The problem maybe is caused that you  do not have a unique row id defined with key: true or jsonReader, which causes maybe the problem.

Kind Regards,
Tony

**Comment by stefancvetkovic** [comment]
@tonytomov  thanks for quick reply.
The catch that its working on main grid. properties are pretty much the same from main and subgrid. 
Thanks anyway.
