### ISSUE TITLE
Sorting issue when using jsonmap with nested objects and loadonce

### ISSUE THREAD

**Issue by mdprw** [tonytomov/jqGrid#918]
I'm loading my grid with a nested object and used jsonmap to map the columns (I set loadonce=true). I'm getting my json response and the grid is populated with the received data, but when I try to sort (datatype is local now) all fields change to undefined/blank.

I prepared a small demo here:
[http://jsfiddle.net/xpvt214o/557305/](url)

Thanks.

**Comment by tonytomov** [comment]
Thank you for finding this problem. I have fixed it. Please let us know if it is fixed for you and if so, please close the issue.

Thank you again 

Kind Regards,
Tony

**Comment by mdprw** [comment]
The fix is working, thanks!
