### ISSUE TITLE
Dislocated column menu when horizontaly scroll

### ISSUE THREAD

**Issue by BogMil** [tonytomov/jqGrid#920]
When column menu is opened and when you try to horizontally scroll, column menu does not move with parent column. It stays fixed on screen. Then when you close opened column menu, and try to open new one, the new one is dislocated. 

It is dislocated if first one (column menu) is left dislocated with scrolling before opening new one . Every new column menu is shifted right or left for for exact amount of space that you make when scrolling. It is easy to try it on this demo : http://www.guriddo.net/demo/bootstrap/functionality/column_menu/index.html
but first, it is necessary to make column wider to gain horizontal scroll bar.

**Comment by tonytomov** [comment]
Thanks. The fix is not so easy. The only good solution is to close the menu when you scroll horizontally. 
I will try to do it these days.

Regards

**Comment by tonytomov** [comment]
Have fixed the problem. You can try and let me know if it is fixed for you
