### ISSUE TITLE
Can not set default options for navGrid

### ISSUE THREAD

**Issue by BogMil** [tonytomov/jqGrid#921]
When i console $.jgrid, there is no nav property. So i can not set options for navGrid globally as suggested here: 
https://stackoverflow.com/questions/19538012/jqgrid-default-refresh-button-to-refresh-current-page 

Also there is no properties like add or edit defined in docs:
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:navigator

But, for example, i have defaults property, where i can set default values, that is documented here:
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:options#setting_options_globally

**Comment by tonytomov** [comment]
The documentation you refer is for the jqGrid <=4.7

It is highly recommended to read the new documentation here: http://www.guriddo.net/documentation/guriddo/javascript/

As from the higher versions you can query the values from language file:
var nav = $.jgrid.regional["en"].nav;

in case you use english language file.

Please read carfully the new docs.

Kind Regards,
Tony

**Comment by BogMil** [comment]
Yes, but it is regional file. 
For example, I want for all my navGrid to set refresh:false. 
Is it possible to set false as default value for refresh?

Thanks for quick answering!

**Comment by tonytomov** [comment]
I do not see a problem to do something like this:
````js
<head>
    <script type="text/ecmascript" src="...jquery.jqGrid.js"></script>
    <script type="text/ecmascript" src=".../i18n/grid.locale-en.js"></script>
    ...
    <script>
        $.jgrid.regional["en"].nav.refresh = true;
     </script>
	
</head>
````

**Comment by BogMil** [comment]
Works. Thanks!
