### ISSUE TITLE
How to append dynamically option in select tag in jqgrid?

### ISSUE THREAD

**Issue by rahultank1993** [tonytomov/jqGrid#922]
I want to load select tag options using ajax by selecting another select tag option.

Is there any way, please suggest.

**Comment by tonytomov** [comment]
This is called depended dropdown in jqGrid. You may want to look at [Guriddo jqGrid demo](http://www.guriddo.net/demo/guriddojs/edit_add_delete/dialogs_dependent_dropdowns/index.html)
