### ISSUE TITLE
Selected row i treeGrid

### ISSUE THREAD

**Issue by BogMil** [tonytomov/jqGrid#925]
When treeGrid=true after updating node row, selectedRow is the updated row, but all the css for selected row is gone. So it looks like it is not selected. Also, same thing when refreshing.  Selected row is the one that has been selected before refreshing.

Fixed it with afterComplete() and resetSelection(),  and custom refresh button...

**Comment by tonytomov** [comment]
It depends how you update it. It will be good to demonstrate this with example
