### ISSUE TITLE
Column header not function when hidden field exists in column model array

### ISSUE THREAD

**Issue by kstan79** [tonytomov/jqGrid#929]
Im use jqgrid with turn on column menu & filter. The table I show to user consist hundred of field, and I have setting to allow user show hide column. I notice strange behaviour which is when all column shown, the header filter work properly. When activate 'hidden=true' in columnmodel (we hide most of the seldom use column), the header filter no longer activate. I can't find any relevant article regarding this topic.
Anyway to solve it? 

Edit:
sorry, it happened during bugs exists, same column name and column model appear more then 1 time cause this. thanks

**Comment by kstan79** [comment]
close issue

**Comment by tonytomov** [comment]
Did you have found the resolution?

**Comment by tonytomov** [comment]
Sorry do not see the updated oh the original post
