### ISSUE TITLE
Password Masking Problem

### ISSUE THREAD

**Issue by sithes** [tonytomov/jqGrid#93]
Hi, I wasn't able to find anything addressing this specific issue.
I'm using inline editing with users and the issue has to do with passwords.
When displaying a password field I see I can mask the data by setting:
DataFormatString = "**********" and EditType = EditType.Password
But when I edit a row and put in a new password and save it, it displays the string I just entered instead of a masked string.
How can I get it to mask the password correctly?

**Comment by nikhiltembhe** [comment]
have you found any solution as I am also looking for it.
