### ISSUE TITLE
Autowidth & Responsive properties don't behave correctly on hidden elements (for example inactive tabs)

### ISSUE THREAD

**Issue by mdprw** [tonytomov/jqGrid#930]
Autowidth & Responsive properties don't work correctly on hidden elements. When I instanciate jqgrid on an inactive tab the witdh of the grid is not calculated as it should. I know is not easy to calculate the width of hidden elements, but I would expect the grid to react when the tab is active and set the width accordingly. I could use the tab click event to set the width of the grid by myself using the width of the container but there's one remaining issue that I can't fix (Please read problem number 1).

I prepared a small demo here:
http://jsfiddle.net/to6unkh9/

Problems:
1) On the grid of the second tab (inactive) if I set autowidth & responsive to true the action buttons get replaced by the text "action" with a menu. This is not the desired behavior since there's plenty of space to put the action icons. besides that, the "actions" menu doesn't work if I set the language to spanish.

2) On the first grid (active) the behavior is not consistent. You can see there's some space to allocate the scrollbar (I could set scrollOffset: 0 to fix this) but when you resize the browser that space is no longer present. Widths are calculated differently?

Thanks!

**Comment by mdprw** [comment]
This also happens with lastest version (5.3.2)

**Comment by tonytomov** [comment]
Hello,

This is a well know discussion.

Please look at [this discussion](http://www.trirand.com/blog/?page_id=393/help/autowidth-with-jquery-tabs) in order to get idea how to solve the problem.

**Comment by mdprw** [comment]
Ok, I choose to set the width when tab gets selected. Closing as solved.
