### ISSUE TITLE
Deleted row is displayed again.

### ISSUE THREAD

**Issue by wonhyoung05** [tonytomov/jqGrid#932]
I found the issue that deleted row is show again.
I attached the 'index_dnd_html.txt'.
[index_dnd_html.txt](https://github.com/tonytomov/jqGrid/files/2537264/index_dnd_html.txt)
Full working demo here: 
[delete_demo.zip](https://github.com/tonytomov/jqGrid/files/2537378/delete_demo.zip)

 

The test scenarios are:
1. Move the row with id 11 from grid1 to grid2 ( drag and drop )
2. Sort rows of grid1 by 'Id 1' ( click 'Id 1' )
3. The moved row (id 11) is displayed at grid1 again.

It seems that the issue has occurred because $t.p.data did not updated in function delRowData.

Please refer to comments in the code.

js/jquery.jqGrid.js
```
        delRowData : function(rowid) {
                var success = false, rowInd, ia, nextRow;
                this.each(function() {
                        var $t = this;
                        rowInd = $($t).jqGrid('getGridRowById', rowid);
                        if(!rowInd) {return false;}
                               
                                ... skip

                        if($t.p.datatype === 'local') {
                                var id = $.jgrid.stripPref($t.p.idPrefix, rowid),
                                pos = $t.p._index[id]; //  I guess that if 'datatype: "local" ' line in index_dnd.html  then $t.p._index has the wrong value. 
                                if(pos !== undefined) { //  This conditional statement is false.
                                        $t.p.data.splice(pos,1); // This line is not excuted. So $t.p.data is not updated.
                                        $t.refreshIndex();
                                }
                        }
                });
                return success;
        },
```

**Comment by tonytomov** [comment]
Hello,

Thank you for the test case.

The bug is not in delRowData.

The problem you have is in the grid settings.

You have at the same time 

````js
datatype:'local',
loadonce: true,
...
````

loadonce true does not have sense when the datatype is local, since local data is always present in data parameter.

loadonce have sense only if you load the data from the server and want to make it local.

To solve the problem remove loadonce:true from the both grid settings.

It seems to be a small problem in refreshIndex in case these parameters are set.

I will look at this.

Kind Regards,
Tony

**Comment by wonhyoung05** [comment]
Thank you for response.

After erasing 'loadonce: true', the issue is not occurs.

But there is another issue.

Scenario 1 works well.
But Scenario 2 has an issue.
Please refer below

***
Scenario 1 :
1. Move the row with id 11 from grid1 to grid2 ( drag and drop )
        The row id is "dnd_xxx".
        < tr id="dnd_xxx" ... >
2. Move the row with id 11 from grid2 to grid1 ( drag and drop )
        In delRowData(), "dnd_xxx" row's data is removed from $t.p.data.
3. Sort rows of grid2 by 'ID 2' ( click 'Id 2' )
***
***
Scenario 2 :
1. Move the row with id 11 from grid1 to grid2 ( drag and drop )
        The row id is "dnd_xxx".
        < tr id="dnd_xxx" ... >
2. Sort rows of grid2 by 'ID 2' ( click 'Id 2' )
        The row id is changed.
        < tr id="11"  >
3. Move the row with id 11 from grid2 to grid1 ( drag and drop )
        In delRowData(), "11" row's data is not removed from $t.p.data.
4. Sort rows of grid2 by 'ID 2' ( click 'Id 2' )
5. The "11" row is displayed in grid 2 again.
***

While the addJSONData() function redraws rows, the id is changed.

If modify code like this, senario 2 works well.
( I changed first parameter of constructTr() )
```
        addJSONData = function(data, rcnt, more, adjust) {
                while (i<len) {

                        ... skip

                        //rowData[iStartTrTag] = constructTr(idr, hiderow, (selr ? classes + ' ' + highlight : classes), rd, cur);
                        rowData[iStartTrTag] = constructTr( cur.id || idr, hiderow, (selr ? classes + ' ' + highlight : classes), rd, cur);

                        ... skip

                }
        },
```

**Comment by tonytomov** [comment]
Thanks for the investigation. 

Currently you can omit  this problem if you set autoid to false. The problem is that you have key true in colModel, but in the same way you force generation of id from the gridDnD.

To resolve do the following:

````js
...
jQuery("#jqGrid1").jqGrid('gridDnD',{connectWith:'#jqGrid2', autoid : false}); 
jQuery("#jqGrid2").jqGrid('gridDnD',{connectWith:'#jqGrid1', autoid : false});
...
````
