### ISSUE TITLE
In multiselect mode, deleted row id will be get if it's checked when delete.

### ISSUE THREAD

**Issue by liulinwjzx** [tonytomov/jqGrid#935]
In multiselect mode, deleted row id will be get if it's checked when delete.

Test:
1. Open [http://www.guriddo.net/demo/bootstrap/selection/checkbox/index.html](http://www.guriddo.net/demo/bootstrap/selection/checkbox/index.html).
1. F12 to open console, and check data `1010`.
1. Run code in console to delete `1010`:  `$("#jqGrid").delRowData(1010)`.
1. Check data `1012`, and run code in console: `$("#jqGrid").getGridParam("selarrrow")`, return value is `[1010, 1012]`, but not `[1012]`.

To resolve it, i should do `$jq.resetSelection(rowid).delRowData(rowid)` when server delete data success, I think it's extra invoking and hope it can be repaired.

**Comment by tonytomov** [comment]
Hello,

Thanks. I have fixed the bug. The problem was that the delRowData is called with integer parameter which is used in searching in selarrrow array, which values are string.

If you call it with
````js
...
$("#jqGrid").delRowData("1010");
````
then this will work correct.

Please, let me know if it is fixed for you.

Bear Regards

**Comment by liulinwjzx** [comment]
Thans for fixing. It has fixed in testing page.
