### ISSUE TITLE
exportToHtml，but there is no data

### ISSUE THREAD

**Issue by XShandow** [tonytomov/jqGrid#936]
Thanks for jqgrid.
When I use exportToHtml to print ,there is only header without no data.

JS
`jQuery(#grid-table).jqGrid('navButtonAdd', pager_selector, {
            caption: "Print",
            buttonicon: 'ace-icon fa fa-search-plus grey',
            title: 'Print',
            id: 'Print',
            position: "first",
            onClickButton: function () {
                $("#grid-table").jqGrid("exportToHtml",{
                    includeLabels : true,
                    includeGroupHeader : true,
                    includeFooter: true,
                    autoPrint : true
                });
            }
        });`

JSP:
<link rel="stylesheet" href="<%=basePath%>assets/js/jqGrid/css/ui.jqgrid.css"/>
<link rel="stylesheet"
      href="<%=basePath%>assets/css/bootstrapValidator.min.css"/>
<script type="text/javascript"
        src="<%=basePath%>assets/js/bootstrapValidator.min.js"></script>
<script type="text/javascript" src="<%=basePath%>assets/js/jqGrid/jquery.jqGrid.min.js"></script>

<table id="grid-table"></table>
<div id="grid-pager"></div>

**Comment by XShandow** [comment]
jqGrid JS - v5.3.2
jQuery v2.1.1

**Comment by tonytomov** [comment]
Can you please post the jqGrid setup. The export work only on local data and if there is a datatype:"json" it will not export. I highly recommend you to look at the docs: http://www.guriddo.net/documentation/guriddo/javascript/user-guide/exporting/

**Comment by XShandow** [comment]
Thanks,I use loadonce: true,now it is ok
