### ISSUE TITLE
Excel Export in Jqgrid

### ISSUE THREAD

**Issue by iamarshad** [tonytomov/jqGrid#942]
I have a problem on exporting the Jdgrid table in a PHP Website. I used a button to call the Excel export function, but the function returns "Uncaught TypeError: Cannot read property 'indexOf' of null"
and the error shows in this line
if(o.url.indexOf("?") != -1) { url = o.url+"&"+params; }

of the **excelexport** function. The complete function in the Jqgrid.js is as follows

        excelExport : function(o) {
            o = $.extend({
                exptype : "remote",
                url : null,
                oper: "oper",
                tag: "excel",
                exportOptions : {}
            }, o || {});
            return this.each(function(){
                if(!this.grid) { return;}
                var url;
                if(o.exptype == "remote") {
                    var pdata = $.extend({},this.p.postData);
                    pdata[o.oper] = o.tag;
                    var params = jQuery.param(pdata);
                    if(o.url.indexOf("?") != -1) { url = o.url+"&"+params; }
                    else { url = o.url+"?"+params; }
                    window.location = url;
                }
            });

**Comment by tonytomov** [comment]
Hello,

We know this code very well, but we do not know your code, which causes this error.

Can you please post a demo which demonstrates the problem. Note we require tested and working demo which causes the problem.

Thank you

**Comment by iamarshad** [comment]
Hi, thanks in advance for helping..

Here's my code for the webpage, I have initiated a Jqgrid in this webpage to display a list of items from database. I want that data to be exported to excel format. That I could't able to do. 

<?php $this->load->view('header')
?>
<?php $this->load->view('navigation')
?>
<div class="container main-content innerPage">
	<?php if($this->session->userdata('msg')){
	?>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">
			&times;
		</button>
		<?php echo $this -> session -> userdata('msg'); ?>
	</div>
	<?php } $this->session->unset_userdata('msg'); ?>
	<h5 class="report"> Summary Report By Item. <span class="pull-right" style="margin-top: -5px;"><input id="globalSearchText" class="x-campaigns-filter" type="text" placeholder="Search by Order #, Address, City, Region or MAC #" style="width:328px"><input id="showSearchOption" style="margin-left:10px;margin-bottom:10px;" class="btn btn-default" type="button" value="Search" />
	<input type="button" id="export" value=" Export" style="margin-left:10px;margin-bottom:10px;" class="btn btn-default" />	
	<input id="showAll" class="btn btn-default" style="margin-left:10px;margin-bottom:10px;" type="button" value="Show All" /></span></h5>

	<div class="overFlow">
		<table id="itemlist"></table>
	</div>
	
	<div id="itemlistpagination"></div>
</div>

<script type="text/javascript">var mydata =<?php echo json_encode($items); ?>
	;


	jQuery(document).ready(function($) {
		var sumOQOD=0;
		var sumQTDL=0;
		var containerWidth = $(".main-content").width();
		var containerHeight = $(window).height() - 450;
		var grid = jQuery("#itemlist");
		grid.jqGrid({
			data : mydata,
			datatype : "local",
			height : containerHeight,
			width : containerWidth,
			colNames : ['Item No.', 'Description', ' Total Order Qty',   'Made & At Factory', 'On Ocean', 'In W/H', 'Shipped to WF', 'Open Qty'],
			colModel : [
			{
				name : 'SONO',
				index : 'SONO',
				width : 7,
				align : "center"
			}, {
				name : 'DESCJ1',
				index : 'DESCJ1',
				width : 31
			}, {
				name : 'TQOD',
				index : 'TQOD',
				width : 6,
				align : "center"
			}, {
				name : 'QTFT',
				index : 'QTFT',
				width : 7,
				align : "center"
			}, {
				name : 'QTOC',
				index : 'QTOC',
				width : 5,
				align : "center"
			}, {
				name : 'QTWH',
				index : 'QTWH',
				width : 5,
				align : "center"
			}, {
				name : 'QTDL',
				index : 'QTDL',
				width : 7,
				search : false,
				align : "center",
				sorttype : "float",
				formatter : function(cellvalue, options, rowObject) {
					sumQTDL=sumQTDL+parseInt(cellvalue);
					return '<a href="#shippedWFModal" id="' + rowObject['SONO'] + '" class="getShippedWFSummary" data-toggle="modal">' + cellvalue + '</a>';
				
				},classes: 'blue-text'
			}, 
			{
				name : 'OQOD',
				index : 'OQOD',
				width : 5,
				search : false,
				align : "center",
				sorttype : "float",
				formatter : 'Number',
				formatter : function(cellvalue, options, rowObject) {
					//console.log(rowObject['SONO']);
					
					return '<a href="#openQtyModal" id="' + rowObject['SONO'] + '" class="getOpenQtySummary" data-toggle="modal">' + cellvalue + '</a>';
					sumOQOD=parseInt(cellvalue);
				}
			}
			],
			rowNum : 100,
			rowList : [150,200,250],
			loadonce : true,
			mtype : "GET",
			casesensitive : true,
			rownumbers : false,
			rownumWidth : 40,
			ignoreCase : true,
			gridview : true,
			pager : '#itemlistpagination',
			sortname : 'SONO',
			excelExport: true,
			viewrecords : true,
			footerrow: true,
			gridComplete: function() {
		        var colSum = [];
		        var colSum1 = [];
		        var colSum2 = 'Total';
		        var colSum3 = [];
		        var colSum4 = [];


				sumOQOD = grid.jqGrid('getCol', 'OQOD', true, 'sum');

		        colSum  = grid.jqGrid('getCol', 'OQOD', false, 'sum');

		        //Total Order Qty
		        colSum1 = grid.jqGrid('getCol', 'TQOD', false, 'sum');

		        //colSum = grid.jqGrid('getCol', 'DESCJ1', true, 'sum');

		        colSum3 = grid.jqGrid('getCol', 'QTDL', false, 'sum');
		        colSum4 = grid.jqGrid('getCol', 'QTWH', false, 'sum');

		        grid.jqGrid('footerData', 'set', { OQOD : sumOQOD });

		        grid.jqGrid('footerData', 'set', { TQOD : colSum1 });

		        grid.jqGrid('footerData', 'set', { DESCJ1 : colSum2 });

		        grid.jqGrid('footerData', 'set', { QTDL : sumQTDL });

		        grid.jqGrid('footerData', 'set', { QTWH : colSum4 });
		    },
			loadComplete : function() {
				$("tr.jqgrow:odd").addClass('jqgrow-alt-row');
			},

			sortorder : "asc",
			 onSelectRow: function(cellvalue, options, rowObject) {
			 	var row = grid.getRowData(cellvalue);
			 	var id = row['SONO'];
			 	$('#shippedWFModal').modal('show');
			 	$("#btnModalSubmit2").show();
				$(".modal-body").html('');
				$(".modal-body").addClass('loader');
				$(".modal-body").load('<?php echo base_url(); ?>index.php/main/show_shipped_wf_summary/'+id, function(e){
					$(".modal-body").removeClass('loader');


				});
				
        	}
		})

$("#export").on("click", function(){
			console.log("clicked");
    grid.jqGrid("excelExport",{
      includeLabels : true,
      export: true,
      includeGroupHeader : true,
      includeFooter: true,
      fileName : "items.xlsx",
      excelExport: true,
      maxlength : 40 // maxlength for visible string data 
    })
  })

		grid.jqGrid('navGrid','#itemlistpagination',{add:false,edit:false,del:false});

// add custom button to export the data to excel
grid.jqGrid('navButtonAdd','#itemlistpagination',{
       caption:"",
       id: 'export' ,
       onClickButton : function () { 
           console.log("clicked");
           //grid.jqGrid('excelExport', '#itemlist');
           $("#itemlist").excelExport();

       } 
});

		jQuery('#shippedWFModal').live('shown', function () {
    		jQuery(".modal-body").scrollTop(0);
		});

		jQuery('#openQtyModal').live('shown', function () {
    		jQuery(".modal-body").scrollTop(0);
		});


		$("#globalSearchText").keyup(function() {
			var rules = [], i, cm, postData = grid.jqGrid("getGridParam", "postData"), colModel = grid.jqGrid("getGridParam", "colModel"), searchText = $("#globalSearchText").val(), l = colModel.length;

			for ( i = 0; i < l; i++) {
				cm = colModel[i];
				if (cm.search !== false && ( typeof cm.stype === "undefined" || cm.stype === "text")) {
					rules.push({
						field : cm.name,
						op : "cn",
						data : searchText
					});
				}
			}

			$.extend(postData, {
				filters : {
					groupOp : "OR",
					rules : rules
				}
			});

			grid.jqGrid("setGridParam", {
				search : true,
				postData : postData
			});
			grid.trigger("reloadGrid", [{
				page : 1,
				current : true
			}]);
			return false;
		});

	});
	jQuery("#itemlist").jqGrid('navGrid', '#itemlistpagination', {
		del : false,
		add : false,
		edit : false
	}, {}, {}, {});
	jQuery("#showSearchOption").live("click", function() {
		jQuery("#itemlist").searchGrid({
			recreateFilter : true,
			overlay : true,
			multipleSearch : false,
			multipleGroup : false,
			sopt : ['cn'],
			searchOnEnter : true
		});
	});
	jQuery("#showAll").live("click", function() {
		$("#globalSearchText").val('');
		jQuery("#itemlist").jqGrid("setGridParam", {
			search : ""
		}).trigger("reloadGrid", [{
			page : 1
		}]);
	});

	

</script>





<div class="modal hide fade" id="openQtyModal">

	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">
			x
		</button>
		<h3>Item Summary (Open Qty)</h3>
	</div>

	<div class="modal-body printable"></div>

	<div class="modal-footer">
		<a href="#" id="btnModalSubmit1" class="btn btn-primary">Print</a>
		<a href="#" class="btn btn-warning" data-dismiss="modal">Close</a>
	</div>

</div>

<div class="modal hide fade" id="shippedWFModal">

	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">
			x
		</button>
		<h3>Item Summary (Shipped to WF)</h3>
	</div>

	<div class="modal-body printable"></div>

	<div class="modal-footer">
		<a href="#" id="btnModalSubmit2" class="btn btn-primary">Print</a>
		<a href="#" class="btn btn-warning" data-dismiss="modal">Close</a>
	</div>

</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div id="list" class="span6 offset3"></div>
	</div>
</div>
<style>
@media print {
	table {
		table-layout: fixed;
	}
	table td {
	    padding: 5px;
	    word-break: break-all;
	}
	table td a {
	    display: inline-block;
	}
}
</style>
<script>

	$(function() {
$(".getOpenQtySummary").live("click", function(){
$("#btnModalSubmit1").show();
var id = $(this).attr("id");
$(".modal-body").html('');
$(".modal-body").addClass('loader');
$(".modal-body").load('<?php echo base_url(); ?>index.php/main/show_open_qty_summary/'+id, function(e){
$(".modal-body").removeClass('loader');
});
});

$(".getShippedWFSummary").live("click", function(){
$("#btnModalSubmit2").show();
var id = $(this).attr("id");
$(".modal-body").html('');
$(".modal-body").addClass('loader');
$(".modal-body").load('<?php echo base_url(); ?>index.php/main/show_shipped_wf_summary/'+id, function(e){
$(".modal-body").removeClass('loader');
});
});

});

// When the document is ready, initialize the link so
// that when it is clicked, the printable area of the
// page will print.

$(function(){
// Hook up the print link.
$( "a#btnModalSubmit1" )
.attr( "href", "javascript:void( 0 )" )
.click(
function(){
// Print the DIV.
$( ".printable" ).print();
// Cancel click event.
return( false );
}
);
$( "a#btnModalSubmit2" )
.attr( "href", "javascript:void( 0 )" )
.click(
function(){
// Print the DIV.
$( ".printable" ).print();
// Cancel click event.
return( false );
}
);
});

</script>
  
  
  

<div class="modal hide" id="myModal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">x</button>
      <h3>New User Details</h3>
    </div>
    <div class="modal-body">
    	<form action="<?php echo site_url('main/create_new_user'); ?>" id="register-form" class="form-horizontal" method="post" enctype="multipart/form-data">
        <p><input type="text" class="span4" name="first_name" id="first_name" placeholder="First Name"></p>
        <p><input type="text" class="span4" name="last_name" id="last_name" placeholder="Last Name"></p>
        <p><input type="text" class="span4" name="email" id="email" placeholder="Email"></p>
        <p>
          <select class="span4" name="teamId" id="teamId">
            <option value="">Team Number...</option>
            <option value="1">1</option>
            <option value="2">2</option>
          </select>
        </p>
        <p>
          <label class="checkbox span4">
            <input type="checkbox" id="isAdmin" name="isAdmin"> Is an admin?
          </label>
        </p>
        <p><input type="password" class="span4" name="password" id="password" placeholder="Password"></p>
        <p><input type="password" class="span4" name="password2" id="password2" placeholder="Confirm Password"></p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-warning" data-dismiss="modal">Cancel</a>
      <button id="save" class="btn">Submit</button>
    </div>
  </div>


<?php $this->load->view('footer')
?>


Kindly let me know if you have any questions on this code. I'll be online and clarify them. Thanks again
