### ISSUE TITLE
Adding Multiple headers in Jqgrid

### ISSUE THREAD

**Issue by iamarshad** [tonytomov/jqGrid#943]
How to add two levels of header in Jqgrid. I need the first level of Header for the Titles and the second level of the header for displaying total sum values in the grid.

**Comment by tonytomov** [comment]
Hello,

Call setGroupHeaders two times - one time for the titlea and other time for the summaries. Just test it

**Comment by iamarshad** [comment]
HI tonytomov. Thanks, I tried using setGroupHeaders , For Titles, its working, and for displaying the total values of the jqgrid, its not working. I tried using SetGroupHeaders and SetLabels, its not working as well

This is the code :+1: 

for (var i = 0; i <= mydata.length; i++){
        grid.jqGrid('addRowData', i + 1, mydata[i]);
    }

    grid.jqGrid('setLabel', "SONO"," ");
    grid.jqGrid('setLabel', "DESCJ1","Total");
    grid.jqGrid('setLabel', "TQOD", "colSum");
    grid.jqGrid('setLabel', "QTFT", sumQTDL);
    grid.jqGrid('setLabel', "QTOC", sumQTDL);
    grid.jqGrid('setLabel', "QTWH", sumQTDL);
    grid.jqGrid('setLabel', "QTDL", sumQTDL);
    grid.jqGrid('setLabel', "OQOD", sumQTDL);

grid.jqGrid('setGroupHeaders', {
  useColSpanStyle: false,
  groupHeaders : [
    { startColumnName:'SONO', numberOfColumns:1, titleText:'Item No.' },
    { startColumnName:'DESCJ1', numberOfColumns:1, titleText:'Description' },
    { startColumnName:'TQOD', numberOfColumns:1, titleText:'Total Order Qty' },
    { startColumnName:'QTFT', numberOfColumns:1, titleText:'Made & At Factory' },
    { startColumnName:'QTOC', numberOfColumns:1, titleText:'On Ocean' },
    { startColumnName:'QTWH', numberOfColumns:1, titleText:'In W/H' },
    { startColumnName:'QTDL', numberOfColumns:1, titleText:'Shipped to WF' },
    { startColumnName:'OQOD', numberOfColumns:1, titleText:'Open Qty' }


  ]
});

The ColSum1 and sumQTDY are the total values added frm grid

**Comment by tonytomov** [comment]
I really do not understand what you try to do.

Can you please show me with picture wheat is your goal? How the grid should look like?

Thanks

**Comment by iamarshad** [comment]
![Capture](https://user-images.githubusercontent.com/47967201/55326659-e9c74b00-54a5-11e9-976b-054551b2fa13.JPG)
 Hi Tony,
U see in this picture, I have created 2 headers, I have used the first header for Titles, and i need the second header to have the total values of their respective columns. I have that already in the footer, But it has to be presented on top. And do you know that if there is anyway that we might include Mysql query in Jqgrid

**Comment by tonytomov** [comment]
The upcoming release will support this feature. 
What is the problem with your code? This should work or your totals does not appear?

**Comment by iamarshad** [comment]
The problem with my code here is I couldn't know how to display these totals in header.

**Comment by tonytomov** [comment]
With setLabels as you do this should work.

The problem that I see is from where you get these values  ColSum1 and sumQTDY and when you set the labels. Question - From where is the value of colSum1?

**Comment by tonytomov** [comment]
As for the Mysql binding you can do this. Since Guriddo jqGrid is commercial product I recommend you to use our other commercial Suito PHP. Demo here: http://www.guriddo.net/demo/demos/jqgrid/ and more on this product you can find on our http://www.guriddo.net site

**Comment by tonytomov** [comment]
The faeture is added: https://github.com/tonytomov/jqGrid/commit/e75e5eb928b3c80fbce3a3d61d1ff935374e654a
