### ISSUE TITLE
How do I close the horizontal scroll bar?

### ISSUE THREAD

**Issue by Heavenzhao** [tonytomov/jqGrid#944]
How do I close the horizontal scroll bar? Please tell me.

**Comment by ssmathivanan402** [comment]
I have fix the issues in two way. by manually assign the width of the last *td
*and another one is set the srinktofit:true and set the width in grid
initialization itself.

**Comment by tonytomov** [comment]
Ok. Will close it

**Comment by Heavenzhao** [comment]
Thank you very much for your reply! I'll try it. @ssmathivanan402
