### ISSUE TITLE
 I found the actual version of the jquery.jqGrid.min.js file in version 4.5.3 to 4.6.0 is 4.5.2

### ISSUE THREAD

**Issue by ly641921791** [tonytomov/jqGrid#947]
I found the actual version of the jquery.jqGrid.min.js file in version 4.5.3 to 4.6.0 is 4.5.2.

**Comment by ly641921791** [comment]
This caused bugs in some other projects, such as https://github.com/webjars/jqgrid/issues/3

**Comment by tonytomov** [comment]
Can you please post example?  I expect to see from where this file is downloaded and what is exactly the bug?

**Comment by ly641921791** [comment]
Sorry, my statement has a problem.  

The upstream file used by the [webjars/jqgrid](https://github.com/webjars/jqgrid) project is current project. The actual version of the jquery.jqGrid.min.js file in the current project from 4.5.3 to 4.6.0 is 4.5.2.

So when jqGrid is introduced through the [webjars/jqgrid](https://github.com/webjars/jqgrid) of version 4.5.3 to 4.6.0, and the jquery.jqGrid.min.js file is used, the version 4.5.2 of jquery.jqGrid.min.js is actually used.
