### ISSUE TITLE
Problem with Default Search Value

### ISSUE THREAD

**Issue by unle70** [tonytomov/jqGrid#949]
Hello,
I'm testing version 5.4.0 and saw a problem.
When defining a default search value for a column:
`colModel: [ {name: 'col-a', searchoptions: { defaultValue: 'abcd' } } ]`

It works OK and the value appears as default for that 'col-a'. If I then change this value and press the 'x' button (to clear the search field) it goes back to the same default value, which is acceptable.

But then I try to push the 'x' button on any OTHER column search field and surprisingly the default value of 'col-a' is set as default in ALL the other columns as well.

I tried checking this in an old fiddle for version 4.6.x and didn't see the same problem there.
Now I'm wondering if it's just my environment or a bug in version 5.4.0.

**Comment by tonytomov** [comment]
Thanks. We already have been notified about [this problem](http://www.trirand.com/blog/?p=1674&cpage=1#comment-113810). The problem is fixed (see today commit). Please let us know if there is a problem or everything is working as expected

**Comment by unle70** [comment]
Thanks Tony.
Solved the problem for me.
