### ISSUE TITLE
colTotals without formatting in pivot

### ISSUE THREAD

**Issue by Rknorr-Logica** [tonytomov/jqGrid#952]
Found that commit ce6b148 on 12 Jun (tonytomov - Header and Footer user data should be not formated. The should comm in raw format) makes colTotals : true formatting to be ignored. 

Is there a new way to set formatting for this summary? For now i just changed back those lines prior to this version as i am not using user data on footer or header.

**Comment by tonytomov** [comment]
Thanks. I will try to fix this this week

**Comment by tonytomov** [comment]
Sorry for the late fix, but better late, than never ;-)
