### ISSUE TITLE
InlineEdit on null value

### ISSUE THREAD

**Issue by microcipu** [tonytomov/jqGrid#954]
https://github.com/tonytomov/jqGrid/blob/0e68781e95360a8d31dd7bf51b9d4e4b5ebe28b9/js/grid.inlinedit.js#L99

When trying to edit a null line this validation breaks tmp.length===1 && tmp.charCodeAt(0)===160
pls add tmp !== null

**Comment by tonytomov** [comment]
Can you please post demo on which case you get "pure" null?
Thank you
