### ISSUE TITLE
Pagination control are not accessible using Keyboard in JQGrid 4.4.4

### ISSUE THREAD

**Issue by Raunak0786** [tonytomov/jqGrid#956]
**Problem** If controls are not accessible through keyboard then the users who rely on keyboard will not able to perform any action on controls which are not accessible by keyboard.
**Repro Steps**:
Open any JQGrid version 4.4.4
Navigate to table
Verify below scenario
a)Pagination control are accessible by keyboard or not

**Expected Result**:
a) Pagination control should be accessible by keyboard 

#JQGrid

**Comment by tonytomov** [comment]
The current supported version is 5.4. The version 4.4 is seven(7) years old and is not supported. Sorry.

**Comment by Raunak0786** [comment]
Hi Tony,
We also tested the current JQGrid version 5.4.0 and found that below scenario is not fix in JQgrid
1. Pagination control are not accessible using keyboard

![image](https://user-images.githubusercontent.com/55841857/70235721-79d23880-1789-11ea-81a4-f36afcec926a.png)

**Comment by tonytomov** [comment]
This feature was never available in jqGrid as of its creation - so I will say that it should not be fixed - maybe you mean that this should be updated..

**Comment by tonytomov** [comment]
If you run aria grid these controls are available with the keyboard.
Look [here please](http://guriddo.net/demo/guriddojs/functionality/keyb_navigation/).
