### ISSUE TITLE
inlineNav Save to database

### ISSUE THREAD

**Issue by NJDave71** [tonytomov/jqGrid#958]
I am able to save data from the form to a Database but I  am unable to figure out how to do this via inlineNav.  

This is what I am doing in the form
```
datatype: "json",
url: "index.aspx/updateRecords",
ajaxEditOptions: { contentType: "application/json; charset=utf-8" },
serializeEditData: function (postData) {
            var postdata = { 'data': postData };
            return JSON.stringify(postdata);
   }
```
this sends back an Object that i can handle in C#.

Trying to do the same inline and not having any luck
Thanks

**Comment by tonytomov** [comment]
I suppose you do not have consult the docs. For inline edit there is other serialize method. You may find it [here](http://www.guriddo.net/documentation/guriddo/javascript/user-guide/editing/#inline-editing)
