### ISSUE TITLE
Pager info is hide depending on container width

### ISSUE THREAD

**Issue by mariohs22** [tonytomov/jqGrid#959]
When container width <= 907 px ".ui-paging-info" is hidden.
When container width > 907 px ".ui-paging-info" is shown.
I use this solution:
loadComplete: function(){$(".ui-paging-info").show();}

**Comment by tonytomov** [comment]
Hello,
This is not a solution. The solution will be performed if you put a real working example which demonstrates the problem.

**Comment by mariohs22** [comment]
Oh, sorry. I have set the 'responsive' option to 'true', with the 'false' pager info is shown.
