### ISSUE TITLE
rowNum is getting changed in treeGrid with pagination

### ISSUE THREAD

**Issue by avnish1306** [tonytomov/jqGrid#962]
When the grid type is tree grid and pagination is true then th "rowNum" which is number of rows in a page is getting changed to 10000 because there is a mistake in **setTreeGrid** function as `if($t.p.rowTotal === null ) { $t.p.rowNum = 10000; }` 
**`$t.p.rowNum =10000 should be $t.p.rowTotal = 10000;`**
![treeGridIssue](https://user-images.githubusercontent.com/28188933/73258249-50fb7c00-41eb-11ea-805d-5b461218de01.PNG)

**Comment by tonytomov** [comment]
You use a old version of jqGrid. Use the latest one.
