### ISSUE TITLE
Accessibility issues in JQGrid 4.4.4 : Narrator focus moves to the blank header

### ISSUE THREAD

**Issue by Raunak0786** [tonytomov/jqGrid#965]
**Proble :**  Screen reader focus moves to the blank header in the JQGrid
**Repro Steps:**
Open any JQGrid version 4.4.4 having expandable rows 
Turn on Narrator and navigate to the table 
Verify below scenario
Screen reader focus is moving to some hidden elements available along with table header .
Refer the screen shot attached 
#JQGrid

![image](https://user-images.githubusercontent.com/55841857/74919150-2ff40880-53f0-11ea-9bdc-9e5872f8378a.png)

**Comment by tonytomov** [comment]
In order to prevent publishing more problems you will need to know that jqGrid version 4.4.4 is no more supported.

**Comment by Raunak0786** [comment]
Thanks for the information . Can you please share the supported JQGrid version where I can reverify these issues ?
