### ISSUE TITLE
Accessibility issues in JQGrid 4.4.4 : In scan mode Narrator reads all the headers and grid content in one go

### ISSUE THREAD

**Issue by Raunak0786** [tonytomov/jqGrid#966]
**Problem**  In scan mode Narrator reads all the headers and grid's data in one go when focus in at the beginning of the grid
**Repro Steps:**
Open any JQGrid version 4.4.4
Turn on Narrator and switch on Scan  mode. Navigate to the start of the grid .
Verify below scenario
All the headers and grid's data is read by Narrator in one go
**Expected Result:**
Narrator should not read all the headers along with the content in one go 
#JQGrid

**Comment by tonytomov** [comment]
In order to prevent publishing more problems you will need to know that jqGrid version 4.4.4 is no more supported.

**Comment by Raunak0786** [comment]
Thanks for the information . Can you please share the supported JQGrid version where I can reverify these issues ? Would appreciate if you can help me with some sample

**Comment by tonytomov** [comment]
Use the latest release 5.4.0

**Comment by Raunak0786** [comment]
Hi Tony, 
Can you please help me with the documentation\release notes of this JQGrid 5.4.0 to understand what are the new features supported in this version in terms of functionality and accessibility . 

Thanks.

**Comment by tonytomov** [comment]
http://www.guriddo.net/documentation/guriddo/javascript/about/release-notes/

**Comment by tonytomov** [comment]
Will close the issue. You can reopen it if you need this.
