### ISSUE TITLE
What is free and what is paying?

### ISSUE THREAD

**Issue by Mrodent** [tonytomov/jqGrid#968]
Sorry to ask this here, but I just tried to register for your jqGrid forum on the Gurrido site. I tried twice, with two different emails, and passed the "Captcha" test twice. I looked in Spam. I didn't receive an email either time: maybe you might look into that.

I just wanted to ask: given that I can download the latest release (5.4.0) from this Github site, what is it that I receive, and what do I not receive: what is paying and what is free? I'm a little confused.

I believe this project started off for free as a JQuery plugin (https://plugins.jquery.com/jqGrid/) ... but then became paying after 4.6.0. in 2014.

**Comment by tonytomov** [comment]
Hello,

Sorry for this inconvenience. I have looked at our system and there was really two registrations yesterday (suppose yours). Everything seems to be correct. Not sure what is happen. I can generate new password for you and send it automatically to the e-mails.

In Github is the last development and of course all official releases. As source you get everything you need to develop applications using Guriddo jqGrid. 

The product is under [Creative Commons Attribution-Non-Commercial 3.0 License](http://creativecommons.org/licenses/by-nc/3.0/) this mean:
You can use our software for free under the [non-commercial](http://creativecommons.org/licenses/by-nc/3.0/) license when you are:

- A student, university or a public school
- A non-profit organisation
- Developing and testing applications using Guriddo jqGrid/Suito

If something is not clear, please let me know I will try to answer all of your questions.

**Comment by Mrodent** [comment]
Thanks. Maybe you could send it (password), please?  I just checked: I still haven't received anything (including in Spam).

I'm a TDD fanatic. As a matter of interest, can you say how much of this project has been developed using TDD? I downloaded the 5.4.0 release yesterday and had a look: I couldn't see any testing files.

**Comment by tonytomov** [comment]
Hello,

We have send new password to your e-mails.

Unfortunately, we use traditional tests. We are old (boys) to use this new approach. Note that jqGrid started back in 2007 as a hobby project and believe me I didn't know what TDD was at the time. But until recently I also hadn't heard what it was ;-)

**Comment by Mrodent** [comment]
Got the email and managed to log on. Re TDD: yes, I understand and am not surprised by what you say!

**Comment by tonytomov** [comment]
I will close the issue. Feel free to reopen it if you think you need this.
