### ISSUE TITLE
treeGrid with local can't be show

### ISSUE THREAD

**Issue by mssk12315** [tonytomov/jqGrid#970]
I use treeGrid with local data, is can't be show

it's return by this code, i want know why need return here, thanks!

if(ts.p.treeGrid && ts.p._sort) {
    $(ts).jqGrid("SortTree", st, ts.p.sortorder, cmtypes[st].stype || 'text', cmtypes[st].srcfmt || '');
    return;
}

**Comment by tonytomov** [comment]
I close this. In case you are able to show us demo reproducing the problem, please reopen the issue
