### ISSUE TITLE
Local special characters are sorted wrong when sorting columns. Please change to localeCompare()

### ISSUE THREAD

**Issue by SKPFCW** [tonytomov/jqGrid#982]
German umlauts appear after sorting at the end of the list instead of in their correct place.
JavaScript localeCompare-Method should be used instead of greater/less-comparison.

For example:
Correct sorting would be: 
Am, An, Ao, **Aö**, Ap, Aq

Wrong sorting in jqGrid is: 
Am, An, Ao, Ap, Aq, **Aö**

The error occurs in the function this._compare by using binary greater-/less-than comparison: (Versions 5.5.4 and before)

```
529: this._compare = function (a, b, d) {
...
552:     if (a <b) {return -d;}
553:     if (a> b) {return d;}
554:     return 0;
```
    
Hotfix by using the JS localeCompare()-method:
```
552:-3     if (typeof a === "string") {
552:-2         return a.localeCompare(b) * d;
552:-1    } else {
552:             if (a <b) {return -d; }
553:             if (a> b) {return d; }
554:             return 0;
554:+1    }
```

**Comment by tonytomov** [comment]
I have fixed the problem. You can check it. Please let me know if it is ok for you.

**Comment by SKPFCW** [comment]
It works great. Thank you for your quick and helpful support.

**Comment by tonytomov** [comment]
I will close the issue. Feel free to reopen it, if there is a problem
