### ISSUE TITLE
Excel export: Error message when opening a excel file if a grid is exported multiple times to excel.

### ISSUE THREAD

**Issue by SKPFCW** [tonytomov/jqGrid#983]
When I export a grid to excel, I can only open the excel file the first time without an error message. If I export it again afterwards, I get an error message when opening the file with Excel:

Environment
jqGrid 5.5.4 / WIN10 / Edge Chromium 90 / Chrome 89 / MS Office Pro+ 2016

Using your demo: [http://guriddo.net/demo/guriddojs/export/customexcel/](http://guriddo.net/demo/guriddojs/export/customexcel/)

Click "Export to Excel"
Wait for the download to finish
Open the downloaded file with excel -> **no Problem**
Close excel application.

Click "Export to Excel" again
Wait for the second download to finish
Open the newly downloaded file with excel -> **Error message occurs:**

> **We have identified a problem with some of the content in "jqGridExport (2) .xlsx". Should we restore as much as possible? If you trust the source of this workbook, click "Yes".**

After reloading the page, opening the downloaded excel file works again the on the first time.

**Comment by SKPFCW** [comment]
Update: I unzipped and compared the excel files (the one that opens (=correctFile.xlsx) and one that generates an error message when opening (=failedF
[failedFile.xlsx](https://github.com/tonytomov/jqGrid/files/6359067/failedFile.xlsx)
[correctFile.xlsx](https://github.com/tonytomov/jqGrid/files/6359068/correctFile.xlsx)

ile.xlsx)). There are differences in the file xl\styles.xml. These are the differences:

### File xl\styles.xml
**Paragraph <numFmts>**
```
correctFile: <numFmts count="8">
failedFile: <numFmts count="7">

correctFile: <numFmt numFmtId="171" formatCode="[$$-45C]* ###0.00_-;[$$-45C]* (###0.00_-)"/>
failedFile: =missing line
```

**Paragraph <cellXfs count>:**
```
correctFile: <cellXfs count="68">
failedFile: <cellXfs count="67">

correctFile: <xf numFmtId="171" fontId="0" fillId="0" borderId="0" applyFont="1" applyFill="1" applyBorder="1" xfId="0" applyNumberFormat="1"/>
failedFile: =missing line
```

Hope this helps.

**Comment by tonytomov** [comment]
Hello,

Thank you very much. Your investigations helped a lot. We have fixed the problem. Please let us know if the issues is fixed for you.

Thank you.

**Comment by SKPFCW** [comment]
Our first tests did not show any problems anymore. 
Thank you for the quick and competent help. 
I am closing this issue.
