### ISSUE TITLE
"setCell" method not set cell attributes when nData parameter value is empty string

### ISSUE THREAD

**Issue by LuckyTil** [tonytomov/jqGrid#985]
"setCell" method not set cell attributes when nData parameter value is empty string.

Proposed fix:
if(nData !== "" || forceupd === true ) {
...
}
// fix {
else {
    ohtml = tcell;
}
// fix }

Works for me fine.

**Comment by tonytomov** [comment]
Thanks. Will test it too.

**Comment by tonytomov** [comment]
Could not see a problem See:https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L6243  . Which version of jqGrid is used?

**Comment by LuckyTil** [comment]
> Which version of jqGrid is used?
tagged 5.5.4

**Comment by LuckyTil** [comment]
Yes, this fixed in 'master'.
Thank You.
