### ISSUE TITLE
"resizeGrid" strange behavior when is responsive and height set to "auto"

### ISSUE THREAD

**Issue by PaolaRuby** [tonytomov/jqGrid#995]
Height keeps growing when resizeGrid is called or when is reponsive and trigger orientationEvent
Example [https://jsfiddle.net/v47kqrx9/3/](https://jsfiddle.net/v47kqrx9/3/)
![image](https://user-images.githubusercontent.com/79208489/121385917-2bb66c00-c90f-11eb-980f-a82dab6bd1c0.png)
maybe  `if($t.p.height  !== 'auto' && typeof height !== 'boolean' ) {` or only where `$t.p.height === '100%'` on
https://github.com/tonytomov/jqGrid/blob/bf643639f5f6b8953e03a14cd4af094d3903282b/js/grid.base.js#L6995 but on `$("#gbox_"+$.jgrid.jqID($t.p.id)).parent().height()` is the problem when parent has more elements, maybe the `$t.p.height === 100%` here
https://github.com/tonytomov/jqGrid/blob/bf643639f5f6b8953e03a14cd4af094d3903282b/js/grid.base.js#L7021-L7025

----

also, `var wh = $t.p.height,` is mislocated
https://github.com/tonytomov/jqGrid/blob/bf643639f5f6b8953e03a14cd4af094d3903282b/js/grid.base.js#L7008-L7009 i beleaves must be in
https://github.com/tonytomov/jqGrid/blob/bf643639f5f6b8953e03a14cd4af094d3903282b/js/grid.base.js#L7021-L7022 so `var bstw = $t.p.styleUI.search('Bootstrap') !== -1 && !isNaN(wh) ? 2 : 0` 
and maybe it should take `wh` when is set instead of the height of "parent"

**Comment by MymsMan** [comment]
I have also noticed this annoying behaviour 
If a table has insufficient rows (or filtering has reduced the number displayed) to fill a full screen the grid initially resizes to avoid white space at the bottom but a soon as the window width changes the table depth expands to the full window depth even if there is no data to display in the extra space.

**Comment by fredsal** [comment]
+1

**Comment by erikn69** [comment]
+1

**Comment by tonytomov** [comment]
@PaolaRuby  
Thank you. Good catch.
I'm not sure how to process with this.

The same problem apply to the width. In your example add another p element and set is a float: right by example - you will see the similar problem.

For now I will fix only the check for height auto and miss-location of the 

`var wh = $t.p.height`

Hope that we will have a fruitful discussion to resolve this problem.

**Comment by PaolaRuby** [comment]
Thank you, `height='auto'` works for me, also see the width problem, but i haven't left/right elements

**Comment by tonytomov** [comment]
Hello,

Will close it. If there is a problem, please reopen it.

Thank you.

Best Regards,
Tony
