### ISSUE TITLE
"autowidth" strange behavior at start and after `resizeGrid`

### ISSUE THREAD

**Issue by PaolaRuby** [tonytomov/jqGrid#996]
grid has a scrollbar's space at start, but after `resizeGrid` or trigger orientationEvent(responsive) the scrollbar's space disappears
Example [https://jsfiddle.net/f5vcd0z3/](https://jsfiddle.net/f5vcd0z3/) (look at the right of the grid)
![image](https://user-images.githubusercontent.com/79208489/121433701-f8410500-c941-11eb-9f1f-d7223d604725.png)
After resizeGrid or orientationEvent 
![image](https://user-images.githubusercontent.com/79208489/121433588-d778af80-c941-11eb-9c32-ea5c8a2c763e.png)
When fill the grid
![image](https://user-images.githubusercontent.com/79208489/121435799-1c521580-c945-11eb-9eeb-d5e2ad89e2c9.png)

console.log()
```
"----Initial widths----"
"#grid1: ",      480
"#gbox_grid1: ", 500
"----After resize widths----"
"#grid1: ",      500
"#gbox_grid1: ", 500
```
----
**UPDATE:** With `$('#grid1 #norecs').remove();` after grid creation, makes scrollbar's space works again when resizeGrid or orientationEvent are called but only shows one row, `emptyRecordRow` breaks something?
[https://jsfiddle.net/jnbkq7cv/](https://jsfiddle.net/jnbkq7cv/)
```
"----Initial widths----"
"#grid1: ",      480
"#gbox_grid1: ", 500
"----After resize widths----"
"#grid1: ",      480
"#gbox_grid1: ", 500
```

**Comment by tonytomov** [comment]
Hello,

Thank you,  I will check this and replay ASAP.

**Comment by PaolaRuby** [comment]
@tonytomov [Jquery deprecated-3.4](https://api.jquery.com/category/deprecated/deprecated-3.4/), so eq, first are deprecated?

https://github.com/tonytomov/jqGrid/blob/a2a83d4ce5c5948b14505712da73b8a76a2a76e0/js/jquery.jqGrid.js#L5559-L5563

**Comment by tonytomov** [comment]
@PaolaRuby Thanks for this.
Since the above problem is quite different for the first originally published, can you please open new issue.
I will delete this one

Thank you

**Comment by tonytomov** [comment]
Hello,

Sorry for delay. I have found and fixed the problem. Please let me know if it is ok for you. 
In case it is fixed, please close the issue.
Thank you again.

Best Regards,
Tony

**Comment by PaolaRuby** [comment]
@tonytomov now it's working, thanks a lot

**Comment by PaolaRuby** [comment]
@tonytomov maybe the same issue diferent steps
**UPDATED EXAMPLE:** [https://jsfiddle.net/pafhs8nd/1/](https://jsfiddle.net/pafhs8nd/1/)
**STEPS:**
First fill partially the grid(there is a scrollbar space)
![image](https://user-images.githubusercontent.com/79208489/123665289-c4992280-d7fd-11eb-8b87-4deea7e7ba2d.png)
Then trigger `resizeGrid`
![image](https://user-images.githubusercontent.com/79208489/123665451-ea262c00-d7fd-11eb-9df5-785f548058c3.png)
For last fill with big data the grid
![image](https://user-images.githubusercontent.com/79208489/123665656-18a40700-d7fe-11eb-87a6-95deb3647668.png)

**Comment by tonytomov** [comment]
@PaolaRuby ,

Thanks for investigations. This is correct behavior. 
The reason for this is that addRowData does not care about the scroll - sorry.
After second fill calling resizeGrid will make it correct
